// docs/app/demos/en/drawer/locked.vue
<script setup lang="ts">
  import { ref } from 'vue'
  import { Button, Drawer, Text } from '@hina-ui/vue'

  const open = ref(false)
  const saving = ref(false)

  function save() {
    saving.value = true
    setTimeout(() => {
      saving.value = false
      open.value = false
    }, 2000)
  }
</script>

<template>
  <Drawer
    v-model:open="open"
    title="Edit tags"
    description="Please keep this drawer open while it saves."
    :locked="saving"
  >
    <Button variant="outline" tone="neutral">Edit tags</Button>
    <template #content>
      <Text>
        {{
          saving
            ? 'Saving. It closes on its own in two seconds.'
            : 'Saving locks the drawer for two seconds.'
        }}
      </Text>
    </template>
    <template #footer="{ close }">
      <Button variant="soft" tone="neutral" :disabled="saving" @click="close">Cancel</Button>
      <Button :loading="saving" @click="save">Save</Button>
    </template>
  </Drawer>
</template>

// docs/react/demos/en/drawer/locked.tsx
'use client'

import { useState } from 'react'
import { Button, Drawer, Text } from '@hina-ui/react'

export default function Demo() {
  const [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false)

  function save() {
    setSaving(true)
    setTimeout(() => {
      setSaving(false)
      setOpen(false)
    }, 2000)
  }

  return (
    <Drawer
      open={open}
      onOpenChange={setOpen}
      title="Edit tags"
      description="Please keep this drawer open while it saves."
      locked={saving}
      renderContent={() => (
        <Text>
          {saving
            ? 'Saving. It closes on its own in two seconds.'
            : 'Saving locks the drawer for two seconds.'}
        </Text>
      )}
      renderFooter={({ close }) => (
        <>
          <Button variant="soft" tone="neutral" disabled={saving} onClick={close}>
            Cancel
          </Button>
          <Button loading={saving} onClick={save}>
            Save
          </Button>
        </>
      )}
    >
      <Button variant="outline" tone="neutral">
        Edit tags
      </Button>
    </Drawer>
  )
}
