// docs/app/demos/en/drawer/navigation.vue
<script setup lang="ts">
  import { BookOpen, Home, Library, Settings, User } from '@lucide/vue'
  import { Button, Drawer, NavLink, Stack } from '@hina-ui/vue'
</script>

<template>
  <Drawer title="Navigation" side="start" size="sm">
    <Button variant="outline" tone="neutral">Menu</Button>
    <template #content>
      <Stack gap="xs">
        <NavLink href="#" label="Home" active>
          <template #icon>
            <Home />
          </template>
          Home
        </NavLink>
        <NavLink href="#" label="Library">
          <template #icon>
            <Library />
          </template>
          Library
        </NavLink>
        <NavLink href="#" label="Reading history">
          <template #icon>
            <BookOpen />
          </template>
          Reading history
        </NavLink>
        <NavLink href="#" label="Profile">
          <template #icon>
            <User />
          </template>
          Profile
        </NavLink>
        <NavLink href="#" label="Settings">
          <template #icon>
            <Settings />
          </template>
          Settings
        </NavLink>
      </Stack>
    </template>
  </Drawer>
</template>

// docs/react/demos/en/drawer/navigation.tsx
'use client'

import { BookOpen, Home, Library, Settings, User } from 'lucide-react'
import { Button, Drawer, NavLink, Stack } from '@hina-ui/react'

export default function Demo() {
  return (
    <Drawer
      title="Navigation"
      side="start"
      size="sm"
      renderContent={() => (
        <Stack gap="xs">
          <NavLink href="#" label="Home" active icon={<Home />}>
            Home
          </NavLink>
          <NavLink href="#" label="Library" icon={<Library />}>
            Library
          </NavLink>
          <NavLink href="#" label="Reading history" icon={<BookOpen />}>
            Reading history
          </NavLink>
          <NavLink href="#" label="Profile" icon={<User />}>
            Profile
          </NavLink>
          <NavLink href="#" label="Settings" icon={<Settings />}>
            Settings
          </NavLink>
        </Stack>
      )}
    >
      <Button variant="outline" tone="neutral">
        Menu
      </Button>
    </Drawer>
  )
}
