// packages/vue/src/components/data-table/DataTableText.vue
<script setup lang="ts">
  import { shallowRef } from 'vue'
  import { vTooltip } from '../tooltip/directive'
  import { useTableText } from './composables/useTableText'
  const props = defineProps<{ value: string | number; truncate?: boolean }>()
  const element = shallowRef<HTMLElement>()
  const { overflow, tooltip } = useTableText(element, () => props.value)
</script>
<template>
  <span
    v-if="truncate"
    ref="element"
    v-tooltip="tooltip"
    class="block truncate"
    :tabindex="overflow ? 0 : undefined"
  >
    {{ value }}
  </span>
  <template v-else>{{ value }}</template>
</template>

// packages/react/src/components/data-table/DataTableText.tsx
'use client'

import { useState } from 'react'
import { TooltipTarget } from '../float-button/TooltipTarget'
import { useTableText } from './hooks/useTableText'

export interface DataTableTextProps {
  value: string | number
  truncate?: boolean
}

function TruncatedText({ value }: { value: string | number }) {
  const [element, setElement] = useState<HTMLSpanElement | null>(null)
  const { overflow, tooltip } = useTableText(element, value)
  return (
    <>
      <span ref={setElement} className="block truncate" tabIndex={overflow ? 0 : undefined}>
        {value}
      </span>
      <TooltipTarget target={element} options={{ content: tooltip || '' }} />
    </>
  )
}

export function DataTableText({ value, truncate }: DataTableTextProps) {
  return truncate ? <TruncatedText value={value} /> : <>{value}</>
}
