// packages/vue/src/components/splitter/Splitter.vue
<script setup lang="ts">
  import { SplitterGroup } from '../../primitives/splitter'
  import { cn } from '../../lib/cn'

  defineOptions({ name: 'HnSplitter' })

  const props = withDefaults(
    defineProps<{
      direction?: 'horizontal' | 'vertical'
      autoSaveId?: string
      class?: string
    }>(),
    { direction: 'horizontal' },
  )
</script>

<template>
  <div :class="cn(props.class)">
    <SplitterGroup :direction="props.direction" :auto-save-id="props.autoSaveId">
      <slot />
    </SplitterGroup>
  </div>
</template>

// packages/react/src/components/splitter/Splitter.tsx
import type { HTMLAttributes, Ref } from 'react'
import { cn } from '../../lib/cn'
import { SplitterGroup } from '../../primitives/splitter'

export interface SplitterProps extends HTMLAttributes<HTMLDivElement> {
  direction?: 'horizontal' | 'vertical'
  autoSaveId?: string
  ref?: Ref<HTMLDivElement>
}

export function Splitter({
  direction = 'horizontal',
  autoSaveId,
  className,
  children,
  ...attrs
}: SplitterProps) {
  return (
    <div {...attrs} className={cn(className)}>
      <SplitterGroup direction={direction} autoSaveId={autoSaveId}>
        {children}
      </SplitterGroup>
    </div>
  )
}
