// packages/vue/src/components/tooltip/Tooltip.vue
<script setup lang="ts">
  import { TooltipRoot, TooltipTrigger } from 'reka-ui'
  import TooltipBubble from './TooltipBubble.vue'
  import type { TooltipProps } from './types'

  defineOptions({ name: 'HnTooltip' })

  const props = withDefaults(defineProps<TooltipProps>(), {
    open: undefined,
    disabled: false,
  })
</script>

<template>
  <TooltipRoot :open="props.open" :disabled="props.disabled" ignore-non-keyboard-focus>
    <TooltipTrigger as-child>
      <slot />
    </TooltipTrigger>
    <TooltipBubble v-bind="props">
      <slot name="content">{{ props.content }}</slot>
    </TooltipBubble>
  </TooltipRoot>
</template>

// packages/react/src/components/tooltip/Tooltip.tsx
import type { ReactElement } from 'react'
import { TooltipRoot, TooltipTrigger } from '../../primitives/tooltip'
import { TooltipBubble } from './TooltipBubble'
import type { TooltipProps } from './types'

export interface TooltipComponentProps extends TooltipProps {
  children: ReactElement
}

export function Tooltip({ open, disabled = false, children, ...props }: TooltipComponentProps) {
  return (
    <TooltipRoot open={open} disabled={disabled} ignoreNonKeyboardFocus>
      <TooltipTrigger asChild>{children}</TooltipTrigger>
      <TooltipBubble {...props} open={open} disabled={disabled} />
    </TooltipRoot>
  )
}
