// packages/vue/src/components/accordion/AccordionContent.vue
<script setup lang="ts">
  import { AccordionContent as RekaAccordionContent } from '../../primitives/accordion'
  import { cn } from '../../lib/cn'
  import { rekaAccordionStyle } from '../../lib/reka/styles'
  import { useCollapseGap } from '../../lib/collapse'
  import { accordionContent } from './accordion.variants'

  defineOptions({ name: 'HnAccordionContent' })

  const props = defineProps<{ class?: string }>()

  const content = useCollapseGap()
</script>

<template>
  <RekaAccordionContent
    ref="content"
    :class="cn(accordionContent(), props.class)"
    :style="rekaAccordionStyle"
  >
    <div class="pb-4">
      <slot />
    </div>
  </RekaAccordionContent>
</template>

// packages/react/src/components/accordion/AccordionContent.tsx
'use client'

import { useComposedRefs } from 'radix-ui/internal'
import { cn } from '../../lib/cn'
import { useCollapseGap } from '../../lib/collapse'
import { radixAccordionStyle } from '../../lib/radix/styles'
import {
  AccordionContent as AccordionContentPrimitive,
  type AccordionContentProps as AccordionContentPrimitiveProps,
} from '../../primitives/accordion'
import { accordionContent } from './accordion.variants'

export interface AccordionContentProps extends Omit<
  AccordionContentPrimitiveProps,
  'as' | 'asChild' | 'forceMount'
> {}

export function AccordionContent({
  className,
  style,
  children,
  ref,
  ...attrs
}: AccordionContentProps) {
  const content = useCollapseGap<HTMLElement>()
  const composedRef = useComposedRefs(ref, content)
  return (
    <AccordionContentPrimitive
      ref={composedRef}
      {...attrs}
      className={cn(accordionContent(), className)}
      style={{ ...radixAccordionStyle, ...style }}
    >
      <div className="pb-4">{children}</div>
    </AccordionContentPrimitive>
  )
}
