// docs/react/demos/en/scroll-area/focusable.tsx
import { ScrollArea, Stack, Text } from '@hina-ui/react'

const lines = Array.from({ length: 10 }, (_, i) => i + 1)

export default function Demo() {
  return (
    <ScrollArea
      focusable
      label="Release notes"
      className="bg-inset h-32 w-full max-w-sm rounded-md"
    >
      <Stack className="p-4">
        {lines.map(i => (
          <Text key={i}>Line {i}</Text>
        ))}
      </Stack>
    </ScrollArea>
  )
}

// docs/app/demos/en/scroll-area/focusable.vue
<script setup lang="ts">
  import { ScrollArea, Stack, Text } from '@hikarinagi/ui'
</script>

<template>
  <ScrollArea focusable label="Release notes" class="bg-inset h-32 w-full max-w-sm rounded-md">
    <Stack class="p-4">
      <Text v-for="i in 10" :key="i">Line {{ i }}</Text>
    </Stack>
  </ScrollArea>
</template>
