// packages/vue/src/components/empty/Empty.vue
<script setup lang="ts">
  import { Inbox } from '@lucide/vue'
  import { useSlots } from 'vue'
  import { cn } from '../../lib/cn'
  import {
    empty,
    emptyActions,
    emptyDescription,
    emptyIcon,
    emptyText,
    emptyTitle,
    type EmptyVariants,
  } from './empty.variants'

  defineOptions({ name: 'HnEmpty' })

  const props = withDefaults(
    defineProps<{
      title?: string
      description?: string
      icon?: boolean
      size?: EmptyVariants['size']
      class?: string
    }>(),
    { icon: true, size: 'md' },
  )

  const slots = useSlots()
</script>

<template>
  <div data-hn-empty :class="cn(empty({ size: props.size }), props.class)">
    <span v-if="slots.icon" aria-hidden="true" class="flex shrink-0 justify-center">
      <slot name="icon" />
    </span>
    <span v-else-if="props.icon" aria-hidden="true" :class="emptyIcon({ size: props.size })">
      <Inbox />
    </span>
    <div v-if="props.title || props.description" :class="emptyText()">
      <p v-if="props.title" :class="emptyTitle({ size: props.size })">{{ props.title }}</p>
      <p v-if="props.description" :class="emptyDescription({ size: props.size })">
        {{ props.description }}
      </p>
    </div>
    <slot />
    <div v-if="slots.actions" :class="emptyActions()">
      <slot name="actions" />
    </div>
  </div>
</template>

// packages/react/src/components/empty/Empty.tsx
import { Inbox } from 'lucide-react'
import type { HTMLAttributes, ReactNode, Ref } from 'react'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { lucide } from '../../lib/icon'
import {
  empty,
  emptyActions,
  emptyDescription,
  emptyIcon,
  emptyText,
  emptyTitle,
  type EmptyVariants,
} from './empty.variants'

const InboxIcon = lucide(Inbox)

export interface EmptyProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  title?: string
  description?: string
  icon?: ReactNode
  size?: EmptyVariants['size']
  actions?: ReactNode
  ref?: Ref<HTMLDivElement>
  [attribute: `data-${string}`]: string | undefined
}

export function Empty({
  title,
  description,
  icon = true,
  size = 'md',
  actions,
  className,
  children,
  ...attrs
}: EmptyProps) {
  const customIcon = hasContent(icon)
  return (
    <div data-hn-empty="" {...attrs} className={cn(empty({ size }), className)}>
      {customIcon ? (
        <span aria-hidden="true" className="flex shrink-0 justify-center">
          {icon}
        </span>
      ) : icon ? (
        <span aria-hidden="true" className={emptyIcon({ size })}>
          <InboxIcon />
        </span>
      ) : null}
      {title || description ? (
        <div className={emptyText()}>
          {title ? <p className={emptyTitle({ size })}>{title}</p> : null}
          {description ? <p className={emptyDescription({ size })}>{description}</p> : null}
        </div>
      ) : null}
      {children}
      {hasContent(actions) ? <div className={emptyActions()}>{actions}</div> : null}
    </div>
  )
}
