// packages/vue/src/components/prose/Prose.vue
<script setup lang="ts">
  import { Primitive, type PrimitiveProps } from 'reka-ui'
  import { cn } from '../../lib/cn'

  defineOptions({ name: 'HnProse' })

  const props = withDefaults(defineProps<PrimitiveProps & { class?: string }>(), { as: 'div' })
</script>

<template>
  <Primitive :as="props.as" :as-child="props.asChild" :class="cn('hn-prose', props.class)">
    <slot />
  </Primitive>
</template>

// packages/react/src/components/prose/Prose.tsx
import { cn } from '../../lib/cn'
import { Primitive, type PrimitiveElementProps } from '../../lib/primitive'

export type ProseProps = PrimitiveElementProps

export function Prose({ as = 'div', asChild, className, ...attrs }: ProseProps) {
  return <Primitive as={as} asChild={asChild} {...attrs} className={cn('hn-prose', className)} />
}
