// docs/react/demos/en/dialog/viewport.tsx
'use client'

import { useState } from 'react'
import { Button, Dialog, Stack, Text, type DialogHandle } from '@hina-ui/react'

export default function Demo() {
  const [modal, setModal] = useState<DialogHandle | null>(null)

  function scrollTo(position: 'start' | 'end') {
    const viewport = modal?.viewport
    if (!viewport) return
    viewport.scrollTo({ top: position === 'start' ? 0 : viewport.scrollHeight })
  }

  return (
    <Dialog
      ref={setModal}
      title="Scroll viewport"
      description="The title and footer stay fixed while the body scrolls."
      renderContent={() => (
        <Stack gap="sm">
          {Array.from({ length: 30 }, (_, i) => i + 1).map(index => (
            <Text key={index}>
              Line {index} The title and footer stay fixed while this content scrolls.
            </Text>
          ))}
        </Stack>
      )}
      renderFooter={({ close }) => (
        <>
          <Button
            variant="soft"
            tone="neutral"
            disabled={!modal?.viewport}
            onClick={() => scrollTo('start')}
          >
            Top
          </Button>
          <Button
            variant="soft"
            tone="neutral"
            disabled={!modal?.viewport}
            onClick={() => scrollTo('end')}
          >
            Bottom
          </Button>
          <Button onClick={close}>Close</Button>
        </>
      )}
    >
      <Button variant="outline" tone="neutral">
        Open
      </Button>
    </Dialog>
  )
}

// docs/app/demos/en/drawer/viewport.vue
<script setup lang="ts">
  import { ref } from 'vue'
  import { Button, Drawer, Stack, Text } from '@hina-ui/vue'

  const modal = ref<InstanceType<typeof Drawer>>()

  function scrollTo(position: 'start' | 'end') {
    const viewport = modal.value?.viewport
    if (!viewport) return
    viewport.scrollTo({ top: position === 'start' ? 0 : viewport.scrollHeight })
  }
</script>

<template>
  <Drawer
    ref="modal"
    title="Scroll viewport"
    description="The title and footer stay fixed while the body scrolls."
  >
    <Button variant="outline" tone="neutral">Open</Button>
    <template #content>
      <Stack gap="sm">
        <Text v-for="index in 30" :key="index">
          Line {{ index }} The title and footer stay fixed while this content scrolls.
        </Text>
      </Stack>
    </template>
    <template #footer="{ close }">
      <Button variant="soft" tone="neutral" :disabled="!modal?.viewport" @click="scrollTo('start')">
        Top
      </Button>
      <Button variant="soft" tone="neutral" :disabled="!modal?.viewport" @click="scrollTo('end')">
        Bottom
      </Button>
      <Button @click="close">Close</Button>
    </template>
  </Drawer>
</template>
