// docs/react/demos/zh-CN/chip/selectable.tsx
'use client'

import { useState } from 'react'
import { Chip, Inline } from '@hina-ui/react'

export default function Demo() {
  const [finished, setFinished] = useState(true)
  const [translated, setTranslated] = useState(false)

  return (
    <Inline>
      <Chip selected={finished} onSelectedChange={setFinished} selectable>
        已完结
      </Chip>
      <Chip selected={translated} onSelectedChange={setTranslated} selectable>
        有汉化
      </Chip>
    </Inline>
  )
}

// docs/app/demos/zh-CN/chip/selectable.vue
<script setup lang="ts">
  import { ref } from 'vue'
  import { Chip, Inline } from '@hina-ui/vue'

  const finished = ref(true)
  const translated = ref(false)
</script>

<template>
  <Inline>
    <Chip v-model:selected="finished" selectable>已完结</Chip>
    <Chip v-model:selected="translated" selectable>有汉化</Chip>
  </Inline>
</template>
