// packages/react/src/components/pagination/PaginationEllipsis.tsx
'use client'

import type { ReactNode } from 'react'
import clsx from 'clsx'
import { ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react'
import { hasContent } from '../../lib/content'
import { lucide } from '../../lib/icon'
import { useUiLocale } from '../../locale'
import { Button } from '../button/Button'
import { usePaginationContext } from './context'
import { paginationArrow } from './pagination.variants'
import type { PaginationRange, PaginationSide } from './types'
import type { PaginationEllipsisController } from './hooks/usePaginationEllipsis'

const MoreIcon = lucide(MoreHorizontal)
const PrevIcon = lucide(ChevronLeft)
const NextIcon = lucide(ChevronRight)

export interface PaginationEllipsisSlotProps {
  side: PaginationSide
  expanded: boolean
}

export interface PaginationEllipsisProps {
  range: PaginationRange
  controller: PaginationEllipsisController
  children?: (props: PaginationEllipsisSlotProps) => ReactNode
}

export function PaginationEllipsis({ range, controller, children }: PaginationEllipsisProps) {
  const { size, blocked, direction, siblingCount } = usePaginationContext()
  const t = useUiLocale()
  const side = range.side
  const expanded = controller.open && controller.active === side
  const step = siblingCount * 2 + 1
  const Chevron = side === 'prev' ? PrevIcon : NextIcon
  const content = children?.({ side, expanded })

  return (
    <Button
      ref={controller.register(side)}
      variant="ghost"
      tone="neutral"
      iconOnly
      size={size}
      disabled={blocked}
      data-hn-pagination-ellipsis=""
      data-type="ellipsis"
      data-side={side}
      aria-haspopup="dialog"
      aria-expanded={expanded}
      aria-controls={expanded ? controller.id : undefined}
      aria-label={
        side === 'prev' ? t.pagination.previousPagesLabel(step) : t.pagination.nextPagesLabel(step)
      }
      aria-description={t.pagination.choosePageHint}
      aria-keyshortcuts="ArrowDown ArrowUp"
      onPointerDown={event => controller.pointerdown(event)}
      onFocus={() => controller.focus(side)}
      onKeyDown={event => controller.keydown(side, event)}
      onClick={() => controller.click(side)}
    >
      {hasContent(content) ? (
        content
      ) : (
        <span className="grid" aria-hidden="true">
          <MoreIcon
            className={clsx(
              'hn-transition-base [grid-area:1/1]',
              expanded ? 'scale-90 opacity-0' : 'scale-100 opacity-100',
            )}
          />
          <Chevron
            className={clsx(
              paginationArrow({ dir: direction }),
              expanded ? 'scale-100 opacity-100' : 'scale-90 opacity-0',
              'hn-transition-base [grid-area:1/1]',
            )}
          />
        </span>
      )}
    </Button>
  )
}

// packages/vue/src/components/pagination/PaginationEllipsis.vue
<script setup lang="ts">
  import { computed, type ComponentPublicInstance } from 'vue'
  import { ChevronLeft, ChevronRight, MoreHorizontal } from '@lucide/vue'
  import Button from '../button/Button.vue'
  import { useUiLocale } from '../../locale'
  import { usePaginationContext } from './context'
  import { paginationArrow } from './pagination.variants'
  import type { PaginationRange } from './types'
  import type { PaginationEllipsisController } from './composables/usePaginationEllipsis'
  defineOptions({ name: 'HnPaginationEllipsis' })
  const props = defineProps<{ range: PaginationRange; controller: PaginationEllipsisController }>()
  const { size, blocked, direction, siblingCount } = usePaginationContext()
  const t = useUiLocale()
  const expanded = computed(
    () => props.controller.open.value && props.controller.active.value === props.range.side,
  )
  const register = (element: Element | ComponentPublicInstance | null) =>
    props.controller.register(props.range.side, element)
  const step = computed(() => siblingCount.value * 2 + 1)
</script>

<template>
  <Button
    :ref="register"
    variant="ghost"
    tone="neutral"
    icon-only
    :size="size"
    :disabled="blocked"
    data-hn-pagination-ellipsis
    data-type="ellipsis"
    :data-side="props.range.side"
    aria-haspopup="dialog"
    :aria-expanded="expanded"
    :aria-controls="expanded ? props.controller.id : undefined"
    :aria-label="
      props.range.side === 'prev'
        ? t.pagination.previousPagesLabel(step)
        : t.pagination.nextPagesLabel(step)
    "
    :aria-description="t.pagination.choosePageHint"
    aria-keyshortcuts="ArrowDown ArrowUp"
    @pointerdown="props.controller.pointerdown"
    @pointerenter="props.controller.enter(props.range.side, $event)"
    @pointerleave="props.controller.leave"
    @focus="props.controller.focus(props.range.side)"
    @keydown="props.controller.keydown(props.range.side, $event)"
    @click="props.controller.click(props.range.side)"
  >
    <slot :side="props.range.side" :expanded="expanded">
      <span class="grid" aria-hidden="true">
        <MoreHorizontal
          class="hn-transition-base [grid-area:1/1]"
          :class="expanded ? 'scale-90 opacity-0' : 'scale-100 opacity-100'"
        />
        <component
          :is="props.range.side === 'prev' ? ChevronLeft : ChevronRight"
          :class="[
            paginationArrow({ dir: direction }),
            expanded ? 'scale-100 opacity-100' : 'scale-90 opacity-0',
          ]"
          class="hn-transition-base [grid-area:1/1]"
        />
      </span>
    </slot>
  </Button>
</template>
