// docs-react/demos/en/input/form.tsx
'use client'

import { useState } from 'react'
import * as v from 'valibot'
import { Button, Form, FormField, Input, Text } from '@hina-ui/react'

const schema = v.object({
  name: v.pipe(
    v.string('Enter a nickname'),
    v.nonEmpty('Enter a nickname'),
    v.minLength(2, 'At least 2 characters'),
    v.maxLength(12, 'At most 12 characters'),
  ),
})

export default function Demo() {
  const [values, setValues] = useState({ name: '' })
  const [saved, setSaved] = useState('')

  async function save(data: unknown) {
    await new Promise(resolve => setTimeout(resolve, 600))
    setSaved(JSON.stringify(data))
  }

  return (
    <Form values={values} rules={schema} className="w-80" onSubmit={save}>
      {({ submitting }) => (
        <>
          <FormField name="name" label="Nickname" description="2 to 12 characters" required>
            <Input value={values.name} onValueChange={name => setValues({ ...values, name })} />
          </FormField>
          <Button type="submit" loading={submitting} className="self-start">
            Save
          </Button>
          {saved && (
            <Text tone="muted" size="sm">
              Saved: {saved}
            </Text>
          )}
        </>
      )}
    </Form>
  )
}

// docs/vue/app/demos/en/textarea/form.vue
<script setup lang="ts">
  import { reactive, ref } from 'vue'
  import * as v from 'valibot'
  import { Button, Form, FormField, Text, Textarea } from '@hina-ui/vue'

  const schema = v.object({
    review: v.pipe(
      v.string('Write a review'),
      v.trim(),
      v.minLength(20, 'At least 20 characters'),
      v.maxLength(500, 'At most 500 characters'),
    ),
  })

  const values = reactive({ review: '' })
  const saved = ref(false)

  async function save() {
    await new Promise(resolve => setTimeout(resolve, 600))
    saved.value = true
  }
</script>

<template>
  <Form v-slot="{ submitting }" :values="values" :rules="schema" class="w-80" @submit="save">
    <FormField name="review" label="Review" description="20 to 500 characters" required>
      <Textarea v-model="values.review" />
    </FormField>
    <Button type="submit" :loading="submitting" class="self-start">Post</Button>
    <Text v-if="saved" tone="muted" size="sm">Review posted.</Text>
  </Form>
</template>
