// docs-react/demos/zh-CN/listbox/padding.tsx
'use client'

import { useState } from 'react'
import { Card, Listbox, Stack, Switch, type ListboxValue } from '@hina-ui/react'

const options = [
  { value: 'a', label: '选项 A' },
  { label: '分组', options: [{ value: 'b', label: '选项 B' }] },
]

export default function Demo() {
  const [padded, setPadded] = useState(false)
  const [selected, setSelected] = useState<ListboxValue>('a')

  return (
    <Stack className="w-64">
      <Switch checked={padded} onCheckedChange={setPadded} controlPlacement="end" block>
        列表外围留白
      </Switch>
      <Card padded={false}>
        <Listbox
          value={selected}
          onValueChange={setSelected}
          options={options}
          variant="bare"
          padded={padded}
          aria-label="列表外围留白"
        />
      </Card>
    </Stack>
  )
}

// docs/app/demos/zh-CN/listbox/padding.vue
<script setup lang="ts">
  import { ref } from 'vue'
  import { Card, Listbox, Stack, Switch } from '@hina-ui/vue'
  const padded = ref(false)
  const selected = ref('reading')
  const options = [
    { value: 'reading', label: '在读' },
    { label: '归档', options: [{ value: 'finished', label: '已读' }] },
  ]
</script>
<template>
  <Stack class="w-64">
    <Switch v-model="padded" control-placement="end" block>列表外围留白</Switch>
    <Card :padded="false">
      <Listbox
        v-model="selected"
        :options="options"
        variant="bare"
        :padded="padded"
        aria-label="阅读状态"
      />
    </Card>
  </Stack>
</template>
