// packages/react/src/components/sidebar/Sidebar.tsx
'use client'

import type { HTMLAttributes, ReactNode, Ref, TransitionEvent } from 'react'
import { cn } from '../../lib/cn'
import { useUiLocale } from '../../locale'
import { CloseButton } from '../close-button/CloseButton'
import { ScrollArea } from '../scroll-area/ScrollArea'
import { SidebarScopeContext, useSidebar, type SidebarState } from './context'
import { SidebarLabel } from './SidebarLabel'
import {
  sidebarRoot,
  sidebarRegion,
  sidebarBrand,
  sidebarIcon,
  sidebarWordmark,
} from './sidebar.variants'

export interface SidebarSlotProps {
  state: SidebarState
}

export interface SidebarProps extends HTMLAttributes<HTMLElement> {
  label?: string
  closable?: boolean
  renderHeader?: (props: SidebarSlotProps) => ReactNode
  renderIcon?: (props: SidebarSlotProps) => ReactNode
  renderWordmark?: (props: SidebarSlotProps) => ReactNode
  renderFooter?: (props: SidebarSlotProps) => ReactNode
  ref?: Ref<HTMLElement>
  [attribute: `data-${string}`]: string | undefined
}

export function Sidebar({
  label,
  closable = true,
  renderHeader,
  renderIcon,
  renderWordmark,
  renderFooter,
  className,
  children,
  onTransitionRun,
  ...attrs
}: SidebarProps) {
  const t = useUiLocale()
  const sidebar = useSidebar()
  const state = sidebar?.state ?? 'expanded'
  const inDrawer = sidebar?.inDrawer ?? false
  const close = inDrawer && closable
  const toggle = () => sidebar?.toggle()
  const railWithoutIcon = state === 'rail' && !renderIcon

  function transitionRun(event: TransitionEvent<HTMLElement>) {
    sidebar?.onTransitionRun?.(event)
    onTransitionRun?.(event)
  }

  return (
    <SidebarScopeContext value={true}>
      <aside
        data-state={state}
        inert={state === 'hidden'}
        {...attrs}
        className={cn(sidebarRoot({ inDrawer }), className)}
        onTransitionRun={transitionRun}
      >
        {renderHeader ? (
          <div className={cn(sidebarRegion({ inDrawer }), 'flex items-center gap-2')}>
            <div className="min-w-0 flex-1">{renderHeader({ state })}</div>
            {close && <CloseButton className="shrink-0" onClick={toggle} />}
          </div>
        ) : renderIcon || renderWordmark ? (
          <div
            className="hn-collapse shrink-0"
            data-state={railWithoutIcon ? 'closed' : 'open'}
            inert={railWithoutIcon}
          >
            <div className="hn-collapse-body">
              <div className={sidebarRegion({ inDrawer })}>
                <div className={sidebarBrand()}>
                  {renderIcon && <div className={sidebarIcon()}>{renderIcon({ state })}</div>}
                  {renderWordmark && (
                    <SidebarLabel as="div" className={sidebarWordmark()}>
                      {renderWordmark({ state })}
                    </SidebarLabel>
                  )}
                  {close && <CloseButton className="ms-auto shrink-0" onClick={toggle} />}
                </div>
              </div>
            </div>
          </div>
        ) : close ? (
          <div className={cn(sidebarRegion({ inDrawer }), 'flex justify-end')}>
            <CloseButton onClick={toggle} />
          </div>
        ) : null}
        <ScrollArea shadow={false} className="min-h-0 flex-1">
          <nav
            aria-label={label ?? t.sidebar.navLabel}
            className={cn('flex flex-col gap-1', inDrawer ? 'py-2' : 'px-2.5 py-2.5')}
          >
            {children}
          </nav>
        </ScrollArea>
        {renderFooter && (
          <div className={sidebarRegion({ inDrawer, footer: true })}>{renderFooter({ state })}</div>
        )}
      </aside>
    </SidebarScopeContext>
  )
}

// packages/vue/src/components/sidebar/Sidebar.vue
<script setup lang="ts">
  import { computed } from 'vue'
  import { cn } from '../../lib/cn'
  import { useUiLocale } from '../../locale'
  import CloseButton from '../close-button/CloseButton.vue'
  import ScrollArea from '../scroll-area/ScrollArea.vue'
  import { useSidebar, type SidebarState } from './context'
  import SidebarLabel from './SidebarLabel.vue'
  import {
    sidebarRoot,
    sidebarRegion,
    sidebarBrand,
    sidebarIcon,
    sidebarWordmark,
  } from './sidebar.variants'

  defineOptions({ name: 'HnSidebar' })

  const props = withDefaults(
    defineProps<{
      label?: string
      closable?: boolean
      class?: string
    }>(),
    { closable: true },
  )

  defineSlots<{
    default?(): unknown
    header?(props: { state: SidebarState }): unknown
    icon?(props: { state: SidebarState }): unknown
    wordmark?(props: { state: SidebarState }): unknown
    footer?(props: { state: SidebarState }): unknown
  }>()

  const t = useUiLocale()
  const sidebar = useSidebar()
  const state = computed(() => sidebar?.state.value ?? 'expanded')
  const inDrawer = computed(() => sidebar?.inDrawer ?? false)
</script>

<template>
  <aside
    :data-state="state"
    :inert="state === 'hidden'"
    :class="cn(sidebarRoot({ inDrawer }), props.class)"
    @transitionrun="sidebar?.onTransitionRun"
  >
    <div v-if="$slots.header" :class="cn(sidebarRegion({ inDrawer }), 'flex items-center gap-2')">
      <div class="min-w-0 flex-1">
        <slot name="header" :state="state" />
      </div>
      <CloseButton v-if="inDrawer && props.closable" class="shrink-0" @click="sidebar?.toggle()" />
    </div>
    <div
      v-else-if="$slots.icon || $slots.wordmark"
      class="hn-collapse shrink-0"
      :data-state="state === 'rail' && !$slots.icon ? 'closed' : 'open'"
      :inert="state === 'rail' && !$slots.icon"
    >
      <div class="hn-collapse-body">
        <div :class="sidebarRegion({ inDrawer })">
          <div :class="sidebarBrand()">
            <div v-if="$slots.icon" :class="sidebarIcon()">
              <slot name="icon" :state="state" />
            </div>
            <SidebarLabel v-if="$slots.wordmark" as="div" :class="sidebarWordmark()">
              <slot name="wordmark" :state="state" />
            </SidebarLabel>
            <CloseButton
              v-if="inDrawer && props.closable"
              class="ms-auto shrink-0"
              @click="sidebar?.toggle()"
            />
          </div>
        </div>
      </div>
    </div>
    <div
      v-else-if="inDrawer && props.closable"
      :class="cn(sidebarRegion({ inDrawer }), 'flex justify-end')"
    >
      <CloseButton @click="sidebar?.toggle()" />
    </div>
    <ScrollArea :shadow="false" class="min-h-0 flex-1">
      <nav
        :aria-label="props.label ?? t.sidebar.navLabel"
        :class="cn('flex flex-col gap-1 py-2', !inDrawer && 'px-2.5')"
      >
        <slot />
      </nav>
    </ScrollArea>
    <div v-if="$slots.footer" :class="sidebarRegion({ inDrawer, footer: true })">
      <slot name="footer" :state="state" />
    </div>
  </aside>
</template>
