// docs/app/demos/zh-CN/code-block/overflow.vue
<script setup lang="ts">
  import { CodeBlock } from '@hina-ui/vue'

  const source = `const theme = { accent: 'var(--hn-accent)', radius: 'var(--hn-radius-lg)', shadow: 'var(--hn-shadow-sm)', font: 'var(--hn-font-sans)' }`
</script>

<template>
  <CodeBlock :code="source" lang="ts" class="w-full max-w-md" />
</template>

// docs/react/demos/zh-CN/code-block/overflow.tsx
import { CodeBlock } from '@hina-ui/react'

const source = `const theme = { accent: 'var(--hn-accent)', radius: 'var(--hn-radius-lg)', shadow: 'var(--hn-shadow-sm)', font: 'var(--hn-font-sans)' }`

export default function Demo() {
  return <CodeBlock code={source} lang="ts" className="w-full max-w-md" />
}
