// docs/react/demos/en/grid/cols.tsx
import { Card, Grid, Stack, Text } from '@hina-ui/react'

const counts = [2, 3, 4, 6] as const

export default function Demo() {
  return (
    <Stack className="w-full max-w-md">
      {counts.map(cols => (
        <Stack key={cols} gap="xs">
          <Text tone="muted" size="sm">
            cols {cols}
          </Text>
          <Grid cols={cols} gap="sm">
            {Array.from({ length: cols }, (_, i) => i + 1).map(i => (
              <Card
                key={i}
                className="bg-inset grid h-10 place-items-center text-sm"
                padded={false}
              >
                {i}
              </Card>
            ))}
          </Grid>
        </Stack>
      ))}
    </Stack>
  )
}

// docs/app/demos/en/grid/cols.vue
<script setup lang="ts">
  import { Card, Grid, Stack, Text } from '@hikarinagi/ui'

  const counts = [2, 3, 4, 6] as const
</script>

<template>
  <Stack class="w-full max-w-md">
    <Stack v-for="cols in counts" :key="cols" gap="xs">
      <Text tone="muted" size="sm">cols {{ cols }}</Text>
      <Grid :cols="cols" gap="sm">
        <Card
          v-for="i in cols"
          :key="i"
          class="bg-inset grid h-10 place-items-center text-sm"
          :padded="false"
        >
          {{ i }}
        </Card>
      </Grid>
    </Stack>
  </Stack>
</template>
