// packages/vue/src/components/panel/Panel.vue
<script setup lang="ts">
  import { useSlots } from 'vue'
  import { cn } from '../../lib/cn'
  import Card from '../card/Card.vue'
  import Heading from '../heading/Heading.vue'
  import Text from '../text/Text.vue'
  import { panelActions, panelBody, panelHeader, panelIcon, panelTitle } from './panel.variants'

  defineOptions({ name: 'HnPanel' })

  const props = withDefaults(
    defineProps<{
      title: string
      description?: string
      count?: number
      level?: 2 | 3 | 4
      padded?: boolean
      class?: string
    }>(),
    { level: 2, padded: true },
  )

  const slots = useSlots()
</script>

<template>
  <Card data-hn-panel :padded="false" :class="cn('flex flex-col', props.class)">
    <div :class="panelHeader({ bodiless: !slots.default })">
      <div class="flex min-w-0 flex-col gap-1">
        <div :class="panelTitle()">
          <span v-if="slots.icon" :class="panelIcon()" aria-hidden="true">
            <slot name="icon" />
          </span>
          <Heading :level="props.level" size="base" class="min-w-0">
            <slot name="title">{{ props.title }}</slot>
          </Heading>
          <Text
            v-if="props.count !== undefined"
            as="span"
            tone="muted"
            size="sm"
            class="tabular-nums"
          >
            {{ props.count }}
          </Text>
        </div>
        <Text v-if="props.description || slots.description" tone="muted" size="sm">
          <slot name="description">{{ props.description }}</slot>
        </Text>
      </div>
      <div v-if="slots.actions" :class="panelActions()">
        <slot name="actions" />
      </div>
    </div>
    <div v-if="slots.default" :class="panelBody({ padded: props.padded })">
      <slot />
    </div>
  </Card>
</template>

// packages/react/src/components/panel/Panel.tsx
import type { ReactNode } from 'react'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { Card, type CardProps } from '../card/Card'
import { Heading } from '../heading/Heading'
import { Text } from '../text/Text'
import { panelActions, panelBody, panelHeader, panelIcon, panelTitle } from './panel.variants'

export interface PanelProps extends Omit<CardProps, 'title' | 'padded'> {
  title: ReactNode
  description?: ReactNode
  count?: number
  level?: 2 | 3 | 4
  padded?: boolean
  icon?: ReactNode
  actions?: ReactNode
}

export function Panel({
  title,
  description,
  count,
  level = 2,
  padded = true,
  icon,
  actions,
  className,
  children,
  ...attrs
}: PanelProps) {
  return (
    <Card data-hn-panel="" {...attrs} padded={false} className={cn('flex flex-col', className)}>
      <div className={panelHeader({ bodiless: !hasContent(children) })}>
        <div className="flex min-w-0 flex-col gap-1">
          <div className={panelTitle()}>
            {hasContent(icon) ? (
              <span className={panelIcon()} aria-hidden="true">
                {icon}
              </span>
            ) : null}
            <Heading level={level} size="base" className="min-w-0">
              {title}
            </Heading>
            {count !== undefined ? (
              <Text as="span" tone="muted" size="sm" className="tabular-nums">
                {count}
              </Text>
            ) : null}
          </div>
          {hasContent(description) && description !== '' ? (
            <Text tone="muted" size="sm">
              {description}
            </Text>
          ) : null}
        </div>
        {hasContent(actions) ? <div className={panelActions()}>{actions}</div> : null}
      </div>
      {hasContent(children) ? <div className={panelBody({ padded })}>{children}</div> : null}
    </Card>
  )
}
