// packages/react/src/components/tooltip/TooltipBubble.tsx
import type { ReactNode } from 'react'
import { TooltipArrow, TooltipContent, TooltipPortal } from '../../primitives/tooltip'
import { cn } from '../../lib/cn'
import type { TooltipProps } from './types'

export interface TooltipBubbleProps extends TooltipProps {
  children?: ReactNode
}

export function TooltipBubble({
  content,
  side = 'top',
  align = 'center',
  sideOffset = 8,
  open,
  className,
  children,
}: TooltipBubbleProps) {
  return (
    <TooltipPortal>
      <TooltipContent
        side={side}
        align={align}
        sideOffset={sideOffset}
        aria-label={typeof content === 'string' ? content : undefined}
        updatePositionStrategy={open === undefined ? 'optimized' : 'always'}
        className={cn(
          'hn-anim-pop [--hn-pop-in:var(--hn-duration-fast)] bg-neutral-solid text-neutral-solid-on z-(--hn-z-overlay)',
          'max-w-xs rounded-md px-2.5 py-1 text-xs shadow-md',
          className,
        )}
      >
        {children ?? content}
        <TooltipArrow width={10} height={5} className="fill-neutral-solid" />
      </TooltipContent>
    </TooltipPortal>
  )
}

// packages/vue/src/components/tooltip/TooltipBubble.vue
<script setup lang="ts">
  import { TooltipPortal, TooltipContent, TooltipArrow } from 'reka-ui'
  import { cn } from '../../lib/cn'
  import type { TooltipProps } from './types'

  defineOptions({ name: 'HnTooltipBubble' })

  const props = withDefaults(defineProps<TooltipProps>(), {
    side: 'top',
    align: 'center',
    sideOffset: 8,
    open: undefined,
  })
</script>

<template>
  <TooltipPortal>
    <TooltipContent
      :side="props.side"
      :align="props.align"
      :side-offset="props.sideOffset"
      :aria-label="props.content"
      :update-position-strategy="props.open === undefined ? 'optimized' : 'always'"
      :class="
        cn(
          'hn-anim-pop [--hn-pop-in:var(--hn-duration-fast)] bg-neutral-solid text-neutral-solid-on z-(--hn-z-overlay)',
          'max-w-xs rounded-md px-2.5 py-1 text-xs shadow-md',
          props.class,
        )
      "
    >
      <slot>{{ props.content }}</slot>
      <TooltipArrow :width="10" :height="5" class="fill-neutral-solid" />
    </TooltipContent>
  </TooltipPortal>
</template>
