// packages/react/src/components/editable/Editable.tsx
'use client'

import {
  useId,
  useImperativeHandle,
  useRef,
  type ChangeEvent,
  type CompositionEvent,
  type FocusEvent,
  type KeyboardEvent,
  type MouseEvent,
  type Ref,
} from 'react'
import { Check, Pencil, X } from 'lucide-react'
import { useControllableState } from 'radix-ui/internal'
import { cn } from '../../lib/cn'
import { lucide } from '../../lib/icon'
import { useUiLocale } from '../../locale'
import { useFieldControl } from '../form-field/context'
import { IconButton } from '../icon-button/IconButton'
import { Textarea, type TextareaHandle } from '../textarea/Textarea'
import { useEditable } from './hooks/useEditable'
import {
  editable,
  editableActions,
  editableError,
  editableInput,
  editablePreview,
  editablePreviewText,
} from './editable.variants'
import type { EditableControls, EditableProps } from './types'

const CheckIcon = lucide(Check)
const PencilIcon = lucide(Pencil)
const XIcon = lucide(X)

const plain = { ripple: false } as object

export function Editable({
  activationMode = 'click',
  submitMode = 'both',
  selectOnFocus = true,
  multiline = false,
  rows = 3,
  controls = true,
  placeholder,
  name,
  required,
  maxlength,
  disabled: disabledProp,
  readonly = false,
  invalid: invalidProp,
  size,
  onSave,
  value,
  defaultValue = '',
  onValueChange,
  editing: editingProp,
  defaultEditing = false,
  onEditingChange,
  onEdit,
  onSubmit,
  onCancel,
  onError,
  renderPreview,
  renderActions,
  className,
  ref,
  ...attrs
}: EditableProps) {
  const t = useUiLocale()
  const [model, setModel] = useControllableState({
    prop: value,
    defaultProp: defaultValue,
    onChange: onValueChange,
    caller: 'Editable',
  })
  const [editing, setEditing] = useControllableState({
    prop: editingProp,
    defaultProp: defaultEditing,
    onChange: onEditingChange,
    caller: 'Editable',
  })
  const { id, labelledBy, describedBy, invalid, disabled } = useFieldControl(
    { disabled: disabledProp, invalid: invalidProp },
    attrs,
  )
  const errorId = `hn-editable-error-${useId()}`
  const singleLine = useRef<HTMLInputElement | null>(null)
  const area = useRef<TextareaHandle | null>(null)

  function nativeInput() {
    return multiline ? (area.current?.input ?? undefined) : (singleLine.current ?? undefined)
  }

  const {
    root,
    preview,
    draft,
    error,
    saving,
    blocked,
    dirty,
    edit,
    submit,
    cancel,
    focus,
    onInput,
    onFocusout,
    onKeydown,
    onCompositionStart,
    onCompositionEnd,
    state,
  } = useEditable({
    model,
    setModel,
    editing,
    setEditing,
    submitMode,
    selectOnFocus,
    multiline,
    readonly,
    onSave,
    input: nativeInput,
    disabled,
    failureMessage: t.editable.failed,
    requiredMessage: t.form.required,
    onEdit: () => onEdit?.(),
    onSubmit: (next, previous) => onSubmit?.(next, previous),
    onCancel: abandoned => onCancel?.(abandoned),
    onError: cause => onError?.(cause),
  })

  const description =
    [describedBy, error ? errorId : undefined].filter(Boolean).join(' ') || undefined
  const interactive = !readonly && activationMode !== 'manual'
  const isEditing = editing && !blocked
  const scope: EditableControls = {
    editing: isEditing,
    draft,
    dirty,
    saving,
    disabled: blocked,
    error,
    edit,
    submit: () => submit(),
    cancel,
  }
  const ariaLabel = attrs['aria-label'] || (labelledBy ? undefined : t.editable.edit)

  function activate(event: KeyboardEvent<HTMLElement>) {
    if (!interactive || (event.key !== 'Enter' && event.key !== ' ')) return
    event.preventDefault()
    edit()
  }

  useImperativeHandle(ref, () => ({
    edit,
    submit: () => submit(),
    cancel,
    focus,
    get input() {
      return nativeInput()
    },
    get draft() {
      return state.current.draft
    },
    get saving() {
      return state.current.saving
    },
    get error() {
      return state.current.error
    },
  }))

  const PreviewTag = interactive ? 'button' : 'div'
  const showActions =
    !!renderActions || (controls && (isEditing || activationMode === 'manual') && !readonly)

  const editorEvents = {
    onChange: (event: ChangeEvent<HTMLInputElement & HTMLTextAreaElement>) => onInput(event),
    onCompositionStart: (event: CompositionEvent<HTMLInputElement & HTMLTextAreaElement>) => {
      attrs.onCompositionStart?.(event)
      onCompositionStart()
    },
    onCompositionEnd: (event: CompositionEvent<HTMLInputElement & HTMLTextAreaElement>) => {
      attrs.onCompositionEnd?.(event)
      onCompositionEnd()
    },
  }

  return (
    <div
      ref={root as Ref<HTMLDivElement>}
      data-hn-editable=""
      data-state={isEditing ? 'editing' : 'preview'}
      data-saving={saving ? '' : undefined}
      aria-busy={saving || undefined}
      className={cn(editable({ size }), className)}
      onBlur={(event: FocusEvent<HTMLElement>) => onFocusout(event)}
      onKeyDown={onKeydown}
    >
      {!isEditing ? (
        <PreviewTag
          ref={preview as Ref<HTMLButtonElement & HTMLDivElement>}
          {...attrs}
          id={id}
          type={interactive ? 'button' : undefined}
          disabled={interactive ? disabled : undefined}
          tabIndex={!interactive && activationMode === 'manual' && !blocked ? 0 : undefined}
          aria-label={ariaLabel}
          aria-labelledby={labelledBy}
          aria-describedby={description}
          aria-invalid={invalid || undefined}
          data-disabled={disabled ? '' : undefined}
          data-invalid={invalid ? '' : undefined}
          className={editablePreview({ interactive })}
          onClick={(event: MouseEvent<HTMLElement>) => {
            attrs.onClick?.(event)
            if (activationMode === 'click') edit()
          }}
          onDoubleClick={(event: MouseEvent<HTMLElement>) => {
            attrs.onDoubleClick?.(event)
            if (activationMode === 'dblclick') edit()
          }}
          onKeyDown={(event: KeyboardEvent<HTMLElement>) => {
            attrs.onKeyDown?.(event)
            activate(event)
          }}
        >
          <span className={editablePreviewText({ multiline })} data-empty={!model ? '' : undefined}>
            {renderPreview
              ? renderPreview({ value: model, empty: !model })
              : model || placeholder || t.editable.placeholder}
          </span>
          {interactive && !disabled && (
            <PencilIcon aria-hidden="true" className="size-3.5 shrink-0 text-muted" />
          )}
        </PreviewTag>
      ) : multiline ? (
        <Textarea
          ref={area}
          {...attrs}
          {...editorEvents}
          value={draft}
          rows={rows}
          size={size}
          invalid={invalid || !!error}
          id={id}
          required={required}
          maxLength={maxlength}
          placeholder={placeholder ?? t.editable.placeholder}
          readOnly={saving}
          disabled={disabled}
          aria-label={ariaLabel}
          aria-labelledby={labelledBy}
          aria-describedby={description}
          aria-invalid={invalid || !!error || undefined}
          data-invalid={invalid || error ? '' : undefined}
          className="font-normal"
        />
      ) : (
        <input
          ref={singleLine}
          {...attrs}
          {...editorEvents}
          value={draft}
          type="text"
          id={id}
          required={required}
          maxLength={maxlength}
          placeholder={placeholder ?? t.editable.placeholder}
          readOnly={saving}
          disabled={disabled}
          aria-label={ariaLabel}
          aria-labelledby={labelledBy}
          aria-describedby={description}
          aria-invalid={invalid || !!error || undefined}
          data-invalid={invalid || error ? '' : undefined}
          className={editableInput()}
        />
      )}
      {name && <input type="hidden" name={name} value={model} disabled={disabled} />}
      {error && (
        <div id={errorId} role="alert" className={editableError()}>
          {error}
        </div>
      )}
      {showActions && (
        <div className={editableActions()}>
          {renderActions ? (
            renderActions(scope)
          ) : isEditing ? (
            <>
              <IconButton
                label={t.editable.save}
                size={size}
                variant="soft"
                tone="accent"
                loading={saving}
                disabled={disabled}
                {...plain}
                onClick={() => void submit()}
              >
                <CheckIcon />
              </IconButton>
              <IconButton
                label={t.common.cancel}
                size={size}
                disabled={saving || disabled}
                {...plain}
                onClick={cancel}
              >
                <XIcon />
              </IconButton>
            </>
          ) : (
            <IconButton
              label={t.editable.edit}
              size={size}
              disabled={disabled}
              {...plain}
              onClick={edit}
            >
              <PencilIcon />
            </IconButton>
          )}
        </div>
      )}
    </div>
  )
}

// packages/vue/src/components/editable/Editable.vue
<script setup lang="ts">
  import { computed, shallowRef, useId } from 'vue'
  import { Check, Pencil, X } from '@lucide/vue'
  import { cn } from '../../lib/cn'
  import { useUiLocale } from '../../locale'
  import { useFieldControl } from '../form-field/context'
  import IconButton from '../icon-button/IconButton.vue'
  import Textarea from '../textarea/Textarea.vue'
  import { useEditable } from './composables/useEditable'
  import {
    editable,
    editablePreview,
    editablePreviewText,
    editableInput,
    editableActions,
    editableError,
  } from './editable.variants'
  import type { EditableProps, EditableControls } from './types'

  defineOptions({ name: 'HnEditable', inheritAttrs: false })
  const props = withDefaults(defineProps<EditableProps>(), {
    activationMode: 'click',
    submitMode: 'both',
    selectOnFocus: true,
    controls: true,
    rows: 3,
  })
  const model = defineModel<string>({ default: '' })
  const editing = defineModel<boolean>('editing', { default: false })
  const emit = defineEmits<{
    edit: []
    submit: [value: string, previousValue: string]
    cancel: [draft: string]
    error: [error: unknown]
  }>()
  defineSlots<{
    preview?(props: { value: string; empty: boolean }): unknown
    actions?(props: EditableControls): unknown
  }>()
  const t = useUiLocale()
  const { id, labelledBy, describedBy, invalid, disabled } = useFieldControl({
    disabled: () => props.disabled,
    invalid: () => props.invalid,
  })
  const errorId = `hn-editable-error-${useId()}`
  const editor = shallowRef<HTMLInputElement | InstanceType<typeof Textarea>>()
  const nativeInput = computed(() => {
    const instance = editor.value
    return instance && 'input' in instance ? (instance.input ?? undefined) : instance
  })
  const {
    root,
    input,
    preview,
    draft,
    error,
    saving,
    blocked,
    dirty,
    edit,
    submit,
    cancel,
    focus,
    onInput,
    onFocusout,
    onKeydown,
    onCompositionStart,
    onCompositionEnd,
  } = useEditable({
    props,
    model,
    editing,
    input: nativeInput,
    disabled: () => disabled.value,
    failureMessage: () => t.value.editable.failed,
    requiredMessage: () => t.value.form.required,
    onEdit: () => emit('edit'),
    onSubmit: (value, previous) => emit('submit', value, previous),
    onCancel: value => emit('cancel', value),
    onError: error => emit('error', error),
  })
  const description = computed(
    () =>
      [describedBy.value, error.value ? errorId : undefined].filter(Boolean).join(' ') || undefined,
  )
  const editorProps = computed(() =>
    props.multiline
      ? {
          modelValue: draft.value,
          rows: props.rows,
          size: props.size,
          invalid: invalid.value || !!error.value,
        }
      : { value: draft.value, type: 'text' },
  )
  const interactive = computed(() => !props.readonly && props.activationMode !== 'manual')
  const isEditing = computed(() => editing.value && !blocked.value)
  const scope = computed<EditableControls>(() => ({
    editing: isEditing.value,
    draft: draft.value,
    dirty: dirty.value,
    saving: saving.value,
    disabled: blocked.value,
    error: error.value,
    edit,
    submit: () => submit(),
    cancel,
  }))
  function activate(event: KeyboardEvent) {
    if (!interactive.value || (event.key !== 'Enter' && event.key !== ' ')) return
    event.preventDefault()
    edit()
  }
  defineExpose({ edit, submit: () => submit(), cancel, focus, input, draft, saving, error })
</script>

<template>
  <div
    ref="root"
    data-hn-editable
    :data-state="isEditing ? 'editing' : 'preview'"
    :data-saving="saving ? '' : undefined"
    :aria-busy="saving || undefined"
    :class="cn(editable({ size: props.size }), props.class)"
    @focusout="onFocusout"
    @keydown="onKeydown"
  >
    <component
      v-if="!isEditing"
      :is="interactive ? 'button' : 'div'"
      ref="preview"
      v-bind="$attrs"
      :id="id"
      :type="interactive ? 'button' : undefined"
      :disabled="interactive ? disabled : undefined"
      :tabindex="!interactive && props.activationMode === 'manual' && !blocked ? 0 : undefined"
      :aria-label="
        ($attrs['aria-label'] as string | undefined) || (labelledBy ? undefined : t.editable.edit)
      "
      :aria-labelledby="labelledBy"
      :aria-describedby="description"
      :aria-invalid="invalid || undefined"
      :data-disabled="disabled ? '' : undefined"
      :data-invalid="invalid ? '' : undefined"
      :class="editablePreview({ interactive })"
      @click="props.activationMode === 'click' && edit()"
      @dblclick="props.activationMode === 'dblclick' && edit()"
      @keydown="activate"
    >
      <span
        :class="editablePreviewText({ multiline: props.multiline })"
        :data-empty="!model ? '' : undefined"
      >
        <slot name="preview" :value="model" :empty="!model">
          {{ model || props.placeholder || t.editable.placeholder }}
        </slot>
      </span>
      <Pencil
        v-if="interactive && !disabled"
        aria-hidden="true"
        class="size-3.5 shrink-0 text-muted"
      />
    </component>
    <component
      v-else
      :is="props.multiline ? Textarea : 'input'"
      ref="editor"
      v-bind="{ ...$attrs, ...editorProps }"
      :id="id"
      :required="props.required"
      :maxlength="props.maxlength"
      :placeholder="props.placeholder ?? t.editable.placeholder"
      :readonly="saving"
      :disabled="disabled"
      :aria-label="
        ($attrs['aria-label'] as string | undefined) || (labelledBy ? undefined : t.editable.edit)
      "
      :aria-labelledby="labelledBy"
      :aria-describedby="description"
      :aria-invalid="invalid || !!error || undefined"
      :data-invalid="invalid || error ? '' : undefined"
      :class="props.multiline ? 'font-normal' : editableInput()"
      @input="onInput"
      @compositionstart="onCompositionStart"
      @compositionend="onCompositionEnd"
    />
    <input v-if="props.name" type="hidden" :name="props.name" :value="model" :disabled="disabled" />
    <div v-if="error" :id="errorId" role="alert" :class="editableError()">{{ error }}</div>
    <div
      v-if="
        $slots.actions ||
        (props.controls && (isEditing || props.activationMode === 'manual') && !props.readonly)
      "
      :class="editableActions()"
    >
      <slot name="actions" v-bind="scope">
        <template v-if="isEditing">
          <IconButton
            :label="t.editable.save"
            :size="props.size"
            variant="soft"
            tone="accent"
            :loading="saving"
            :disabled="disabled"
            :ripple="false"
            @click="submit()"
          >
            <Check />
          </IconButton>
          <IconButton
            :label="t.common.cancel"
            :size="props.size"
            :disabled="saving || disabled"
            :ripple="false"
            @click="cancel"
          >
            <X />
          </IconButton>
        </template>
        <IconButton
          v-else
          :label="t.editable.edit"
          :size="props.size"
          :disabled="disabled"
          :ripple="false"
          @click="edit"
        >
          <Pencil />
        </IconButton>
      </slot>
    </div>
  </div>
</template>
