// packages/vue/src/components/table/Table.vue
<script setup lang="ts">
  import ScrollArea from '../scroll-area/ScrollArea.vue'
  import { cn } from '../../lib/cn'
  import { tableWrapper, type TableVariants } from './table.variants'

  defineOptions({ name: 'HnTable' })

  const props = withDefaults(
    defineProps<{
      variant?: TableVariants['variant']
      hover?: boolean
      stickyHeader?: boolean
      caption?: string
      class?: string
    }>(),
    { variant: 'primary', hover: true, stickyHeader: false },
  )
</script>

<template>
  <ScrollArea
    :direction="props.stickyHeader ? 'both' : 'horizontal'"
    :class="
      cn(
        tableWrapper({
          variant: props.variant,
          hover: props.hover,
          stickyHeader: props.stickyHeader,
        }),
        props.class,
      )
    "
  >
    <table class="hn-table">
      <caption v-if="props.caption">
        <span>{{ props.caption }}</span>
      </caption>
      <slot />
    </table>
  </ScrollArea>
</template>

// packages/react/src/components/table/Table.tsx
import type { ReactNode } from 'react'
import { cn } from '../../lib/cn'
import { ScrollArea, type ScrollAreaProps } from '../scroll-area/ScrollArea'
import { tableWrapper, type TableVariants } from './table.variants'

export interface TableProps extends Omit<ScrollAreaProps, 'direction'> {
  variant?: TableVariants['variant']
  hover?: boolean
  stickyHeader?: boolean
  caption?: string
  children?: ReactNode
}

export function Table({
  variant = 'primary',
  hover = true,
  stickyHeader = false,
  caption,
  className,
  children,
  ...attrs
}: TableProps) {
  return (
    <ScrollArea
      {...attrs}
      direction={stickyHeader ? 'both' : 'horizontal'}
      className={cn(tableWrapper({ variant, hover, stickyHeader }), className)}
    >
      <table className="hn-table">
        {caption ? (
          <caption>
            <span>{caption}</span>
          </caption>
        ) : null}
        {children}
      </table>
    </ScrollArea>
  )
}
