// packages/react/src/components/command-palette/CommandPaletteInput.tsx
'use client'

import type { InputHTMLAttributes, Ref } from 'react'
import { ListboxFilter } from '../../primitives/listbox'
import { cn } from '../../lib/cn'
import { commandInput } from './command-palette.variants'
import { useCommandPaletteContext } from './context'
import { useComposedRefs } from '../../primitives/utils/compose-refs'

export interface CommandPaletteInputProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'value' | 'defaultValue' | 'onChange' | 'autoFocus'
> {
  ref?: Ref<HTMLInputElement>
}

export function CommandPaletteInput({
  placeholder,
  className,
  ref,
  ...attrs
}: CommandPaletteInputProps) {
  const context = useCommandPaletteContext()
  const composedRef = useComposedRefs(ref, context.setInput)

  return (
    <ListboxFilter
      {...attrs}
      ref={composedRef}
      value={context.search}
      onValueChange={context.setSearch}
      autoFocus={context.autoFocus}
      placeholder={placeholder ?? context.placeholder}
      aria-label={context.label}
      className={className ? cn(commandInput(), className) : commandInput()}
    />
  )
}

// packages/vue/src/components/command-palette/CommandPaletteInput.vue
<script setup lang="ts">
  import { ListboxFilter } from 'reka-ui'
  import { shallowRef, watchEffect } from 'vue'
  import { cn } from '../../lib/cn'
  import { commandInput } from './command-palette.variants'
  import { injectCommandPalette } from './context'

  defineOptions({ name: 'HnCommandPaletteInput' })

  const props = defineProps<{
    placeholder?: string
    class?: string
  }>()

  const context = injectCommandPalette()
  const filter = shallowRef<{ $el: HTMLElement }>()

  watchEffect(() => {
    context.input.value = filter.value?.$el
  })
</script>

<template>
  <ListboxFilter
    ref="filter"
    v-model="context.search.value"
    :auto-focus="context.autoFocus.value"
    :placeholder="props.placeholder ?? context.placeholder.value"
    :aria-label="context.label.value"
    :class="props.class ? cn(commandInput(), props.class) : commandInput()"
  />
</template>
