// packages/react/src/components/command-palette/CommandPalettePanel.tsx
'use client'

import { useState, type HTMLAttributes, type ReactNode, type Ref } from 'react'
import { Search } from 'lucide-react'
import { useControllableState } from 'radix-ui/internal'
import {
  ListboxContent,
  ListboxFilter,
  ListboxGroup,
  ListboxGroupLabel,
  ListboxRoot,
} from '../../primitives/listbox'
import { cn } from '../../lib/cn'
import { lucide } from '../../lib/icon'
import { useUiLocale } from '../../locale'
import { Card } from '../card/Card'
import { ScrollArea } from '../scroll-area/ScrollArea'
import { VirtualChoices } from '../virtual-list/VirtualChoices'
import type { VirtualizeOptions } from '../../lib/virtual/types'
import { selectLabel, selectListBody } from '../select/select.variants'
import { CommandPaletteItem } from './CommandPaletteItem'
import {
  commandCard,
  commandEmpty,
  commandInput,
  commandInputRow,
  commandList,
} from './command-palette.variants'
import type { CommandItem, CommandItems } from './types'
import { useCommandItems, type CommandOption } from './hooks/useCommandItems'

const SearchIcon = lucide(Search)

export interface CommandPalettePanelProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onSelect' | 'children'
> {
  items: CommandItems
  virtualize?: VirtualizeOptions
  label: string
  placeholder?: string
  ignoreFilter?: boolean
  autoFocus?: boolean
  inline?: boolean
  search?: string
  defaultSearch?: string
  onSearchChange?: (search: string) => void
  onSelect?: (item: CommandItem) => void
  children?: ReactNode
  ref?: Ref<HTMLElement>
  [attribute: `data-${string}`]: string | undefined
}

export function CommandPalettePanel({
  items,
  virtualize,
  label,
  placeholder,
  ignoreFilter,
  autoFocus,
  inline,
  search: searchProp,
  defaultSearch = '',
  onSearchChange,
  onSelect,
  className,
  children,
  ...attrs
}: CommandPalettePanelProps) {
  const t = useUiLocale()
  const [search = '', setSearch] = useControllableState<string>({
    prop: searchProp,
    defaultProp: defaultSearch,
    onChange: onSearchChange,
    caller: 'CommandPalettePanel',
  })
  const [input, setInput] = useState<HTMLInputElement | null>(null)
  const { sections, options } = useCommandItems(items, ignoreFilter, search)

  return (
    <Card
      {...attrs}
      data-hn-command-palette=""
      padded={false}
      className={cn(commandCard({ inline }), className)}
    >
      {children}
      <ListboxRoot selectionBehavior="replace" highlightOnHover className="flex min-h-0 flex-col">
        <div className={commandInputRow()}>
          <SearchIcon aria-hidden="true" />
          <ListboxFilter
            ref={setInput}
            value={search}
            onValueChange={setSearch}
            autoFocus={autoFocus}
            placeholder={placeholder ?? t.command.placeholder}
            aria-label={label}
            className={commandInput()}
          />
        </div>
        {virtualize ? (
          <ListboxContent asChild aria-label={label}>
            <VirtualChoices<CommandOption>
              options={options}
              virtualize={virtualize}
              input={input}
              kind="listbox"
              className={commandList()}
              empty={t.command.empty}
            >
              {({ option, attrs: itemAttrs }) => (
                <CommandPaletteItem
                  {...itemAttrs}
                  match={option.match}
                  onSelect={() => onSelect?.(option.match.item)}
                />
              )}
            </VirtualChoices>
          </ListboxContent>
        ) : (
          <ScrollArea className={commandList()}>
            <ListboxContent aria-label={label} className={selectListBody()}>
              {sections.map(section =>
                section.label ? (
                  <ListboxGroup key={section.key}>
                    <ListboxGroupLabel className={selectLabel()}>{section.label}</ListboxGroupLabel>
                    {section.matches.map(match => (
                      <CommandPaletteItem
                        key={match.item.id}
                        match={match}
                        onSelect={() => onSelect?.(match.item)}
                      />
                    ))}
                  </ListboxGroup>
                ) : (
                  section.matches.map(match => (
                    <CommandPaletteItem
                      key={match.item.id}
                      match={match}
                      onSelect={() => onSelect?.(match.item)}
                    />
                  ))
                ),
              )}
              {sections.length === 0 && <div className={commandEmpty()}>{t.command.empty}</div>}
            </ListboxContent>
          </ScrollArea>
        )}
      </ListboxRoot>
    </Card>
  )
}

// packages/vue/src/components/command-palette/CommandPalettePanel.vue
<script setup lang="ts">
  import { Search } from '@lucide/vue'
  import {
    ListboxContent,
    ListboxFilter,
    ListboxGroup,
    ListboxGroupLabel,
    ListboxRoot,
  } from 'reka-ui'
  import { shallowRef } from 'vue'
  import { cn } from '../../lib/cn'
  import { useUiLocale } from '../../locale'
  import Card from '../card/Card.vue'
  import ScrollArea from '../scroll-area/ScrollArea.vue'
  import VirtualChoices from '../virtual-list/VirtualChoices.vue'
  import type { VirtualizeOptions } from '../../lib/virtual/types'
  import { selectLabel, selectListBody } from '../select/select.variants'
  import CommandPaletteItem from './CommandPaletteItem.vue'
  import {
    commandCard,
    commandEmpty,
    commandInput,
    commandInputRow,
    commandList,
  } from './command-palette.variants'
  import type { CommandItem, CommandItems } from './types'
  import { useCommandItems } from './composables/useCommandItems'

  defineOptions({ name: 'HnCommandPalettePanel', inheritAttrs: false })

  const props = defineProps<{
    items: CommandItems
    virtualize?: VirtualizeOptions
    label: string
    placeholder?: string
    ignoreFilter?: boolean
    autoFocus?: boolean
    inline?: boolean
    class?: string
  }>()

  const emit = defineEmits<{ select: [item: CommandItem] }>()

  const search = defineModel<string>('search', { default: '' })

  const t = useUiLocale()

  const input = shallowRef<{ $el: HTMLElement }>()
  const { sections, options } = useCommandItems(props, () => search.value)
</script>

<template>
  <Card
    v-bind="$attrs"
    data-hn-command-palette
    :padded="false"
    :class="cn(commandCard({ inline: props.inline }), props.class)"
  >
    <slot />
    <ListboxRoot selection-behavior="replace" highlight-on-hover class="flex min-h-0 flex-col">
      <div :class="commandInputRow()">
        <Search aria-hidden="true" />
        <ListboxFilter
          ref="input"
          v-model="search"
          :auto-focus="props.autoFocus"
          :placeholder="props.placeholder ?? t.command.placeholder"
          :aria-label="props.label"
          :class="commandInput()"
        />
      </div>
      <ListboxContent v-if="props.virtualize" as-child :aria-label="props.label">
        <VirtualChoices
          :options="options"
          :virtualize="props.virtualize"
          :input="input?.$el"
          kind="listbox"
          :class="commandList()"
        >
          <template #default="{ option, attrs }">
            <CommandPaletteItem
              v-bind="attrs"
              :match="option.match"
              @select="emit('select', option.match.item)"
            />
          </template>
          <template #empty>{{ t.command.empty }}</template>
        </VirtualChoices>
      </ListboxContent>
      <ScrollArea v-else :class="commandList()">
        <ListboxContent :aria-label="props.label" :class="selectListBody()">
          <template v-for="section in sections" :key="section.key">
            <ListboxGroup v-if="section.label">
              <ListboxGroupLabel :class="selectLabel()">{{ section.label }}</ListboxGroupLabel>
              <CommandPaletteItem
                v-for="match in section.matches"
                :key="match.item.id"
                :match="match"
                @select="emit('select', match.item)"
              />
            </ListboxGroup>
            <template v-else>
              <CommandPaletteItem
                v-for="match in section.matches"
                :key="match.item.id"
                :match="match"
                @select="emit('select', match.item)"
              />
            </template>
          </template>
          <div v-if="sections.length === 0" :class="commandEmpty()">{{ t.command.empty }}</div>
        </ListboxContent>
      </ScrollArea>
    </ListboxRoot>
  </Card>
</template>
