// packages/vue/src/components/pagination/PaginationJump.vue
<script setup lang="ts">
  import { cn } from '../../lib/cn'
  import { useUiLocale } from '../../locale'
  import Input from '../input/Input.vue'
  import { usePaginationJump } from './composables/usePaginationJump'
  defineOptions({ name: 'HnPaginationJump' })
  const props = defineProps<{ class?: string }>()
  const t = useUiLocale()
  const { draft, commit, reset, size, blocked } = usePaginationJump()
</script>

<template>
  <label
    data-hn-pagination-jump
    :class="
      cn('text-muted flex shrink-0 items-center gap-2 text-sm whitespace-nowrap', props.class)
    "
  >
    {{ t.pagination.jumpLabel }}
    <Input
      v-model="draft"
      :size="size"
      :disabled="blocked"
      inputmode="numeric"
      :aria-label="t.pagination.jumpLabel"
      class="w-16"
      @blur="commit"
      @keydown.enter.prevent.stop="commit"
      @keydown.esc.prevent.stop="reset"
    />
  </label>
</template>

// packages/react/src/components/pagination/PaginationJump.tsx
'use client'

import type { LabelHTMLAttributes } from 'react'
import { cn } from '../../lib/cn'
import { useUiLocale } from '../../locale'
import { Input } from '../input/Input'
import { usePaginationJump } from './hooks/usePaginationJump'

export interface PaginationJumpProps extends LabelHTMLAttributes<HTMLLabelElement> {
  [attribute: `data-${string}`]: string | undefined
}

export function PaginationJump({ className, ...attrs }: PaginationJumpProps) {
  const t = useUiLocale()
  const { draft, setDraft, commit, reset, size, blocked } = usePaginationJump()
  return (
    <label
      data-hn-pagination-jump=""
      className={cn(
        'text-muted flex shrink-0 items-center gap-2 text-sm whitespace-nowrap',
        className,
      )}
      {...attrs}
    >
      {t.pagination.jumpLabel}
      <Input
        value={draft}
        onValueChange={setDraft}
        size={size}
        disabled={blocked}
        inputMode="numeric"
        aria-label={t.pagination.jumpLabel}
        className="w-16"
        onBlur={commit}
        onKeyDown={event => {
          if (event.key === 'Enter') {
            event.preventDefault()
            event.stopPropagation()
            commit()
          } else if (event.key === 'Escape' || event.key === 'Esc') {
            event.preventDefault()
            event.stopPropagation()
            reset()
          }
        }}
      />
    </label>
  )
}
