// packages/vue/src/components/pagination/PaginationControl.vue
<script setup lang="ts">
  import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from '@lucide/vue'
  import {
    PaginationFirst,
    PaginationPrev,
    PaginationNext,
    PaginationLast,
  } from '../../primitives/pagination'
  import { useUiLocale } from '../../locale'
  import Button from '../button/Button.vue'
  import type { ButtonVariants } from '../button/button.variants'
  import { paginationArrow } from './pagination.variants'

  defineOptions({ name: 'HnPaginationControl' })

  const props = defineProps<{
    action: 'first' | 'prev' | 'next' | 'last'
    size?: ButtonVariants['size']
    dir: 'ltr' | 'rtl'
  }>()
  const t = useUiLocale()
  const controls = {
    first: { component: PaginationFirst, icon: ChevronsLeft },
    prev: { component: PaginationPrev, icon: ChevronLeft },
    next: { component: PaginationNext, icon: ChevronRight },
    last: { component: PaginationLast, icon: ChevronsRight },
  }
</script>

<template>
  <component :is="controls[props.action].component" as-child>
    <Button
      variant="ghost"
      tone="neutral"
      :size="props.size"
      icon-only
      :aria-label="t.pagination[props.action]"
      :data-hn-pagination-action="props.action"
    >
      <component
        :is="controls[props.action].icon"
        aria-hidden="true"
        :class="paginationArrow({ dir: props.dir })"
      />
    </Button>
  </component>
</template>

// packages/react/src/components/pagination/PaginationControl.tsx
'use client'

import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-react'
import {
  PaginationFirst,
  PaginationLast,
  PaginationNext,
  PaginationPrev,
} from '../../primitives/pagination'
import { lucide } from '../../lib/icon'
import { useUiLocale } from '../../locale'
import { Button } from '../button/Button'
import type { ButtonVariants } from '../button/button.variants'
import { paginationArrow } from './pagination.variants'

const controls = {
  first: { Component: PaginationFirst, Icon: lucide(ChevronsLeft) },
  prev: { Component: PaginationPrev, Icon: lucide(ChevronLeft) },
  next: { Component: PaginationNext, Icon: lucide(ChevronRight) },
  last: { Component: PaginationLast, Icon: lucide(ChevronsRight) },
}

export interface PaginationControlProps {
  action: 'first' | 'prev' | 'next' | 'last'
  size?: ButtonVariants['size']
  dir: 'ltr' | 'rtl'
}

export function PaginationControl({ action, size, dir }: PaginationControlProps) {
  const t = useUiLocale()
  const { Component, Icon } = controls[action]
  return (
    <Component asChild>
      <Button
        variant="ghost"
        tone="neutral"
        size={size}
        iconOnly
        aria-label={t.pagination[action]}
        data-hn-pagination-action={action}
      >
        <Icon aria-hidden="true" className={paginationArrow({ dir })} />
      </Button>
    </Component>
  )
}
