// packages/react/src/components/collapsible/Collapsible.tsx
'use client'

import { cn } from '../../lib/cn'
import { CollapsibleRoot, type CollapsibleRootProps } from '../../primitives/collapsible'

export interface CollapsibleProps extends Omit<
  CollapsibleRootProps,
  'as' | 'asChild' | 'unmountOnHide'
> {}

export function Collapsible({
  open,
  defaultOpen,
  onOpenChange,
  disabled,
  className,
  ...attrs
}: CollapsibleProps) {
  return (
    <CollapsibleRoot
      open={open}
      defaultOpen={defaultOpen}
      onOpenChange={onOpenChange}
      disabled={disabled}
      {...attrs}
      className={cn(className)}
    />
  )
}

// packages/vue/src/components/collapsible/Collapsible.vue
<script setup lang="ts">
  import { CollapsibleRoot, type CollapsibleRootEmits } from '../../primitives/collapsible'
  import { useForwardPropsEmits } from '../../primitives/utils/useForwardPropsEmits'
  import { cn } from '../../lib/cn'

  defineOptions({ name: 'HnCollapsible' })

  const props = defineProps<{
    open?: boolean
    defaultOpen?: boolean
    disabled?: boolean
    class?: string
  }>()
  const emits = defineEmits<CollapsibleRootEmits>()

  const forwarded = useForwardPropsEmits(
    () => ({ open: props.open, defaultOpen: props.defaultOpen, disabled: props.disabled }),
    emits,
  )
</script>

<template>
  <CollapsibleRoot v-bind="forwarded" :class="cn(props.class)">
    <slot />
  </CollapsibleRoot>
</template>
