// packages/vue/src/components/multi-select/MultiSelect.vue
<script setup lang="ts">
  import { computed, ref } from 'vue'
  import { SelectRoot, SelectTrigger } from 'reka-ui'
  import { cn } from '../../lib/cn'
  import { useUiLocale } from '../../locale'
  import Chip from '../chip/Chip.vue'
  import VisuallyHidden from '../visually-hidden/VisuallyHidden.vue'
  import { X } from '@lucide/vue'
  import InputAction from '../input/InputAction.vue'
  import DisclosureIcon from '../disclosure-icon/DisclosureIcon.vue'
  import { useFieldControl } from '../form-field/context'
  import { injectInputGroup } from '../input-group/context'
  import {
    inputActionSlot,
    inputAdornment,
    inputEmbedded,
    inputHost,
    type InputVariants,
  } from '../input/input.variants'
  import SelectList from '../select/SelectList.vue'
  import { flattenOptions, type SelectItems, type SelectOption } from '../select/types'
  import { multiSelectChips, multiSelectTrigger } from './multi-select.variants'

  defineOptions({ name: 'HnMultiSelect', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      options: SelectItems
      placeholder?: string
      name?: string
      required?: boolean
      autocomplete?: string
      maxVisible?: number
      clearable?: boolean
      variant?: InputVariants['variant']
      size?: InputVariants['size']
      disabled?: boolean
      invalid?: boolean
      class?: string
    }>(),
    { maxVisible: 2, clearable: false },
  )
  const emit = defineEmits<{ clear: [] }>()

  const model = defineModel<Array<string | number>>({ default: () => [] })
  const open = defineModel<boolean>('open', { default: false })

  defineSlots<{ option(props: { option: SelectOption }): unknown }>()

  const t = useUiLocale()
  const group = injectInputGroup()
  const keyboard = ref(false)

  const size = computed(() => (group ? group.size.value : props.size))
  const {
    id: fieldId,
    invalid,
    disabled,
    describedBy,
  } = useFieldControl({
    invalid: () => props.invalid || !!group?.invalid.value,
    disabled: () => props.disabled || !!group?.disabled.value,
  })
  const selected = computed(() =>
    flattenOptions(props.options).filter(option => model.value.includes(option.value)),
  )
  const formOptions = computed(() => flattenOptions(props.options))
  const visible = computed(() => selected.value.slice(0, props.maxVisible))
  const overflow = computed(() => selected.value.length - visible.value.length)
  const chipSize = computed(() => (size.value === 'sm' ? 'sm' : 'md'))
  const clearing = computed(() => props.clearable && selected.value.length > 0 && !disabled.value)

  function remove(value: string | number) {
    if (disabled.value) return
    model.value = model.value.filter(item => item !== value)
  }

  function clear() {
    if (!model.value.length) return
    model.value = []
    emit('clear')
  }

  function isolate(event: Event) {
    if ((event.target as HTMLElement).closest('button')) event.stopPropagation()
  }
</script>

<template>
  <SelectRoot
    v-model="model"
    v-model:open="open"
    :disabled="disabled"
    :required="props.required"
    multiple
  >
    <SelectTrigger
      v-bind="$attrs"
      as="div"
      :id="fieldId"
      :aria-describedby="describedBy"
      data-hn-multi-select
      @keydown="keyboard = true"
      @pointerdown="keyboard = false"
      :tabindex="disabled ? -1 : 0"
      :aria-disabled="disabled || undefined"
      :data-invalid="invalid ? '' : undefined"
      :aria-invalid="invalid || undefined"
      :class="
        cn(
          group ? inputEmbedded() : inputHost({ variant: props.variant, size: props.size }),
          multiSelectTrigger(),
          props.class,
        )
      "
    >
      <span :class="multiSelectChips()">
        <template v-if="selected.length">
          <Chip
            v-for="option in visible"
            :key="option.value"
            :size="chipSize"
            removable
            :disabled="disabled"
            class="max-w-40 min-w-0 shrink data-disabled:opacity-100"
            @pointerdown="isolate"
            @click="isolate"
            @remove="remove(option.value)"
          >
            <span class="min-w-0 truncate">{{ option.label }}</span>
          </Chip>
          <Chip
            v-if="overflow > 0"
            :size="chipSize"
            :disabled="disabled"
            class="shrink-0 data-disabled:opacity-100"
          >
            +{{ overflow }}
          </Chip>
        </template>
        <span v-else class="min-w-0 truncate">{{ props.placeholder ?? t.select.placeholder }}</span>
      </span>
      <Transition
        enter-active-class="hn-transition-base"
        enter-from-class="scale-90 opacity-0"
        leave-active-class="hn-transition"
        leave-to-class="scale-90 opacity-0"
      >
        <span v-if="clearing" data-hn-multi-select-clear :class="inputActionSlot()">
          <InputAction :label="t.common.clear" @pointerdown.stop @click.stop="clear">
            <X />
          </InputAction>
        </span>
      </Transition>
      <span :class="inputAdornment()">
        <DisclosureIcon />
      </span>
    </SelectTrigger>
    <!-- Reka 2.10 BubbleSelect assigns arrays to select.value, which loses multiple values. -->
    <VisuallyHidden v-if="props.name" as-child>
      <select
        v-model="model"
        multiple
        :name="props.name"
        :required="props.required"
        :autocomplete="props.autocomplete"
        :disabled="disabled"
        aria-hidden="true"
        tabindex="-1"
      >
        <option
          v-for="option in formOptions"
          :key="option.value"
          :value="option.value"
          :disabled="option.disabled"
        >
          {{ option.label }}
        </option>
      </select>
    </VisuallyHidden>
    <SelectList :options="props.options" :keyboard="keyboard">
      <template #option="slotProps">
        <slot name="option" v-bind="slotProps" />
      </template>
    </SelectList>
  </SelectRoot>
</template>

// packages/react/src/components/multi-select/MultiSelect.tsx
'use client'

import {
  useLayoutEffect,
  useRef,
  useState,
  type HTMLAttributes,
  type MouseEvent,
  type PointerEvent,
  type ReactNode,
  type Ref,
  type SyntheticEvent,
} from 'react'
import { X } from 'lucide-react'
import { useControllableState } from 'radix-ui/internal'
import { SelectRoot, SelectTrigger } from '../../primitives/select'
import { PrimitiveVisuallyHidden } from '../../primitives/visually-hidden'
import { cn } from '../../lib/cn'
import { lucide } from '../../lib/icon'
import { Transition } from '../../lib/transition/Transition'
import type { VirtualizeOptions } from '../../lib/virtual/types'
import { useUiLocale } from '../../locale'
import { Chip } from '../chip/Chip'
import { InputAction } from '../input/InputAction'
import { DisclosureIcon } from '../disclosure-icon/DisclosureIcon'
import { useFieldControl } from '../form-field/context'
import { useInputGroup } from '../input-group/context'
import {
  inputActionSlot,
  inputAdornment,
  inputEmbedded,
  inputHost,
  type InputVariants,
} from '../input/input.variants'
import { SelectList } from '../select/SelectList'
import { flattenOptions, type SelectItems, type SelectOption } from '../select/types'
import { multiSelectChips, multiSelectTrigger } from './multi-select.variants'

const XIcon = lucide(X)
const EMPTY: Array<string | number> = []

export interface MultiSelectProps<T extends SelectOption = SelectOption> extends Omit<
  HTMLAttributes<HTMLElement>,
  'defaultValue' | 'onChange'
> {
  options: SelectItems<T>
  virtualize?: VirtualizeOptions
  placeholder?: string
  name?: string
  required?: boolean
  autocomplete?: string
  maxVisible?: number
  clearable?: boolean
  variant?: InputVariants['variant']
  size?: InputVariants['size']
  disabled?: boolean
  invalid?: boolean
  value?: Array<string | number>
  defaultValue?: Array<string | number>
  onValueChange?: (value: Array<string | number>) => void
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  onClear?: () => void
  renderOption?: (props: { option: T }) => ReactNode
  ref?: Ref<HTMLElement>
  [attribute: `data-${string}`]: string | undefined
}

export function MultiSelect<T extends SelectOption = SelectOption>({
  options,
  virtualize,
  placeholder,
  name,
  required,
  autocomplete,
  maxVisible = 2,
  clearable = false,
  variant,
  size: sizeProp,
  disabled: disabledProp,
  invalid: invalidProp,
  value,
  defaultValue,
  onValueChange,
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  onClear,
  renderOption,
  className,
  onKeyDown,
  onPointerDown,
  ...attrs
}: MultiSelectProps<T>) {
  const t = useUiLocale()
  const group = useInputGroup()
  const [keyboard, setKeyboard] = useState(false)
  const [modelValue, setModel] = useControllableState<Array<string | number>>({
    prop: value,
    defaultProp: defaultValue ?? EMPTY,
    onChange: onValueChange,
    caller: 'MultiSelect',
  })
  const model = modelValue ?? EMPTY
  const [open, setOpen] = useControllableState<boolean>({
    prop: openProp,
    defaultProp: defaultOpen,
    onChange: onOpenChange,
    caller: 'MultiSelect',
  })

  const size = group ? group.size : sizeProp
  const {
    id: fieldId,
    invalid,
    disabled,
    describedBy,
  } = useFieldControl(
    {
      invalid: invalidProp || !!group?.invalid,
      disabled: disabledProp || !!group?.disabled,
    },
    attrs,
  )
  const flat = flattenOptions(options)
  const selected = flat.filter(option => model.includes(option.value))
  const formOptions = virtualize ? selected : flat
  const visible = selected.slice(0, maxVisible)
  const overflow = selected.length - visible.length
  const chipSize = size === 'sm' ? 'sm' : 'md'
  const clearing = clearable && selected.length > 0 && !disabled

  const nativeSelect = useRef<HTMLSelectElement>(null)
  useLayoutEffect(() => {
    const element = nativeSelect.current
    if (!element) return
    for (const option of element.options)
      option.selected = model.some(item => String(item) === option.value)
  })

  function remove(item: string | number) {
    if (disabled) return
    setModel(model.filter(entry => entry !== item))
  }

  function clear() {
    if (!model.length) return
    setModel([])
    onClear?.()
  }

  function isolate(event: SyntheticEvent) {
    if ((event.target as HTMLElement).closest('button')) event.stopPropagation()
  }

  return (
    <SelectRoot
      value={model}
      onValueChange={next => setModel(next as Array<string | number>)}
      open={open}
      onOpenChange={setOpen}
      disabled={disabled}
      required={required}
      multiple
    >
      <SelectTrigger
        {...attrs}
        as="div"
        id={fieldId}
        aria-describedby={describedBy}
        data-hn-multi-select=""
        onKeyDown={event => {
          setKeyboard(true)
          onKeyDown?.(event)
        }}
        onPointerDown={event => {
          setKeyboard(false)
          onPointerDown?.(event)
        }}
        tabIndex={disabled ? -1 : 0}
        aria-disabled={disabled || undefined}
        data-invalid={invalid ? '' : undefined}
        data-disabled={disabled ? '' : undefined}
        aria-invalid={invalid || undefined}
        className={cn(
          group ? inputEmbedded() : inputHost({ variant, size: sizeProp }),
          multiSelectTrigger(),
          className,
        )}
      >
        <span className={multiSelectChips()}>
          {selected.length ? (
            <>
              {visible.map(option => (
                <Chip
                  key={option.value}
                  size={chipSize}
                  removable
                  disabled={disabled}
                  className="max-w-40 min-w-0 shrink data-disabled:opacity-100"
                  onPointerDown={isolate}
                  onClick={isolate}
                  onRemove={() => remove(option.value)}
                >
                  <span className="min-w-0 truncate">{option.label}</span>
                </Chip>
              ))}
              {overflow > 0 && (
                <Chip
                  size={chipSize}
                  disabled={disabled}
                  className="shrink-0 data-disabled:opacity-100"
                >
                  +{overflow}
                </Chip>
              )}
            </>
          ) : (
            <span className="min-w-0 truncate">{placeholder ?? t.select.placeholder}</span>
          )}
        </span>
        <Transition
          show={clearing}
          enterActiveClass="hn-transition-base"
          enterFromClass="scale-90 opacity-0"
          leaveActiveClass="hn-transition"
          leaveToClass="scale-90 opacity-0"
        >
          <span data-hn-multi-select-clear="" className={inputActionSlot()}>
            <InputAction
              label={t.common.clear}
              onPointerDown={(event: PointerEvent<HTMLButtonElement>) => event.stopPropagation()}
              onClick={(event: MouseEvent<HTMLButtonElement>) => {
                event.stopPropagation()
                clear()
              }}
            >
              <XIcon />
            </InputAction>
          </span>
        </Transition>
        <span className={inputAdornment()}>
          <DisclosureIcon />
        </span>
      </SelectTrigger>
      {name ? (
        <PrimitiveVisuallyHidden asChild>
          <select
            ref={nativeSelect}
            multiple
            onChange={event =>
              setModel(
                Array.from(event.target.selectedOptions, option =>
                  formOptions.find(entry => String(entry.value) === option.value),
                ).flatMap(option => (option ? [option.value] : [])),
              )
            }
            name={name}
            required={required}
            autoComplete={autocomplete}
            disabled={disabled}
            aria-hidden="true"
            tabIndex={-1}
          >
            {formOptions.map(option => (
              <option key={option.value} value={option.value} disabled={option.disabled}>
                {option.label}
              </option>
            ))}
          </select>
        </PrimitiveVisuallyHidden>
      ) : null}
      <SelectList<T>
        options={options}
        keyboard={keyboard}
        virtualize={virtualize}
        renderOption={renderOption}
      />
    </SelectRoot>
  )
}
