// packages/vue/src/components/popover/Popover.vue
<script setup lang="ts">
  import type { OverlayAnchor, OverlayPositionStrategy } from '../../lib/overlay-anchor'
  import { computed } from 'vue'
  import { PopoverRoot, PopoverTrigger, PopoverPortal, type PopoverContentEmits } from 'reka-ui'
  import PopoverContent from './PopoverContent.vue'
  import { useAnchoredOverlay } from '../../lib/anchored-overlay'
  import Card from '../card/Card.vue'
  import { cn } from '../../lib/cn'

  defineOptions({ name: 'HnPopover', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      anchor?: OverlayAnchor | null
      updatePositionStrategy?: OverlayPositionStrategy
      modal?: boolean
      side?: 'top' | 'right' | 'bottom' | 'left'
      align?: 'start' | 'center' | 'end'
      sideOffset?: number
      padded?: boolean
      class?: string
    }>(),
    {
      updatePositionStrategy: 'optimized',
      side: 'bottom',
      align: 'center',
      sideOffset: 8,
      padded: true,
      modal: true,
    },
  )

  const open = defineModel<boolean>('open')
  const emit = defineEmits<PopoverContentEmits>()
  defineSlots<{ default?(): unknown; content?(): unknown }>()
  const { trigger, content, present, reference, visible, events } = useAnchoredOverlay(
    props,
    open,
    emit,
    event => emit('openAutoFocus', event),
  )

  const pressOrigin = computed(() => {
    if (props.side === 'left') return 'right'
    if (props.side === 'right') return 'left'
    if (props.align === 'start') return 'left'
    if (props.align === 'end') return 'right'
    return 'center'
  })
</script>

<template>
  <PopoverRoot v-model:open="visible" :modal="props.modal">
    <PopoverTrigger
      v-if="$slots.default"
      :ref="trigger"
      as-child
      :style="{ transformOrigin: pressOrigin }"
    >
      <slot />
    </PopoverTrigger>
    <PopoverPortal v-if="present">
      <PopoverContent
        v-bind="{ ...$attrs, ...events }"
        :reference="reference"
        :update-position-strategy="props.updatePositionStrategy"
        as-child
        :side="props.side"
        :align="props.align"
        :side-offset="props.sideOffset"
      >
        <Card
          ref="content"
          :padded="props.padded"
          :class="cn('hn-anim-pop z-(--hn-z-overlay) max-w-sm shadow-md outline-none', props.class)"
        >
          <slot name="content" />
        </Card>
      </PopoverContent>
    </PopoverPortal>
  </PopoverRoot>
</template>

// packages/react/src/components/popover/Popover.tsx
'use client'

import { Children, type HTMLAttributes, type ReactNode } from 'react'
import { useControllableState } from 'radix-ui/internal'
import { PopoverPortal, PopoverRoot, PopoverTrigger } from '../../primitives/popover'
import { PopoverContent } from './PopoverContent'
import {
  useAnchoredOverlay,
  type FocusOutsideEvent,
  type PointerDownOutsideEvent,
} from '../../lib/anchored-overlay'
import type { OverlayAnchor, OverlayPositionStrategy } from '../../lib/overlay-anchor'
import { hasContent } from '../../lib/content'
import { Card } from '../card/Card'
import { cn } from '../../lib/cn'

export interface PopoverProps extends Omit<HTMLAttributes<HTMLElement>, 'content'> {
  anchor?: OverlayAnchor | null
  updatePositionStrategy?: OverlayPositionStrategy
  modal?: boolean
  side?: 'top' | 'right' | 'bottom' | 'left'
  align?: 'start' | 'center' | 'end'
  sideOffset?: number
  padded?: boolean
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  onOpenAutoFocus?: (event: Event) => void
  onCloseAutoFocus?: (event: Event) => void
  onEscapeKeyDown?: (event: KeyboardEvent) => void
  onPointerDownOutside?: (event: PointerDownOutsideEvent) => void
  onFocusOutside?: (event: FocusOutsideEvent) => void
  onInteractOutside?: (event: PointerDownOutsideEvent | FocusOutsideEvent) => void
  content?: ReactNode
  children?: ReactNode
  [attribute: `data-${string}`]: string | undefined
}

export function Popover({
  anchor,
  updatePositionStrategy = 'optimized',
  modal = true,
  side = 'bottom',
  align = 'center',
  sideOffset = 8,
  padded = true,
  className,
  open: openProp,
  defaultOpen,
  onOpenChange,
  onOpenAutoFocus,
  onCloseAutoFocus,
  onEscapeKeyDown,
  onPointerDownOutside,
  onFocusOutside,
  onInteractOutside,
  content,
  children,
  ...attrs
}: PopoverProps) {
  const [open, setOpen] = useControllableState<boolean | undefined>({
    prop: openProp,
    defaultProp: defaultOpen,
    onChange: value => {
      if (value !== undefined) onOpenChange?.(value)
    },
    caller: 'Popover',
  })
  const { trigger, contentRef, present, reference, visible, events } = useAnchoredOverlay(
    { anchor, modal, updatePositionStrategy },
    open,
    { onCloseAutoFocus, onEscapeKeyDown, onPointerDownOutside, onFocusOutside, onInteractOutside },
    event => onOpenAutoFocus?.(event),
  )

  const pressOrigin =
    side === 'left'
      ? 'right'
      : side === 'right'
        ? 'left'
        : align === 'start'
          ? 'left'
          : align === 'end'
            ? 'right'
            : 'center'

  return (
    <PopoverRoot open={visible} onOpenChange={setOpen} modal={modal}>
      {hasContent(children) && Children.toArray(children).length > 0 && (
        <PopoverTrigger ref={trigger} asChild style={{ transformOrigin: pressOrigin }}>
          {children}
        </PopoverTrigger>
      )}
      {present && (
        <PopoverPortal>
          <PopoverContent
            {...attrs}
            {...events}
            reference={reference}
            updatePositionStrategy={updatePositionStrategy}
            asChild
            side={side}
            align={align}
            sideOffset={sideOffset}
          >
            <Card
              ref={contentRef}
              padded={padded}
              className={cn(
                'hn-anim-pop z-(--hn-z-overlay) max-w-sm shadow-md outline-none',
                className,
              )}
            >
              {content}
            </Card>
          </PopoverContent>
        </PopoverPortal>
      )}
    </PopoverRoot>
  )
}
