// packages/react/src/components/button-group/ButtonGroup.tsx
import type { HTMLAttributes, Ref } from 'react'
import { cn } from '../../lib/cn'
import { buttonGroup, type ButtonGroupVariants } from './button-group.variants'

export interface ButtonGroupProps extends HTMLAttributes<HTMLDivElement> {
  label?: string
  orientation?: ButtonGroupVariants['orientation']
  block?: boolean
  divider?: boolean
  ref?: Ref<HTMLDivElement>
  [attribute: `data-${string}`]: string | undefined
}

export function ButtonGroup({
  label,
  orientation = 'horizontal',
  block = false,
  divider = false,
  className,
  ...attrs
}: ButtonGroupProps) {
  return (
    <div
      role="group"
      aria-label={label}
      aria-orientation={orientation === 'vertical' ? 'vertical' : undefined}
      {...attrs}
      className={cn(buttonGroup({ orientation, block, divider }), className)}
    />
  )
}

// packages/vue/src/components/button-group/ButtonGroup.vue
<script setup lang="ts">
  import { cn } from '../../lib/cn'
  import { buttonGroup, type ButtonGroupVariants } from './button-group.variants'

  defineOptions({ name: 'HnButtonGroup' })

  const props = withDefaults(
    defineProps<{
      label?: string
      orientation?: ButtonGroupVariants['orientation']
      block?: boolean
      divider?: boolean
      class?: string
    }>(),
    { orientation: 'horizontal', block: false, divider: false },
  )
</script>

<template>
  <div
    role="group"
    :aria-label="props.label"
    :aria-orientation="props.orientation === 'vertical' ? 'vertical' : undefined"
    :class="
      cn(
        buttonGroup({
          orientation: props.orientation,
          block: props.block,
          divider: props.divider,
        }),
        props.class,
      )
    "
  >
    <slot />
  </div>
</template>
