// packages/react/src/components/date-field/DateField.tsx
'use client'

import {
  useImperativeHandle,
  useMemo,
  useRef,
  type HTMLAttributes,
  type ReactNode,
  type Ref,
} from 'react'
import { X } from 'lucide-react'
import { useControllableState } from 'radix-ui/internal'
import type { DateValue } from '@internationalized/date'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { lucide } from '../../lib/icon'
import { Transition } from '../../lib/transition/Transition'
import {
  formatDateValue,
  parseDateValue,
  type DateGranularity,
} from '../../../../shared/src/lib/date'
import { useUiLocale } from '../../locale'
import { DateFieldInput, DateFieldRoot } from '../../primitives/date-field'
import { useFieldControl } from '../form-field/context'
import { useInputGroup } from '../input-group/context'
import { InputAction } from '../input/InputAction'
import {
  inputActionSlot,
  inputAdornment,
  inputEmbedded,
  inputHost,
  type InputVariants,
} from '../input/input.variants'
import { useSegmentFocus } from './hooks/useSegmentFocus'
import { dateFieldControl, dateFieldHost, dateFieldSegment } from './date-field.variants'

const XIcon = lucide(X)

export interface DateFieldHandle {
  clear: () => void
  focus: () => void
}

export interface DateFieldProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'placeholder' | 'defaultValue' | 'children'
> {
  value?: string | null
  defaultValue?: string | null
  onValueChange?: (value: string | null) => void
  placeholder?: string
  min?: string
  max?: string
  granularity?: DateGranularity
  hourCycle?: 12 | 24
  clearable?: boolean
  readonly?: boolean
  name?: string
  variant?: InputVariants['variant']
  size?: InputVariants['size']
  disabled?: boolean
  invalid?: boolean
  onClear?: () => void
  leading?: ReactNode
  trailing?: ReactNode
  ref?: Ref<DateFieldHandle>
  [attribute: `data-${string}`]: string | undefined
}

export function DateField({
  value,
  defaultValue,
  onValueChange,
  placeholder: placeholderProp,
  min,
  max,
  granularity = 'day',
  hourCycle,
  clearable = false,
  readonly,
  name,
  variant,
  size,
  disabled: disabledProp,
  invalid: invalidProp,
  onClear,
  leading,
  trailing,
  className,
  ref,
  ...attrs
}: DateFieldProps) {
  const t = useUiLocale()
  const group = useInputGroup()
  const host = useRef<HTMLDivElement>(null)
  const [model = null, setModel] = useControllableState<string | null>({
    prop: value,
    defaultProp: defaultValue ?? null,
    onChange: onValueChange as ((value: string | null) => void) | undefined,
    caller: 'DateField',
  })

  const parsed = useMemo(() => parseDateValue(model, granularity), [model, granularity])
  const placeholder = useMemo(
    () => parseDateValue(placeholderProp, granularity),
    [placeholderProp, granularity],
  )
  const minValue = useMemo(() => parseDateValue(min, granularity), [min, granularity])
  const maxValue = useMemo(() => parseDateValue(max, granularity), [max, granularity])
  const outOfRange =
    !!parsed &&
    ((!!minValue && parsed.compare(minValue) < 0) || (!!maxValue && parsed.compare(maxValue) > 0))

  const { labelledBy, invalid, disabled, describedBy } = useFieldControl(
    {
      invalid: invalidProp || !!group?.invalid || outOfRange,
      disabled: disabledProp || !!group?.disabled,
    },
    attrs,
  )
  const clearing = clearable && model != null && !disabled
  const hasLeading = hasContent(leading)
  const hasTrailing = hasContent(trailing)

  function segmentLabel(part: string) {
    return (t.dateField as Record<string, string | undefined>)[part]
  }

  function update(next: DateValue | undefined) {
    setModel(next ? formatDateValue(next, granularity) : null)
  }

  const { focus, onHostClick } = useSegmentFocus(host)

  function clear() {
    if (model == null) return
    setModel(null)
    onClear?.()
    focus()
  }

  useImperativeHandle(ref, () => ({ clear, focus }))

  return (
    <div
      ref={host}
      data-hn-date-field=""
      data-invalid={invalid ? '' : undefined}
      data-disabled={disabled ? '' : undefined}
      className={cn(
        group ? inputEmbedded() : inputHost({ variant, size }),
        dateFieldHost(),
        className,
      )}
      onClick={onHostClick}
    >
      {hasLeading && <span className={inputAdornment()}>{leading}</span>}
      <DateFieldRoot
        {...attrs}
        aria-labelledby={labelledBy}
        aria-describedby={describedBy}
        value={parsed}
        placeholder={placeholder}
        minValue={minValue}
        maxValue={maxValue}
        granularity={granularity}
        hourCycle={hourCycle}
        locale={t.tag}
        disabled={disabled}
        readonly={readonly}
        name={name}
        aria-invalid={invalid || undefined}
        className={dateFieldControl({ leading: hasLeading, trailing: clearing || hasTrailing })}
        onValueChange={update}
      >
        {({ segments }) =>
          segments.map((part, index) => (
            <DateFieldInput
              key={part.part === 'literal' ? `literal-${index}` : part.part}
              part={part.part}
              data-hn-segment=""
              aria-label={part.part === 'literal' ? undefined : segmentLabel(part.part)}
              className={dateFieldSegment({
                part: part.part === 'literal' ? 'literal' : 'editable',
              })}
            >
              {part.value}
            </DateFieldInput>
          ))
        }
      </DateFieldRoot>
      <Transition
        show={clearing}
        enterActiveClass="hn-transition-base"
        enterFromClass="scale-90 opacity-0"
        leaveActiveClass="hn-transition"
        leaveToClass="scale-90 opacity-0"
      >
        <span className={inputActionSlot()}>
          <InputAction label={t.common.clear} onClick={clear}>
            <XIcon />
          </InputAction>
        </span>
      </Transition>
      {hasTrailing && <span className={inputAdornment()}>{trailing}</span>}
    </div>
  )
}

// packages/vue/src/components/date-field/DateField.vue
<script setup lang="ts">
  import { computed, shallowRef, useSlots } from 'vue'
  import { DateFieldInput, DateFieldRoot } from 'reka-ui'
  import type { DateValue } from '@internationalized/date'
  import { cn } from '../../lib/cn'
  import { formatDateValue, parseDateValue, type DateGranularity } from '../../lib/date'
  import { useUiLocale } from '../../locale'
  import { X } from '@lucide/vue'
  import InputAction from '../input/InputAction.vue'
  import { useFieldControl } from '../form-field/context'
  import { injectInputGroup } from '../input-group/context'
  import {
    inputActionSlot,
    inputAdornment,
    inputEmbedded,
    inputHost,
    type InputVariants,
  } from '../input/input.variants'
  import { useSegmentFocus } from './composables/useSegmentFocus'
  import { dateFieldControl, dateFieldHost, dateFieldSegment } from './date-field.variants'

  defineOptions({ name: 'HnDateField', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      placeholder?: string
      min?: string
      max?: string
      granularity?: DateGranularity
      hourCycle?: 12 | 24
      clearable?: boolean
      readonly?: boolean
      name?: string
      variant?: InputVariants['variant']
      size?: InputVariants['size']
      disabled?: boolean
      invalid?: boolean
      class?: string
    }>(),
    { granularity: 'day', clearable: false },
  )
  const emit = defineEmits<{ clear: [] }>()

  const model = defineModel<string | null>({ default: null })

  const slots = useSlots()
  const t = useUiLocale()
  const group = injectInputGroup()
  const host = shallowRef<HTMLElement | null>(null)

  const size = computed(() => (group ? group.size.value : props.size))
  const { labelledBy, invalid, disabled, describedBy } = useFieldControl({
    invalid: () => props.invalid || !!group?.invalid.value || outOfRange.value,
    disabled: () => props.disabled || !!group?.disabled.value,
  })

  const value = computed(() => parseDateValue(model.value, props.granularity))
  const placeholder = computed(() => parseDateValue(props.placeholder, props.granularity))
  const minValue = computed(() => parseDateValue(props.min, props.granularity))
  const maxValue = computed(() => parseDateValue(props.max, props.granularity))
  const outOfRange = computed(
    () =>
      !!value.value &&
      ((!!minValue.value && value.value.compare(minValue.value) < 0) ||
        (!!maxValue.value && value.value.compare(maxValue.value) > 0)),
  )
  const clearing = computed(() => props.clearable && model.value != null && !disabled.value)

  function segmentLabel(part: string) {
    return (t.value.dateField as Record<string, string | undefined>)[part]
  }

  function update(next: DateValue | undefined) {
    model.value = next ? formatDateValue(next, props.granularity) : null
  }

  const { focus, onHostClick } = useSegmentFocus(host)

  function clear() {
    if (model.value == null) return
    model.value = null
    emit('clear')
    focus()
  }

  defineExpose({ clear, focus })
</script>

<template>
  <div
    ref="host"
    data-hn-date-field
    :data-invalid="invalid ? '' : undefined"
    :data-disabled="disabled ? '' : undefined"
    :class="
      cn(
        group ? inputEmbedded() : inputHost({ variant: props.variant, size: props.size }),
        dateFieldHost(),
        props.class,
      )
    "
    @click="onHostClick"
  >
    <span v-if="slots.leading" :class="inputAdornment()">
      <slot name="leading" />
    </span>
    <DateFieldRoot
      v-slot="{ segments: parts }"
      v-bind="$attrs"
      :aria-labelledby="labelledBy"
      :aria-describedby="describedBy"
      :model-value="value"
      :placeholder="placeholder"
      :min-value="minValue"
      :max-value="maxValue"
      :granularity="props.granularity"
      :hour-cycle="props.hourCycle"
      :locale="t.tag"
      :disabled="disabled"
      :readonly="props.readonly"
      :name="props.name"
      :aria-invalid="invalid || undefined"
      :class="
        dateFieldControl({ leading: !!slots.leading, trailing: clearing || !!slots.trailing })
      "
      @update:model-value="update"
    >
      <DateFieldInput
        v-for="part in parts"
        :key="part.part"
        :part="part.part"
        data-hn-segment
        :aria-label="part.part === 'literal' ? undefined : segmentLabel(part.part)"
        :class="dateFieldSegment({ part: part.part === 'literal' ? 'literal' : 'editable' })"
      >
        {{ part.value }}
      </DateFieldInput>
    </DateFieldRoot>
    <Transition
      enter-active-class="hn-transition-base"
      enter-from-class="scale-90 opacity-0"
      leave-active-class="hn-transition"
      leave-to-class="scale-90 opacity-0"
    >
      <span v-if="clearing" :class="inputActionSlot()">
        <InputAction :label="t.common.clear" @click="clear">
          <X />
        </InputAction>
      </span>
    </Transition>
    <span v-if="slots.trailing" :class="inputAdornment()">
      <slot name="trailing" />
    </span>
  </div>
</template>
