// packages/react/src/components/close-button/CloseButton.tsx
'use client'

import { X } from 'lucide-react'
import { cn } from '../../lib/cn'
import { lucide } from '../../lib/icon'
import { useUiLocale } from '../../locale'
import { IconButton, type IconButtonProps } from '../icon-button/IconButton'
import type { ButtonVariants } from '../button/button.variants'

const XIcon = lucide(X)

export interface CloseButtonProps extends Omit<
  IconButtonProps,
  'label' | 'size' | 'disabled' | 'tooltip' | 'children'
> {
  label?: string
  size?: 'xs' | ButtonVariants['size']
  disabled?: boolean
  tooltip?: boolean
}

export function CloseButton({
  label,
  size = 'sm',
  disabled,
  tooltip = false,
  className,
  ...attrs
}: CloseButtonProps) {
  const t = useUiLocale()
  return (
    <IconButton
      {...attrs}
      label={label ?? t.common.close}
      tooltip={tooltip}
      size={size === 'xs' ? 'sm' : size}
      pill
      disabled={disabled}
      variant="ghost"
      tone="neutral"
      className={cn(size === 'xs' && 'size-5 [&_svg]:size-3', className)}
    >
      <XIcon />
    </IconButton>
  )
}

// packages/vue/src/components/close-button/CloseButton.vue
<script setup lang="ts">
  import { computed } from 'vue'
  import { X } from '@lucide/vue'
  import IconButton from '../icon-button/IconButton.vue'
  import { useUiLocale } from '../../locale'
  import { cn } from '../../lib/cn'
  import type { ButtonVariants } from '../button/button.variants'

  defineOptions({ name: 'HnCloseButton', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      label?: string
      size?: 'xs' | ButtonVariants['size']
      disabled?: boolean
      tooltip?: boolean
      class?: string
    }>(),
    { size: 'sm', tooltip: false },
  )

  const t = useUiLocale()

  const buttonSize = computed(() => (props.size === 'xs' ? 'sm' : props.size))
</script>

<template>
  <IconButton
    v-bind="$attrs"
    :label="props.label ?? t.common.close"
    :tooltip="props.tooltip"
    :size="buttonSize"
    pill
    :disabled="props.disabled"
    variant="ghost"
    tone="neutral"
    :class="cn(props.size === 'xs' && 'size-5 [&_svg]:size-3', props.class)"
  >
    <X />
  </IconButton>
</template>
