// packages/vue/src/components/file-upload/FileUpload.vue
<script setup lang="ts">
  import { computed, shallowRef } from 'vue'
  import { File as FileIcon, Upload, X } from '@lucide/vue'
  import { cn } from '../../lib/cn'
  import { useFieldControl } from '../form-field/context'
  import { useUiLocale } from '../../locale'
  import Button from '../button/Button.vue'
  import IconSlot from '../button/IconSlot.vue'
  import IconButton from '../icon-button/IconButton.vue'
  import Text from '../text/Text.vue'
  import { useFileDrop } from './composables/useFileDrop'
  import { useObjectUrls } from './composables/useObjectUrls'
  import {
    fileUploadArea,
    fileUploadItem,
    fileUploadList,
    fileUploadMeta,
    fileUploadRoot,
    fileUploadThumb,
  } from './file-upload.variants'
  import { selectFiles, type FileUploadRejection } from './utils/select'
  import { formatSize } from './utils/size'

  defineOptions({ name: 'HnFileUpload', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      multiple?: boolean
      accept?: string
      maxSize?: number
      maxFiles?: number
      variant?: 'area' | 'button'
      list?: boolean
      preview?: boolean
      name?: string
      loading?: boolean
      disabled?: boolean
      invalid?: boolean
      class?: string
    }>(),
    { variant: 'area', list: true, preview: true },
  )
  const emit = defineEmits<{ reject: [rejections: FileUploadRejection[]] }>()

  const model = defineModel<File | File[] | null>({ default: null })

  const t = useUiLocale()
  const input = shallowRef<HTMLInputElement | null>(null)

  const {
    field,
    id: fieldId,
    invalid,
    disabled,
    describedBy,
  } = useFieldControl({
    invalid: () => props.invalid,
    disabled: () => !!props.disabled || !!props.loading,
  })
  const files = computed<File[]>(() =>
    Array.isArray(model.value) ? model.value : model.value ? [model.value] : [],
  )

  function commit(next: File[]) {
    model.value = props.multiple ? next : (next[0] ?? null)
  }

  function take(incoming: File[]) {
    const { next, rejected } = selectFiles(files.value, incoming, {
      accept: props.accept,
      maxSize: props.maxSize,
      maxFiles: props.maxFiles,
      multiple: props.multiple,
    })
    if (rejected.length) emit('reject', rejected)
    commit(next)
  }

  function remove(file: File) {
    commit(files.value.filter(item => item !== file))
  }

  function browse() {
    if (!disabled.value) input.value?.click()
  }

  const { dragging, onDragEnter, onDragOver, onDragLeave, onDrop, onChange } = useFileDrop(
    disabled,
    take,
  )
  const { urls } = useObjectUrls(
    files,
    computed(() => props.preview),
  )
</script>

<template>
  <div data-hn-file-upload :class="cn(fileUploadRoot(), props.class)">
    <input
      ref="input"
      type="file"
      class="hidden"
      tabindex="-1"
      aria-hidden="true"
      :name="props.name"
      :accept="props.accept"
      :multiple="props.multiple"
      :disabled="disabled"
      @change="onChange"
    />
    <button
      v-if="props.variant === 'area'"
      v-bind="$attrs"
      type="button"
      data-hn-file-upload-area
      :id="fieldId"
      :aria-describedby="describedBy"
      :aria-invalid="invalid || undefined"
      :data-dragging="dragging ? '' : undefined"
      :data-invalid="invalid ? '' : undefined"
      :aria-busy="props.loading || undefined"
      :disabled="disabled"
      :class="fileUploadArea()"
      @click="browse"
      @dragenter="onDragEnter"
      @dragover="onDragOver"
      @dragleave="onDragLeave"
      @drop="onDrop"
    >
      <IconSlot
        box-class="relative inline-flex size-6 items-center justify-center [&>svg]:size-6"
        :swapped="!!props.loading"
        spinner-size="md"
      >
        <slot name="icon">
          <Upload aria-hidden="true" />
        </slot>
      </IconSlot>
      <slot>{{ t.upload.dropHint }}</slot>
    </button>
    <Button
      v-else
      v-bind="$attrs"
      :id="fieldId"
      :aria-describedby="describedBy"
      :aria-invalid="invalid || undefined"
      variant="outline"
      tone="neutral"
      :loading="props.loading"
      :disabled="props.disabled || !!field?.disabled.value"
      class="self-start"
      @click="browse"
    >
      <slot name="icon">
        <Upload />
      </slot>
      <slot>{{ t.upload.choose }}</slot>
    </Button>
    <ul v-if="props.list && files.length" :class="fileUploadList()">
      <li
        v-for="file in files"
        :key="`${file.name}-${file.size}-${file.lastModified}`"
        :class="fileUploadItem()"
      >
        <span :class="fileUploadThumb()">
          <img v-if="urls.get(file)" :src="urls.get(file)" alt="" />
          <FileIcon v-else aria-hidden="true" />
        </span>
        <span :class="fileUploadMeta()">
          <Text as="span" size="sm" truncate>{{ file.name }}</Text>
          <Text as="span" size="xs" tone="muted">{{ formatSize(t.tag, file.size) }}</Text>
        </span>
        <IconButton
          variant="ghost"
          tone="neutral"
          size="sm"
          :label="t.upload.removeFile(file.name)"
          :disabled="disabled"
          @click="remove(file)"
        >
          <X />
        </IconButton>
      </li>
    </ul>
  </div>
</template>

// packages/react/src/components/file-upload/FileUpload.tsx
'use client'

import {
  useRef,
  type ButtonHTMLAttributes,
  type DragEvent,
  type MouseEvent,
  type ReactNode,
} from 'react'
import { File as FileGlyph, Upload, X } from 'lucide-react'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { lucide } from '../../lib/icon'
import { useUiLocale } from '../../locale'
import { useFieldControl } from '../form-field/context'
import { Button } from '../button/Button'
import { IconSlot } from '../button/IconSlot'
import { IconButton } from '../icon-button/IconButton'
import { Text } from '../text/Text'
import { useFileDrop } from './hooks/useFileDrop'
import { useObjectUrls } from './hooks/useObjectUrls'
import {
  fileUploadArea,
  fileUploadItem,
  fileUploadList,
  fileUploadMeta,
  fileUploadRoot,
  fileUploadThumb,
} from './file-upload.variants'
import {
  selectFiles,
  type FileUploadRejection,
} from '../../../../shared/src/lib/file-upload/select'
import { formatSize } from '../../../../shared/src/lib/file-upload/size'
import { useControllableState } from '../../primitives/utils/controllable-state'

export type {
  FileUploadReason,
  FileUploadRejection,
} from '../../../../shared/src/lib/file-upload/select'

const UploadIcon = lucide(Upload)
const FileIcon = lucide(FileGlyph)
const XIcon = lucide(X)

type FileUploadValue = File | File[] | null

export interface FileUploadProps extends Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'value' | 'defaultValue' | 'onChange' | 'type' | 'children'
> {
  multiple?: boolean
  accept?: string
  maxSize?: number
  maxFiles?: number
  variant?: 'area' | 'button'
  list?: boolean
  preview?: boolean
  name?: string
  loading?: boolean
  disabled?: boolean
  invalid?: boolean
  value?: FileUploadValue
  defaultValue?: FileUploadValue
  onValueChange?: (value: FileUploadValue) => void
  onReject?: (rejections: FileUploadRejection[]) => void
  icon?: ReactNode
  children?: ReactNode
  [attribute: `data-${string}`]: string | undefined
}

export function FileUpload({
  multiple,
  accept,
  maxSize,
  maxFiles,
  variant = 'area',
  list = true,
  preview = true,
  name,
  loading,
  disabled: disabledProp,
  invalid: invalidProp,
  value,
  defaultValue = null,
  onValueChange,
  onReject,
  icon,
  className,
  children,
  onClick,
  onDragEnter,
  onDragOver,
  onDragLeave,
  onDrop,
  ...attrs
}: FileUploadProps) {
  const t = useUiLocale()
  const input = useRef<HTMLInputElement | null>(null)
  const [model, setModel] = useControllableState<FileUploadValue>({
    prop: value,
    defaultProp: defaultValue,
    onChange: onValueChange,
    caller: 'FileUpload',
  })

  const {
    field,
    id: fieldId,
    invalid,
    disabled,
    describedBy,
  } = useFieldControl({ invalid: invalidProp, disabled: !!disabledProp || !!loading }, attrs)
  const files: File[] = Array.isArray(model) ? model : model ? [model] : []

  function commit(next: File[]) {
    setModel(multiple ? next : (next[0] ?? null))
  }

  function take(incoming: File[]) {
    const { next, rejected } = selectFiles(files, incoming, {
      accept,
      maxSize,
      maxFiles,
      multiple,
    })
    if (rejected.length) onReject?.(rejected)
    commit(next)
  }

  function remove(file: File) {
    commit(files.filter(item => item !== file))
  }

  function browse() {
    if (!disabled) input.current?.click()
  }

  const drop = useFileDrop(disabled, take)
  const { urls } = useObjectUrls(files, preview)

  const iconContent = hasContent(icon) ? icon : null
  const label = hasContent(children) ? children : null

  function onAreaClick(event: MouseEvent<HTMLButtonElement>) {
    onClick?.(event)
    browse()
  }

  return (
    <div data-hn-file-upload="" className={cn(fileUploadRoot(), className)}>
      <input
        ref={input}
        type="file"
        className="hidden"
        tabIndex={-1}
        aria-hidden="true"
        name={name}
        accept={accept}
        multiple={multiple}
        disabled={disabled}
        onChange={drop.onChange}
      />
      {variant === 'area' ? (
        <button
          {...attrs}
          type="button"
          data-hn-file-upload-area=""
          id={fieldId}
          aria-describedby={describedBy}
          aria-invalid={invalid || undefined}
          data-dragging={drop.dragging ? '' : undefined}
          data-invalid={invalid ? '' : undefined}
          aria-busy={loading || undefined}
          disabled={disabled}
          className={fileUploadArea()}
          onClick={onAreaClick}
          onDragEnter={(event: DragEvent<HTMLButtonElement>) => {
            onDragEnter?.(event)
            drop.onDragEnter(event)
          }}
          onDragOver={(event: DragEvent<HTMLButtonElement>) => {
            onDragOver?.(event)
            drop.onDragOver(event)
          }}
          onDragLeave={(event: DragEvent<HTMLButtonElement>) => {
            onDragLeave?.(event)
            drop.onDragLeave()
          }}
          onDrop={(event: DragEvent<HTMLButtonElement>) => {
            onDrop?.(event)
            drop.onDrop(event)
          }}
        >
          <IconSlot
            boxClass="relative inline-flex size-6 items-center justify-center [&>svg]:size-6"
            swapped={!!loading}
            spinnerSize="md"
          >
            {iconContent ?? <UploadIcon aria-hidden="true" />}
          </IconSlot>
          {label ?? t.upload.dropHint}
        </button>
      ) : (
        <Button
          {...attrs}
          id={fieldId}
          aria-describedby={describedBy}
          aria-invalid={invalid || undefined}
          variant="outline"
          tone="neutral"
          loading={loading}
          disabled={!!disabledProp || !!field?.disabled}
          className="self-start"
          onClick={onAreaClick}
        >
          {iconContent ?? <UploadIcon />}
          {label ?? t.upload.choose}
        </Button>
      )}
      {list && files.length > 0 && (
        <ul className={fileUploadList()}>
          {files.map(file => (
            <li key={`${file.name}-${file.size}-${file.lastModified}`} className={fileUploadItem()}>
              <span className={fileUploadThumb()}>
                {urls.get(file) ? (
                  <img src={urls.get(file)} alt="" />
                ) : (
                  <FileIcon aria-hidden="true" />
                )}
              </span>
              <span className={fileUploadMeta()}>
                <Text as="span" size="sm" truncate>
                  {file.name}
                </Text>
                <Text as="span" size="xs" tone="muted">
                  {formatSize(t.tag, file.size)}
                </Text>
              </span>
              <IconButton
                variant="ghost"
                tone="neutral"
                size="sm"
                label={t.upload.removeFile(file.name)}
                disabled={disabled}
                onClick={() => remove(file)}
              >
                <XIcon />
              </IconButton>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
