// packages/vue/src/components/password-input/PasswordInput.vue
<script setup lang="ts">
  import { Eye, EyeOff } from '@lucide/vue'
  import { cn } from '../../lib/cn'
  import { useUiLocale } from '../../locale'
  import InputBase from '../input/InputBase.vue'
  import InputAction from '../input/InputAction.vue'
  import type { InputVariants } from '../input/input.variants'

  defineOptions({ name: 'HnPasswordInput', inheritAttrs: false })

  const props = defineProps<{
    variant?: InputVariants['variant']
    size?: InputVariants['size']
    disabled?: boolean
    invalid?: boolean
    class?: string
  }>()

  const model = defineModel<string>()
  const visible = defineModel<boolean>('visible', { default: false })

  const t = useUiLocale()
</script>

<template>
  <InputBase
    v-bind="$attrs"
    v-model="model"
    :type="visible ? 'text' : 'password'"
    :variant="props.variant"
    :size="props.size"
    :disabled="props.disabled"
    :invalid="props.invalid"
    :class="cn('[&_input::-ms-reveal]:hidden', props.class)"
  >
    <template #action>
      <InputAction
        :label="visible ? t.passwordInput.hide : t.passwordInput.show"
        :disabled="props.disabled"
        @click="visible = !visible"
      >
        <span class="relative inline-flex">
          <Transition
            enter-active-class="hn-transition-base"
            enter-from-class="scale-90 opacity-0"
            leave-active-class="hn-transition absolute"
            leave-to-class="scale-90 opacity-0"
          >
            <EyeOff v-if="visible" key="hide" />
            <Eye v-else key="show" />
          </Transition>
        </span>
      </InputAction>
    </template>
  </InputBase>
</template>

// packages/react/src/components/password-input/PasswordInput.tsx
'use client'

import { Eye, EyeOff } from 'lucide-react'
import { useControllableState } from 'radix-ui/internal'
import { cn } from '../../lib/cn'
import { lucide } from '../../lib/icon'
import { Transition } from '../../lib/transition/Transition'
import { useUiLocale } from '../../locale'
import { InputBase, type InputBaseProps } from '../input/InputBase'
import { InputAction } from '../input/InputAction'

const EyeIcon = lucide(Eye)
const EyeOffIcon = lucide(EyeOff)

export interface PasswordInputProps extends Omit<
  InputBaseProps,
  'clearable' | 'loading' | 'onClear' | 'leading' | 'trailing' | 'action'
> {
  visible?: boolean
  defaultVisible?: boolean
  onVisibleChange?: (visible: boolean) => void
}

export function PasswordInput({
  visible: visibleProp,
  defaultVisible = false,
  onVisibleChange,
  disabled,
  className,
  ...props
}: PasswordInputProps) {
  const t = useUiLocale()
  const [visible, setVisible] = useControllableState({
    prop: visibleProp,
    defaultProp: defaultVisible,
    onChange: onVisibleChange,
    caller: 'PasswordInput',
  })

  return (
    <InputBase
      {...props}
      type={visible ? 'text' : 'password'}
      disabled={disabled}
      className={cn('[&_input::-ms-reveal]:hidden', className)}
      action={
        <InputAction
          label={visible ? t.passwordInput.hide : t.passwordInput.show}
          disabled={disabled}
          onClick={() => setVisible(!visible)}
        >
          <span className="relative inline-flex">
            <Transition
              show={visible}
              enterActiveClass="hn-transition-base"
              enterFromClass="scale-90 opacity-0"
              leaveActiveClass="hn-transition absolute"
              leaveToClass="scale-90 opacity-0"
            >
              <EyeOffIcon />
            </Transition>
            <Transition
              show={!visible}
              enterActiveClass="hn-transition-base"
              enterFromClass="scale-90 opacity-0"
              leaveActiveClass="hn-transition absolute"
              leaveToClass="scale-90 opacity-0"
            >
              <EyeIcon />
            </Transition>
          </span>
        </InputAction>
      }
    />
  )
}
