// packages/vue/src/components/flex/Flex.vue
<script setup lang="ts">
  import type { Component } from 'vue'
  import { cn } from '../../lib/cn'
  import { flex, type FlexVariants } from './flex.variants'

  defineOptions({ name: 'HnFlex' })

  const props = withDefaults(
    defineProps<{
      as?: string | Component
      direction?: FlexVariants['direction']
      gap?: FlexVariants['gap']
      align?: FlexVariants['align']
      justify?: FlexVariants['justify']
      wrap?: boolean
      class?: string
    }>(),
    { as: 'div' },
  )
</script>

<template>
  <component
    :is="props.as"
    :class="cn(flex({ direction, gap, align, justify, wrap }), props.class)"
  >
    <slot />
  </component>
</template>

// packages/react/src/components/flex/Flex.tsx
import type { ElementType, HTMLAttributes, Ref } from 'react'
import { cn } from '../../lib/cn'
import { flex, type FlexVariants } from './flex.variants'
import type { AnchorAttributes } from '../../lib/primitive'

export interface FlexProps extends HTMLAttributes<HTMLElement>, AnchorAttributes {
  as?: ElementType
  direction?: FlexVariants['direction']
  gap?: FlexVariants['gap']
  align?: FlexVariants['align']
  justify?: FlexVariants['justify']
  wrap?: boolean
  ref?: Ref<HTMLElement>
}

export function Flex({
  as: Tag = 'div',
  direction,
  gap,
  align,
  justify,
  wrap,
  className,
  ...props
}: FlexProps) {
  return (
    <Tag {...props} className={cn(flex({ direction, gap, align, justify, wrap }), className)} />
  )
}
