// packages/react/src/components/ring-progress/RingProgress.tsx
'use client'

import type { HTMLAttributes, ReactNode, Ref } from 'react'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { useProgressValue, type ProgressFormat } from '../progress/hooks/useProgressValue'
import {
  ringProgress,
  ringProgressArc,
  ringProgressCenter,
  ringProgressLabel,
  ringProgressRoot,
  ringProgressSvg,
  ringProgressTrack,
  type RingProgressVariants,
} from './ring-progress.variants'
import { ProgressRoot } from '../../primitives/progress'

export interface RingProgressProps extends HTMLAttributes<HTMLDivElement> {
  value?: number | null
  max?: number
  label?: string
  showValue?: boolean
  format?: ProgressFormat
  tone?: RingProgressVariants['tone']
  size?: RingProgressVariants['size']
  children?: ReactNode
  ref?: Ref<HTMLDivElement>
  [attribute: `data-${string}`]: string | undefined
}

export function RingProgress({
  value = null,
  max = 100,
  label,
  showValue = false,
  format,
  tone,
  size,
  className,
  children,
  ...attrs
}: RingProgressProps) {
  const { current, text, name } = useProgressValue({ value, max, label, format })
  const offset = current === null ? 75 : max > 0 ? 100 - (current * 100) / max : 100

  return (
    <div data-hn-ring-progress="" className={cn(ringProgress(), className)}>
      <ProgressRoot
        aria-label={name}
        aria-valuetext={format ? text : undefined}
        {...attrs}
        value={current}
        max={max}
        className={ringProgressRoot({ size })}
      >
        <svg viewBox="0 0 100 100" aria-hidden="true" className={ringProgressSvg()}>
          <circle cx="50" cy="50" r="45" strokeWidth="10" className={ringProgressTrack()} />
          <circle
            cx="50"
            cy="50"
            r="45"
            strokeWidth="10"
            pathLength={100}
            strokeDasharray="100"
            strokeDashoffset={offset}
            strokeLinecap={offset < 100 ? 'round' : undefined}
            className={ringProgressArc({ tone })}
          />
        </svg>
        {hasContent(children) || (showValue && text) ? (
          <div className={ringProgressCenter()}>{hasContent(children) ? children : text}</div>
        ) : null}
      </ProgressRoot>
      {label ? <span className={ringProgressLabel()}>{label}</span> : null}
    </div>
  )
}

// packages/vue/src/components/ring-progress/RingProgress.vue
<script setup lang="ts">
  import { ProgressRoot } from '../../primitives/progress'
  import { computed, useSlots } from 'vue'
  import { cn } from '../../lib/cn'
  import { useProgressValue, type ProgressFormat } from '../progress/composables/useProgressValue'
  import {
    ringProgress,
    ringProgressArc,
    ringProgressCenter,
    ringProgressLabel,
    ringProgressRoot,
    ringProgressSvg,
    ringProgressTrack,
    type RingProgressVariants,
  } from './ring-progress.variants'

  defineOptions({ name: 'HnRingProgress', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      value?: number | null
      max?: number
      label?: string
      showValue?: boolean
      format?: ProgressFormat
      tone?: RingProgressVariants['tone']
      size?: RingProgressVariants['size']
      class?: string
    }>(),
    { value: null, max: 100, showValue: false },
  )

  const slots = useSlots()
  const { current, text, name } = useProgressValue({
    value: () => props.value,
    max: () => props.max,
    label: () => props.label,
    format: () => props.format,
  })
  const offset = computed(() => {
    if (current.value === null) return 75
    return props.max > 0 ? 100 - (current.value * 100) / props.max : 100
  })
</script>

<template>
  <div data-hn-ring-progress :class="cn(ringProgress(), props.class)">
    <ProgressRoot
      v-bind="$attrs"
      :model-value="current"
      :max="props.max"
      :get-value-label="() => name"
      :get-value-text="props.format ? () => text : undefined"
      :class="ringProgressRoot({ size: props.size })"
    >
      <svg viewBox="0 0 100 100" aria-hidden="true" :class="ringProgressSvg()">
        <circle cx="50" cy="50" r="45" stroke-width="10" :class="ringProgressTrack()" />
        <circle
          cx="50"
          cy="50"
          r="45"
          stroke-width="10"
          pathLength="100"
          stroke-dasharray="100"
          :stroke-dashoffset="offset"
          :stroke-linecap="offset < 100 ? 'round' : undefined"
          :class="ringProgressArc({ tone: props.tone })"
        />
      </svg>
      <div v-if="slots.default || (props.showValue && text)" :class="ringProgressCenter()">
        <slot>{{ text }}</slot>
      </div>
    </ProgressRoot>
    <span v-if="props.label" :class="ringProgressLabel()">{{ props.label }}</span>
  </div>
</template>
