// packages/vue/src/components/data-list/DataListItem.vue
<script setup lang="ts">
  import Skeleton from '../skeleton/Skeleton.vue'
  import {
    dataListAnatomy,
    dataListMedia,
    dataListDetails,
    dataListCopy,
    dataListTitle,
    dataListDescription,
    dataListMeta,
    dataListActions,
    dataListPlaceholder,
  } from './data-list.variants'
  import type { DataListLayout } from './types'
  defineProps<{
    layout: DataListLayout
    title?: string | number
    description?: string | number
    mediaRatio?: number
    placeholder?: boolean
    titlePlaceholder?: boolean
    descriptionPlaceholder?: boolean
    media?: boolean
    meta?: boolean
    actions?: boolean
  }>()
  const slots = defineSlots<{
    media?(): unknown
    title?(): unknown
    description?(): unknown
    meta?(): unknown
    actions?(): unknown
  }>()
</script>
<template>
  <div :class="dataListAnatomy({ layout })">
    <div
      v-if="media || slots.media"
      :class="dataListMedia({ layout })"
      :style="mediaRatio ? { aspectRatio: mediaRatio } : undefined"
    >
      <Skeleton v-if="placeholder" :class="dataListPlaceholder({ part: 'media' })" />
      <slot v-else name="media" />
    </div>
    <div :class="dataListDetails({ layout })">
      <div :class="dataListCopy()">
        <div v-if="titlePlaceholder || slots.title || title !== undefined" :class="dataListTitle()">
          <Skeleton v-if="placeholder" :class="dataListPlaceholder({ part: 'title' })" />
          <slot v-else name="title">{{ title }}</slot>
        </div>
        <div
          v-if="descriptionPlaceholder || slots.description || description !== undefined"
          :class="dataListDescription()"
        >
          <Skeleton v-if="placeholder" :class="dataListPlaceholder({ part: 'description' })" />
          <slot v-else name="description">{{ description }}</slot>
        </div>
        <div v-if="meta || slots.meta" :class="dataListMeta()">
          <Skeleton v-if="placeholder" :class="dataListPlaceholder({ part: 'meta' })" />
          <slot v-else name="meta" />
        </div>
      </div>
      <div v-if="actions || slots.actions" :class="dataListActions({ layout })">
        <Skeleton v-if="placeholder" :class="dataListPlaceholder({ part: 'action' })" />
        <slot v-else name="actions" />
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/data-list/DataListItem.tsx
import type { ReactNode } from 'react'
import { Skeleton } from '../skeleton/Skeleton'
import {
  dataListAnatomy,
  dataListMedia,
  dataListDetails,
  dataListCopy,
  dataListTitle,
  dataListDescription,
  dataListMeta,
  dataListActions,
  dataListPlaceholder,
} from './data-list.variants'
import type { DataListLayout } from './types'

export interface DataListItemProps {
  layout: DataListLayout
  title?: string | number
  description?: string | number
  mediaRatio?: number
  placeholder?: boolean
  titlePlaceholder?: boolean
  descriptionPlaceholder?: boolean
  media?: boolean
  meta?: boolean
  actions?: boolean
  renderMedia?: () => ReactNode
  renderTitle?: () => ReactNode
  renderDescription?: () => ReactNode
  renderMeta?: () => ReactNode
  renderActions?: () => ReactNode
}

export function DataListItem({
  layout,
  title,
  description,
  mediaRatio,
  placeholder,
  titlePlaceholder,
  descriptionPlaceholder,
  media,
  meta,
  actions,
  renderMedia,
  renderTitle,
  renderDescription,
  renderMeta,
  renderActions,
}: DataListItemProps) {
  return (
    <div className={dataListAnatomy({ layout })}>
      {(media || renderMedia) && (
        <div
          className={dataListMedia({ layout })}
          style={mediaRatio ? { aspectRatio: mediaRatio } : undefined}
        >
          {placeholder ? (
            <Skeleton className={dataListPlaceholder({ part: 'media' })} />
          ) : (
            renderMedia?.()
          )}
        </div>
      )}
      <div className={dataListDetails({ layout })}>
        <div className={dataListCopy()}>
          {(titlePlaceholder || renderTitle || title !== undefined) && (
            <div className={dataListTitle()}>
              {placeholder ? (
                <Skeleton className={dataListPlaceholder({ part: 'title' })} />
              ) : renderTitle ? (
                renderTitle()
              ) : (
                title
              )}
            </div>
          )}
          {(descriptionPlaceholder || renderDescription || description !== undefined) && (
            <div className={dataListDescription()}>
              {placeholder ? (
                <Skeleton className={dataListPlaceholder({ part: 'description' })} />
              ) : renderDescription ? (
                renderDescription()
              ) : (
                description
              )}
            </div>
          )}
          {(meta || renderMeta) && (
            <div className={dataListMeta()}>
              {placeholder ? (
                <Skeleton className={dataListPlaceholder({ part: 'meta' })} />
              ) : (
                renderMeta?.()
              )}
            </div>
          )}
        </div>
        {(actions || renderActions) && (
          <div className={dataListActions({ layout })}>
            {placeholder ? (
              <Skeleton className={dataListPlaceholder({ part: 'action' })} />
            ) : (
              renderActions?.()
            )}
          </div>
        )}
      </div>
    </div>
  )
}
