// packages/vue/src/components/input/InputBase.vue
<script setup lang="ts">
  import { computed, shallowRef, useSlots } from 'vue'
  import { cn } from '../../lib/cn'
  import { focusFieldFrom } from '../../lib/field-focus'
  import { useUiLocale } from '../../locale'
  import { X } from '@lucide/vue'
  import IconSlot from '../button/IconSlot.vue'
  import InputAction from './InputAction.vue'
  import Spinner from '../spinner/Spinner.vue'
  import { useFieldControl } from '../form-field/context'
  import { injectInputGroup } from '../input-group/context'
  import {
    inputActionSlot,
    inputAdornment,
    inputControl,
    inputEmbedded,
    textInputHost,
    type TextInputVariants,
  } from './input.variants'

  defineOptions({ name: 'HnInputBase', inheritAttrs: false })

  const props = defineProps<{
    variant?: TextInputVariants['variant']
    size?: TextInputVariants['size']
    clearable?: boolean
    loading?: boolean
    disabled?: boolean
    invalid?: boolean
    class?: string
  }>()
  const emit = defineEmits<{ clear: [] }>()

  const model = defineModel<string>()

  const slots = useSlots()
  const t = useUiLocale()
  const group = injectInputGroup()
  const el = shallowRef<HTMLInputElement | null>(null)

  const size = computed(() => (group ? group.size.value : props.size))
  const {
    id: fieldId,
    invalid,
    disabled,
    describedBy,
  } = useFieldControl({
    invalid: () => props.invalid || !!group?.invalid.value,
    disabled: () => props.disabled || !!group?.disabled.value,
  })
  const clearing = computed(() => !!props.clearable && !!model.value && !disabled.value)
  const trailingSpinner = computed(() => !!props.loading && !slots.leading)
  const spinnerSize = computed(() => (size.value === 'lg' ? 'md' : 'sm'))

  function clear() {
    if (!model.value) return
    model.value = ''
    emit('clear')
    el.value?.focus()
  }

  defineExpose({ clear, focus: () => el.value?.focus() })
</script>

<template>
  <div
    data-hn-input
    :data-invalid="invalid ? '' : undefined"
    :data-disabled="disabled ? '' : undefined"
    :aria-busy="props.loading || undefined"
    :class="
      cn(
        group ? inputEmbedded() : textInputHost({ variant: props.variant, size: props.size }),
        props.class,
      )
    "
    @click="focusFieldFrom($event.currentTarget as HTMLElement, $event.target as HTMLElement)"
  >
    <span v-if="slots.leading" :class="inputAdornment()">
      <IconSlot
        box-class="relative inline-flex items-center justify-center"
        :swapped="!!props.loading"
        :spinner-size="spinnerSize"
      >
        <slot name="leading" />
      </IconSlot>
    </span>
    <input
      ref="el"
      v-bind="$attrs"
      v-model="model"
      :id="fieldId"
      :disabled="disabled"
      :aria-invalid="invalid || undefined"
      :aria-describedby="describedBy"
      :class="
        inputControl({
          leading: !!slots.leading,
          trailing: clearing || trailingSpinner || !!slots.trailing,
        })
      "
    />
    <Transition
      enter-active-class="hn-transition-base"
      enter-from-class="scale-90 opacity-0"
      leave-active-class="hn-transition"
      leave-to-class="scale-90 opacity-0"
    >
      <span v-if="trailingSpinner" :class="inputAdornment()">
        <Spinner :size="spinnerSize" />
      </span>
    </Transition>
    <Transition
      enter-active-class="hn-transition-base"
      enter-from-class="scale-90 opacity-0"
      leave-active-class="hn-transition"
      leave-to-class="scale-90 opacity-0"
    >
      <span v-if="clearing" :class="inputActionSlot()">
        <InputAction :label="t.common.clear" @click="clear">
          <X />
        </InputAction>
      </span>
    </Transition>
    <slot name="action" />
    <span v-if="slots.trailing" :class="inputAdornment()">
      <slot name="trailing" />
    </span>
  </div>
</template>

// packages/react/src/components/input/InputBase.tsx
'use client'

import {
  useImperativeHandle,
  type InputHTMLAttributes,
  type MouseEvent,
  type ReactNode,
  type Ref,
} from 'react'
import { X } from 'lucide-react'
import { useControllableState } from 'radix-ui/internal'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { lucide } from '../../lib/icon'
import { Transition } from '../../lib/transition/Transition'
import { focusFieldFrom } from '../../../../shared/src/lib/field-focus'
import { useUiLocale } from '../../locale'
import { IconSlot } from '../button/IconSlot'
import { Spinner } from '../spinner/Spinner'
import { useFieldControl } from '../form-field/context'
import { useInputGroup } from '../input-group/context'
import { InputAction } from './InputAction'
import { useModelText } from './hooks/useModelText'
import {
  inputActionSlot,
  inputAdornment,
  inputControl,
  inputEmbedded,
  textInputHost,
  type TextInputVariants,
} from './input.variants'

const XIcon = lucide(X)

export interface InputHandle {
  clear: () => void
  focus: () => void
}

export interface InputBaseProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'size' | 'value' | 'defaultValue' | 'disabled'
> {
  variant?: TextInputVariants['variant']
  size?: TextInputVariants['size']
  clearable?: boolean
  loading?: boolean
  disabled?: boolean
  invalid?: boolean
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
  onClear?: () => void
  leading?: ReactNode
  trailing?: ReactNode
  action?: ReactNode
  ref?: Ref<InputHandle>
  [attribute: `data-${string}`]: string | undefined
}

export function InputBase({
  variant,
  size: sizeProp,
  clearable,
  loading,
  disabled: disabledProp,
  invalid: invalidProp,
  value,
  defaultValue,
  onValueChange,
  onClear,
  leading,
  trailing,
  action,
  className,
  onChange,
  onCompositionStart,
  onCompositionEnd,
  ref,
  ...attrs
}: InputBaseProps) {
  const t = useUiLocale()
  const group = useInputGroup()
  const [model, setModel] = useControllableState<string | undefined>({
    prop: value,
    defaultProp: defaultValue,
    onChange: onValueChange as ((value: string | undefined) => void) | undefined,
    caller: 'Input',
  })
  const { element, bindings } = useModelText<HTMLInputElement>(model, next => setModel(next), {
    onChange,
    onCompositionStart,
    onCompositionEnd,
  })

  const size = group ? group.size : sizeProp
  const {
    id: fieldId,
    invalid,
    disabled,
    describedBy,
  } = useFieldControl(
    {
      invalid: invalidProp || !!group?.invalid,
      disabled: disabledProp || !!group?.disabled,
    },
    attrs,
  )
  const hasLeading = hasContent(leading)
  const hasTrailing = hasContent(trailing)
  const clearing = !!clearable && !!model && !disabled
  const trailingSpinner = !!loading && !hasLeading
  const spinnerSize = size === 'lg' ? 'md' : 'sm'

  function clear() {
    if (!model) return
    setModel('')
    onClear?.()
    element.current?.focus()
  }

  useImperativeHandle(ref, () => ({ clear, focus: () => element.current?.focus() }))

  function onRootClick(event: MouseEvent<HTMLDivElement>) {
    focusFieldFrom(event.currentTarget, event.target as HTMLElement)
  }

  return (
    <div
      data-hn-input=""
      data-invalid={invalid ? '' : undefined}
      data-disabled={disabled ? '' : undefined}
      aria-busy={loading || undefined}
      className={cn(
        group ? inputEmbedded() : textInputHost({ variant, size: sizeProp }),
        className,
      )}
      onClick={onRootClick}
    >
      {hasLeading && (
        <span className={inputAdornment()}>
          <IconSlot
            boxClass="relative inline-flex items-center justify-center"
            swapped={!!loading}
            spinnerSize={spinnerSize}
          >
            {leading}
          </IconSlot>
        </span>
      )}
      <input
        ref={element}
        {...attrs}
        {...bindings}
        id={fieldId}
        disabled={disabled}
        aria-invalid={invalid || undefined}
        aria-describedby={describedBy}
        className={inputControl({
          leading: hasLeading,
          trailing: clearing || trailingSpinner || hasTrailing,
        })}
      />
      <Transition
        show={trailingSpinner}
        enterActiveClass="hn-transition-base"
        enterFromClass="scale-90 opacity-0"
        leaveActiveClass="hn-transition"
        leaveToClass="scale-90 opacity-0"
      >
        <span className={inputAdornment()}>
          <Spinner size={spinnerSize} />
        </span>
      </Transition>
      <Transition
        show={clearing}
        enterActiveClass="hn-transition-base"
        enterFromClass="scale-90 opacity-0"
        leaveActiveClass="hn-transition"
        leaveToClass="scale-90 opacity-0"
      >
        <span className={inputActionSlot()}>
          <InputAction label={t.common.clear} onClick={clear}>
            <XIcon />
          </InputAction>
        </span>
      </Transition>
      {action}
      {hasTrailing && <span className={inputAdornment()}>{trailing}</span>}
    </div>
  )
}
