// packages/vue/src/components/space/Space.vue
<script setup lang="ts">
  import { cn } from '../../lib/cn'
  import { space, type SpaceVariants } from './space.variants'

  defineOptions({ name: 'HnSpace' })

  const props = defineProps<{
    size?: SpaceVariants['size']
    class?: string
  }>()
</script>

<template>
  <div aria-hidden="true" :class="cn(space({ size: props.size }), props.class)" />
</template>

// packages/react/src/components/space/Space.tsx
import type { HTMLAttributes, Ref } from 'react'
import { cn } from '../../lib/cn'
import { space, type SpaceVariants } from './space.variants'

export interface SpaceProps extends HTMLAttributes<HTMLDivElement> {
  size?: SpaceVariants['size']
  ref?: Ref<HTMLDivElement>
}

export function Space({ size, className, ...props }: SpaceProps) {
  return <div aria-hidden="true" {...props} className={cn(space({ size }), className)} />
}
