// packages/react/src/components/navigation-menu/NavigationMenuTrigger.tsx
'use client'

import type { ButtonHTMLAttributes, ReactNode, Ref } from 'react'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { NavigationMenuTrigger as PrimitiveTrigger } from '../../primitives/navigation-menu'
import { DisclosureIcon } from '../disclosure-icon/DisclosureIcon'
import { useNavigationMenu } from './context'
import {
  navigationMenuControl,
  navigationMenuDisclosure,
  navigationMenuIcon,
  navigationMenuTrigger,
} from './navigation-menu.variants'

export interface NavigationMenuTriggerProps extends Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'disabled'
> {
  disabled?: boolean
  icon?: ReactNode
  trailing?: ReactNode
  ref?: Ref<HTMLButtonElement>
  [attribute: `data-${string}`]: string | undefined
}

export function NavigationMenuTrigger({
  disabled,
  icon,
  trailing,
  className,
  children,
  ref,
  ...attrs
}: NavigationMenuTriggerProps) {
  const menu = useNavigationMenu()
  return (
    <PrimitiveTrigger
      type="button"
      data-hn-navigation-control=""
      disabled={disabled}
      className={cn(
        navigationMenuControl({ size: menu.size, orientation: menu.orientation }),
        navigationMenuTrigger(),
        className,
      )}
      ref={ref as Ref<HTMLElement>}
      {...attrs}
    >
      {hasContent(icon) ? (
        <span className={navigationMenuIcon()} aria-hidden="true">
          {icon}
        </span>
      ) : null}
      <span className="min-w-0 flex-1">{children}</span>
      <span className={navigationMenuIcon()}>
        {hasContent(trailing) ? (
          trailing
        ) : (
          <span className={navigationMenuDisclosure({ orientation: menu.orientation })}>
            <DisclosureIcon direction={menu.orientation === 'vertical' ? 'end' : 'down'} />
          </span>
        )}
      </span>
    </PrimitiveTrigger>
  )
}

// packages/vue/src/components/navigation-menu/NavigationMenuTrigger.vue
<script setup lang="ts">
  import { NavigationMenuTrigger as RekaNavigationMenuTrigger } from 'reka-ui'
  import { cn } from '../../lib/cn'
  import DisclosureIcon from '../disclosure-icon/DisclosureIcon.vue'
  import { useNavigationMenu } from './context'
  import {
    navigationMenuControl,
    navigationMenuTrigger,
    navigationMenuIcon,
    navigationMenuDisclosure,
  } from './navigation-menu.variants'

  defineOptions({ name: 'HnNavigationMenuTrigger' })
  const props = defineProps<{ disabled?: boolean; class?: string }>()
  const menu = useNavigationMenu()
  defineSlots<{ default(): unknown; icon?(): unknown; trailing?(): unknown }>()
</script>

<template>
  <RekaNavigationMenuTrigger
    type="button"
    data-hn-navigation-control
    :disabled="props.disabled"
    :class="
      cn(
        navigationMenuControl({ size: menu.size.value, orientation: menu.orientation.value }),
        navigationMenuTrigger(),
        props.class,
      )
    "
  >
    <span v-if="$slots.icon" :class="navigationMenuIcon()" aria-hidden="true">
      <slot name="icon" />
    </span>
    <span class="min-w-0 flex-1"><slot /></span>
    <span :class="navigationMenuIcon()">
      <slot name="trailing">
        <span :class="navigationMenuDisclosure({ orientation: menu.orientation.value })">
          <DisclosureIcon :direction="menu.orientation.value === 'vertical' ? 'end' : 'down'" />
        </span>
      </slot>
    </span>
  </RekaNavigationMenuTrigger>
</template>
