// docs/react/demos/en/inline/justify.tsx
import { Button, Heading, Inline } from '@hina-ui/react'

export default function Demo() {
  return (
    <Inline justify="between" className="bg-inset w-full rounded-md p-3">
      <Heading level={3} size="md">
        Reading history
      </Heading>
      <Button size="sm" variant="soft" tone="neutral">
        Clear all
      </Button>
    </Inline>
  )
}

// docs/app/demos/en/inline/justify.vue
<script setup lang="ts">
  import { Button, Heading, Inline } from '@hikarinagi/ui'
</script>

<template>
  <Inline justify="between" class="bg-inset w-full rounded-md p-3">
    <Heading :level="3" size="md">Reading history</Heading>
    <Button size="sm" variant="soft" tone="neutral">Clear all</Button>
  </Inline>
</template>
