// docs/app/demos/en/number-format/locale.vue
<script setup lang="ts">
  import { NumberFormat, Stack, Text, enUS, provideUiLocale } from '@hina-ui/vue'
  import { defineComponent, h } from 'vue'

  const English = defineComponent({
    setup(_, { slots }) {
      provideUiLocale(enUS)
      return () => h('span', slots.default?.())
    },
  })
</script>

<template>
  <Stack class="max-w-sm">
    <Text>
      Simplified Chinese:
      <NumberFormat :value="1234567" format="compact" />
    </Text>
    <Text>
      English：
      <English><NumberFormat :value="1234567" format="compact" /></English>
    </Text>
  </Stack>
</template>

// docs-react/demos/en/number-format/locale.tsx
import { createElement, type ReactNode } from 'react'
import { NumberFormat, Stack, Text, UiLocaleProvider, enUS } from '@hina-ui/react'

function English({ children }: { children?: ReactNode }) {
  return createElement(
    'span',
    null,
    <UiLocaleProvider messages={enUS}>{children}</UiLocaleProvider>,
  )
}

export default function Demo() {
  return (
    <Stack className="max-w-sm">
      <Text>
        Simplified Chinese: <NumberFormat value={1234567} format="compact" />
      </Text>
      <Text>
        English：{' '}
        <English>
          <NumberFormat value={1234567} format="compact" />
        </English>
      </Text>
    </Stack>
  )
}
