// docs/app/demos/en/popover/padded.vue
<script setup lang="ts">
  import { Button, Divider, Popover, Stack, Text } from '@hina-ui/vue'
</script>

<template>
  <Popover :padded="false" align="start">
    <Button variant="outline" tone="neutral">Latest update</Button>
    <template #content>
      <Stack gap="none" class="w-64">
        <Stack gap="none" class="bg-inset px-4 py-3">
          <Text size="sm" class="font-medium">Chapter 42</Text>
        </Stack>
        <Divider />
        <Stack gap="xs" class="px-4 py-3">
          <Text tone="muted" size="sm">Written by Isuna Hasekura</Text>
          <Text tone="muted" size="sm">Updated three hours ago</Text>
        </Stack>
      </Stack>
    </template>
  </Popover>
</template>

// docs/react/demos/en/popover/padded.tsx
import { Button, Divider, Popover, Stack, Text } from '@hina-ui/react'

export default function Demo() {
  return (
    <Popover
      padded={false}
      align="start"
      content={
        <Stack gap="none" className="w-64">
          <Stack gap="none" className="bg-inset px-4 py-3">
            <Text size="sm" className="font-medium">
              Chapter 42
            </Text>
          </Stack>
          <Divider />
          <Stack gap="xs" className="px-4 py-3">
            <Text tone="muted" size="sm">
              Written by Isuna Hasekura
            </Text>
            <Text tone="muted" size="sm">
              Updated three hours ago
            </Text>
          </Stack>
        </Stack>
      }
    >
      <Button variant="outline" tone="neutral">
        Latest update
      </Button>
    </Popover>
  )
}
