// packages/vue/src/components/tree/VirtualTreeWindow.vue
<script setup lang="ts" generic="T extends { label: string; disabled?: boolean }">
  import { toRef } from 'vue'
  import type { FlattenedItem } from 'reka-ui'
  import type { VirtualizeOptions } from '../../lib/virtual/types'
  import { useVirtualTree } from '../../lib/reka/useVirtualTree'
  import { virtualListContent, virtualListItem } from '../virtual-list/virtual-list.variants'

  const props = defineProps<{
    items: FlattenedItem<T>[]
    virtualize?: VirtualizeOptions
    initialScrollToSelected?: boolean
    viewport?: HTMLElement
    disabled?: (node: T) => boolean
  }>()
  defineSlots<{ default(props: { item: FlattenedItem<T> }): unknown }>()
  const { body, entries, bodyStyle, measure, focusFirst, focusLast, isFirst } = useVirtualTree(
    props,
    toRef(props, 'viewport'),
  )
  defineExpose({ focusFirst, focusLast, isFirst })
</script>

<template>
  <div
    ref="body"
    data-hn-virtual-tree
    role="presentation"
    :class="virtualListContent({ orientation: 'vertical' })"
    :style="bodyStyle"
  >
    <div
      v-for="entry in entries"
      :key="entry.key"
      :ref="measure"
      :data-index="entry.index"
      role="presentation"
      :class="virtualListItem({ orientation: 'vertical' })"
      :style="{ marginBlockStart: `${entry.gapBefore}px` }"
    >
      <slot :item="props.items[entry.index]!" />
    </div>
  </div>
</template>

// packages/react/src/components/tree/VirtualTreeWindow.tsx
'use client'

import { useImperativeHandle, type ReactNode, type Ref } from 'react'
import type { FlattenedItem } from '../../primitives/tree'
import type { VirtualizeOptions } from '../../lib/virtual/types'
import { useVirtualTree } from '../../lib/virtual/useVirtualTree'
import { virtualListContent, virtualListItem } from '../virtual-list/virtual-list.variants'

export interface VirtualTreeWindowHandle {
  focusFirst(): void
  focusLast(): void
  isFirst(element: EventTarget | null): boolean
}

export interface VirtualTreeWindowProps<T extends { label: string; disabled?: boolean }> {
  items: FlattenedItem<T>[]
  virtualize?: VirtualizeOptions
  initialScrollToSelected?: boolean
  viewport?: HTMLElement
  disabled?: (node: T) => boolean
  children: (props: { item: FlattenedItem<T> }) => ReactNode
  ref?: Ref<VirtualTreeWindowHandle>
}

export function VirtualTreeWindow<T extends { label: string; disabled?: boolean }>({
  items,
  virtualize,
  initialScrollToSelected,
  viewport,
  disabled,
  children,
  ref,
}: VirtualTreeWindowProps<T>) {
  const { body, entries, bodyStyle, measure, focusFirst, focusLast, isFirst } = useVirtualTree<T>(
    { items, virtualize, initialScrollToSelected, disabled },
    viewport,
  )
  useImperativeHandle(ref, () => ({ focusFirst, focusLast, isFirst }))

  return (
    <div
      ref={body as Ref<HTMLDivElement>}
      data-hn-virtual-tree=""
      role="presentation"
      className={virtualListContent({ orientation: 'vertical' })}
      style={bodyStyle}
    >
      {entries.map(entry => (
        <div
          key={entry.key}
          ref={element => measure(element)}
          data-index={entry.index}
          role="presentation"
          className={virtualListItem({ orientation: 'vertical' })}
          style={{ marginBlockStart: `${entry.gapBefore}px` }}
        >
          {children({ item: items[entry.index]! })}
        </div>
      ))}
    </div>
  )
}
