// packages/vue/src/components/tabs/TabsList.vue
<script setup lang="ts">
  import { TabsList } from 'reka-ui'
  import ScrollArea from '../scroll-area/ScrollArea.vue'
  import { cn } from '../../lib/cn'
  import { useTabsStyle } from './context'
  import { tabsList, tabsScroll } from './tabs.variants'

  defineOptions({ name: 'HnTabsList' })

  const props = defineProps<{
    label?: string
    class?: string
  }>()

  const { variant, orientation } = useTabsStyle()
</script>

<template>
  <ScrollArea
    :direction="orientation"
    :scrollbar="false"
    :class="cn(tabsScroll({ variant, orientation }), props.class)"
  >
    <TabsList :aria-label="props.label" :class="cn(tabsList({ variant, orientation }))">
      <slot />
    </TabsList>
  </ScrollArea>
</template>

// packages/react/src/components/tabs/TabsList.tsx
'use client'

import type { ReactNode } from 'react'
import { cn } from '../../lib/cn'
import { TabsList as TabsListPrimitive } from '../../primitives/tabs'
import { ScrollArea, type ScrollAreaProps } from '../scroll-area/ScrollArea'
import { useTabsStyle } from './context'
import { tabsList, tabsScroll } from './tabs.variants'

export interface TabsListProps extends Omit<
  ScrollAreaProps,
  'direction' | 'scrollbar' | 'children'
> {
  label?: string
  children?: ReactNode
}

export function TabsList({ label, className, children, ...attrs }: TabsListProps) {
  const { variant, orientation } = useTabsStyle()
  return (
    <ScrollArea
      direction={orientation}
      scrollbar={false}
      {...attrs}
      className={cn(tabsScroll({ variant, orientation }), className)}
    >
      <TabsListPrimitive aria-label={label} className={cn(tabsList({ variant, orientation }))}>
        {children}
      </TabsListPrimitive>
    </ScrollArea>
  )
}
