// docs/vue/app/demos/zh-CN/popover/anchor.vue
<script setup lang="ts">
  import { ref, shallowRef } from 'vue'
  import { Button, Inline, Popover, Stack, Text } from '@hina-ui/vue'

  const open = ref(false)
  const current = ref(0)
  const anchor = shallowRef<HTMLElement | null>(null)

  function toggle(event: MouseEvent, index: number) {
    const target = event.currentTarget as HTMLElement
    open.value = anchor.value === target ? !open.value : true
    anchor.value = target
    current.value = index
  }
</script>

<template>
  <Inline>
    <Button
      v-for="index in 2"
      :key="index"
      variant="outline"
      tone="neutral"
      aria-haspopup="dialog"
      :aria-expanded="open && current === index"
      @click="toggle($event, index)"
    >
      锚点 {{ index }}
    </Button>
    <Popover v-model:open="open" :anchor="anchor" :modal="false" aria-label="外部锚点">
      <template #content>
        <Stack gap="sm" class="w-56">
          <Text size="sm">默认插槽为空，位置由 anchor 决定。</Text>
          <Button size="sm" variant="soft" tone="neutral" @click="open = false">关闭</Button>
        </Stack>
      </template>
    </Popover>
  </Inline>
</template>

// docs/react/demos/zh-CN/popover/anchor.tsx
'use client'

import { useState, type MouseEvent } from 'react'
import { Button, Inline, Popover, Stack, Text } from '@hina-ui/react'

export default function Demo() {
  const [open, setOpen] = useState(false)
  const [current, setCurrent] = useState(0)
  const [anchor, setAnchor] = useState<HTMLElement | null>(null)

  function toggle(event: MouseEvent<HTMLElement>, index: number) {
    const target = event.currentTarget
    setOpen(anchor === target ? !open : true)
    setAnchor(target)
    setCurrent(index)
  }

  return (
    <Inline>
      {[1, 2].map(index => (
        <Button
          key={index}
          variant="outline"
          tone="neutral"
          aria-haspopup="dialog"
          aria-expanded={open && current === index}
          onClick={event => toggle(event, index)}
        >
          锚点 {index}
        </Button>
      ))}
      <Popover
        open={open}
        onOpenChange={setOpen}
        anchor={anchor}
        modal={false}
        aria-label="外部锚点"
        content={
          <Stack gap="sm" className="w-56">
            <Text size="sm">默认插槽为空，位置由 anchor 决定。</Text>
            <Button size="sm" variant="soft" tone="neutral" onClick={() => setOpen(false)}>
              关闭
            </Button>
          </Stack>
        }
      />
    </Inline>
  )
}
