// docs/vue/app/components/docs/PropPicker.vue
<script setup lang="ts">
  import { Button, ButtonGroup, Inline, Text } from '@hina-ui/vue'

  const props = defineProps<{
    label: string
    options?: readonly string[]
  }>()

  const model = defineModel<string | boolean>()
</script>

<template>
  <Inline gap="xs" class="border-line rounded-md border py-0.5 ps-2.5 pe-0.5">
    <Text as="span" size="xs" tone="muted" class="font-mono">{{ props.label }}</Text>
    <ButtonGroup v-if="props.options" :label="props.label">
      <Button
        v-for="option in props.options"
        :key="option"
        size="sm"
        :variant="model === option ? 'soft' : 'ghost'"
        :tone="model === option ? 'accent' : 'neutral'"
        :aria-pressed="model === option"
        @click="model = option"
      >
        {{ option }}
      </Button>
    </ButtonGroup>
    <Button
      v-else
      size="sm"
      :variant="model ? 'soft' : 'ghost'"
      :tone="model ? 'accent' : 'neutral'"
      :aria-pressed="!!model"
      @click="model = !model"
    >
      {{ model ? 'true' : 'false' }}
    </Button>
  </Inline>
</template>

// docs/react/components/PropPicker.tsx
'use client'

import { Button, ButtonGroup, Inline, Text } from '@hina-ui/react'

interface PropPickerProps {
  label: string
  options?: readonly string[]
  value: string | boolean
  onValueChange: (value: string | boolean) => void
}

export function PropPicker({ label, options, value, onValueChange }: PropPickerProps) {
  return (
    <Inline gap="xs" className="border-line rounded-md border py-0.5 ps-2.5 pe-0.5">
      <Text as="span" size="xs" tone="muted" className="font-mono">
        {label}
      </Text>
      {options ? (
        <ButtonGroup label={label}>
          {options.map(option => (
            <Button
              key={option}
              size="sm"
              variant={value === option ? 'soft' : 'ghost'}
              tone={value === option ? 'accent' : 'neutral'}
              aria-pressed={value === option}
              onClick={() => onValueChange(option)}
            >
              {option}
            </Button>
          ))}
        </ButtonGroup>
      ) : (
        <Button
          size="sm"
          variant={value ? 'soft' : 'ghost'}
          tone={value ? 'accent' : 'neutral'}
          aria-pressed={!!value}
          onClick={() => onValueChange(!value)}
        >
          {value ? 'true' : 'false'}
        </Button>
      )}
    </Inline>
  )
}
