// docs/vue/app/demos/en/form/handle.vue
<script setup lang="ts">
  import { reactive, ref } from 'vue'
  import * as v from 'valibot'
  import { Button, Form, FormField, Input, Stack } from '@hina-ui/vue'

  const schema = v.object({
    name: v.pipe(v.string('Enter a name'), v.nonEmpty('Enter a name')),
  })

  const values = reactive({ name: 'Hoshimi Shion' })
  const form = ref<InstanceType<typeof Form> | null>(null)

  function save() {
    return new Promise(resolve => setTimeout(resolve, 1500))
  }
</script>

<template>
  <Stack gap="md" align="stretch" class="w-80">
    <Form ref="form" :values="values" :rules="schema" @submit="save">
      <FormField name="name" label="Name">
        <Input v-model="values.name" />
      </FormField>
    </Form>
    <Button :loading="form?.submitting" class="self-start" @click="form?.submit()">Save</Button>
  </Stack>
</template>

// docs/react/demos/en/form/handle.tsx
'use client'

import { useState } from 'react'
import * as v from 'valibot'
import { Button, Form, FormField, Input, Stack, useFormHandle } from '@hina-ui/react'

const schema = v.object({
  name: v.pipe(v.string('Enter a name'), v.nonEmpty('Enter a name')),
})

function save() {
  return new Promise(resolve => setTimeout(resolve, 1500))
}

export default function Demo() {
  const [values, setValues] = useState({ name: 'Hoshimi Shion' })
  const form = useFormHandle()

  return (
    <Stack gap="md" align="stretch" className="w-80">
      <Form form={form} values={values} rules={schema} onSubmit={save}>
        <FormField name="name" label="Name">
          <Input value={values.name} onValueChange={name => setValues({ ...values, name })} />
        </FormField>
      </Form>
      <Button loading={form.submitting} className="self-start" onClick={form.submit}>
        Save
      </Button>
    </Stack>
  )
}
