// packages/vue/src/components/sheet/Sheet.vue
<script setup lang="ts">
  import { computed } from 'vue'
  import {
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogOverlay,
    DialogPortal,
    DialogRoot,
    DialogTitle,
    DialogTrigger,
  } from 'reka-ui'
  import { useOverlayPortal } from '../../lib/overlay-portal'
  import { useScrollViewport } from '../../lib/scroll-viewport'
  import { cn } from '../../lib/cn'
  import Card from '../card/Card.vue'
  import CloseButton from '../close-button/CloseButton.vue'
  import Heading from '../heading/Heading.vue'
  import ScrollArea from '../scroll-area/ScrollArea.vue'
  import Text from '../text/Text.vue'
  import { useDragToDismiss } from './composables/useDragToDismiss'
  import { sheetGrip, sheetHandle, sheetPanel } from './sheet.variants'

  defineOptions({ name: 'HnSheet' })

  const props = withDefaults(
    defineProps<{
      title: string
      description?: string
      header?: boolean
      closable?: boolean
      handle?: boolean
      locked?: boolean
      class?: string
    }>(),
    { header: true, closable: true, handle: true, locked: false },
  )

  const slots = defineSlots<{
    default?(): unknown
    icon?(): unknown
    title?(): unknown
    body?(props: { close: () => void }): unknown
    content?(props: { close: () => void }): unknown
    footer?(props: { close: () => void }): unknown
  }>()

  const { scrollArea, viewport } = useScrollViewport()
  defineExpose({ viewport })

  const open = defineModel<boolean>('open')
  const { content: panel, present } = useOverlayPortal(open)

  const { dragging, offset, onPointerDown } = useDragToDismiss(() => panel.value?.$el ?? null, {
    enabled: () => !props.locked,
    open,
    dismiss: () => (open.value = false),
  })

  const style = computed(() =>
    offset.value
      ? { transform: `translateY(${offset.value}px)`, '--hn-sheet-from-y': `${offset.value}px` }
      : undefined,
  )

  function guard(event: Event) {
    if (props.locked) event.preventDefault()
  }

  function close() {
    open.value = false
  }
</script>

<template>
  <DialogRoot v-model:open="open">
    <DialogTrigger v-if="$slots.default" as-child>
      <slot />
    </DialogTrigger>
    <DialogPortal v-if="present">
      <DialogOverlay class="hn-scrim" />
      <DialogContent as-child @escape-key-down="guard" @interact-outside="guard">
        <Card
          ref="panel"
          v-bind="props.description ? {} : { 'aria-describedby': undefined }"
          data-hn-sheet
          :data-dragging="dragging ? '' : undefined"
          :padded="false"
          :style="style"
          :class="
            cn(sheetPanel({ grip: props.header || props.handle, padded: !slots.body }), props.class)
          "
        >
          <template v-if="!props.header || slots.body">
            <DialogTitle as-child>
              <Heading :level="2" class="sr-only">{{ props.title }}</Heading>
            </DialogTitle>
            <DialogDescription v-if="props.description" class="sr-only">
              {{ props.description }}
            </DialogDescription>
          </template>
          <div
            v-if="props.handle || (props.header && !slots.body)"
            data-hn-sheet-grip
            :data-dragging="dragging ? '' : undefined"
            :class="sheetGrip({ standalone: !!slots.body })"
            @pointerdown="onPointerDown"
          >
            <div
              v-if="props.handle"
              aria-hidden="true"
              :data-disabled="props.locked ? '' : undefined"
              :class="sheetHandle({ header: props.header && !slots.body })"
            />
            <div
              v-if="props.header && !slots.body"
              class="flex items-start justify-between gap-4 px-(--hn-panel-p)"
            >
              <div class="flex min-w-0 flex-col gap-1.5">
                <div class="flex min-w-0 items-center gap-2">
                  <span
                    v-if="slots.icon"
                    class="text-muted flex shrink-0 [&_svg]:size-5"
                    aria-hidden="true"
                  >
                    <slot name="icon" />
                  </span>
                  <DialogTitle as-child>
                    <Heading :level="2" size="lg" class="min-w-0">
                      <slot name="title">{{ props.title }}</slot>
                    </Heading>
                  </DialogTitle>
                </div>
                <DialogDescription v-if="props.description" as-child>
                  <Text tone="muted">{{ props.description }}</Text>
                </DialogDescription>
              </div>
              <DialogClose v-if="!props.handle && props.closable" as-child>
                <CloseButton :disabled="props.locked" class="-mt-1.5 -me-1.5 shrink-0" />
              </DialogClose>
            </div>
          </div>
          <slot v-if="slots.body" name="body" :close="close" />
          <template v-else>
            <ScrollArea v-if="$slots.content" ref="scrollArea" class="min-h-0 grow">
              <div class="px-(--hn-panel-p) py-1">
                <slot name="content" :close="close" />
              </div>
            </ScrollArea>
            <div
              v-if="$slots.footer"
              class="flex shrink-0 justify-end gap-(--hn-inline-gap) px-(--hn-panel-p)"
            >
              <slot name="footer" :close="close" />
            </div>
          </template>
        </Card>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

// packages/react/src/components/sheet/Sheet.tsx
'use client'

import { useImperativeHandle, useRef, type CSSProperties, type ReactNode, type Ref } from 'react'
import { useControllableState } from 'radix-ui/internal'
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogOverlay,
  DialogPortal,
  DialogRoot,
  DialogTitle,
  DialogTrigger,
} from '../../primitives/dialog'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { useOverlayPortal } from '../../lib/overlay-portal'
import { useScrollViewport } from '../../lib/scroll-viewport'
import { Card } from '../card/Card'
import { CloseButton } from '../close-button/CloseButton'
import { Heading } from '../heading/Heading'
import { ScrollArea } from '../scroll-area/ScrollArea'
import { Text } from '../text/Text'
import { useDragToDismiss } from './hooks/useDragToDismiss'
import { sheetGrip, sheetHandle, sheetPanel } from './sheet.variants'

export interface SheetSlotProps {
  close: () => void
}

export interface SheetHandle {
  readonly viewport: HTMLElement | undefined
}

export interface SheetProps {
  title: string
  titleContent?: ReactNode
  description?: string
  header?: boolean
  closable?: boolean
  handle?: boolean
  locked?: boolean
  className?: string
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  children?: ReactNode
  icon?: ReactNode
  renderBody?: (props: SheetSlotProps) => ReactNode
  renderContent?: (props: SheetSlotProps) => ReactNode
  renderFooter?: (props: SheetSlotProps) => ReactNode
  ref?: Ref<SheetHandle>
}

export function Sheet({
  title,
  titleContent,
  description,
  header = true,
  closable = true,
  handle = true,
  locked = false,
  className,
  open: openProp,
  defaultOpen,
  onOpenChange,
  children,
  icon,
  renderBody,
  renderContent,
  renderFooter,
  ref,
}: SheetProps) {
  const [open, setOpen] = useControllableState({
    prop: openProp,
    defaultProp: defaultOpen ?? false,
    onChange: onOpenChange,
    caller: 'Sheet',
  })
  const { contentRef, content: panel, present } = useOverlayPortal(open)
  const { scrollArea, viewport, read } = useScrollViewport()
  const panelRef = useRef(panel)
  panelRef.current = panel

  useImperativeHandle(
    ref,
    () => ({
      get viewport() {
        return read()
      },
    }),
    [viewport, read],
  )

  const { dragging, offset, onPointerDown } = useDragToDismiss(() => panelRef.current, {
    enabled: !locked,
    open,
    dismiss: () => setOpen(false),
  })

  const style = offset
    ? ({
        transform: `translateY(${offset}px)`,
        '--hn-sheet-from-y': `${offset}px`,
      } as CSSProperties)
    : undefined

  function guard(event: Event) {
    if (locked) event.preventDefault()
  }

  const close = () => setOpen(false)
  const body = renderBody !== undefined

  return (
    <DialogRoot open={open} onOpenChange={setOpen}>
      {hasContent(children) && <DialogTrigger asChild>{children}</DialogTrigger>}
      {present && (
        <DialogPortal>
          <DialogOverlay className="hn-scrim" />
          <DialogContent asChild onEscapeKeyDown={guard} onInteractOutside={guard}>
            <Card
              ref={contentRef}
              {...(description ? {} : { 'aria-describedby': undefined })}
              data-hn-sheet=""
              data-dragging={dragging ? '' : undefined}
              padded={false}
              style={style}
              className={cn(sheetPanel({ grip: header || handle, padded: !body }), className)}
            >
              {(!header || body) && (
                <>
                  <DialogTitle asChild>
                    <Heading level={2} className="sr-only">
                      {title}
                    </Heading>
                  </DialogTitle>
                  {description && (
                    <DialogDescription className="sr-only">{description}</DialogDescription>
                  )}
                </>
              )}
              {(handle || (header && !body)) && (
                <div
                  data-hn-sheet-grip=""
                  data-dragging={dragging ? '' : undefined}
                  className={sheetGrip({ standalone: body })}
                  onPointerDown={onPointerDown}
                >
                  {handle && (
                    <div
                      aria-hidden="true"
                      data-disabled={locked ? '' : undefined}
                      className={sheetHandle({ header: header && !body })}
                    />
                  )}
                  {header && !body && (
                    <div className="flex items-start justify-between gap-4 px-(--hn-panel-p)">
                      <div className="flex min-w-0 flex-col gap-1.5">
                        <div className="flex min-w-0 items-center gap-2">
                          {hasContent(icon) && (
                            <span
                              className="text-muted flex shrink-0 [&_svg]:size-5"
                              aria-hidden="true"
                            >
                              {icon}
                            </span>
                          )}
                          <DialogTitle asChild>
                            <Heading level={2} size="lg" className="min-w-0">
                              {titleContent ?? title}
                            </Heading>
                          </DialogTitle>
                        </div>
                        {description && (
                          <DialogDescription asChild>
                            <Text tone="muted">{description}</Text>
                          </DialogDescription>
                        )}
                      </div>
                      {!handle && closable && (
                        <DialogClose asChild>
                          <CloseButton disabled={locked} className="-mt-1.5 -me-1.5 shrink-0" />
                        </DialogClose>
                      )}
                    </div>
                  )}
                </div>
              )}
              {body ? (
                renderBody({ close })
              ) : (
                <>
                  {renderContent && (
                    <ScrollArea ref={scrollArea} className="min-h-0 grow">
                      <div className="px-(--hn-panel-p) py-1">{renderContent({ close })}</div>
                    </ScrollArea>
                  )}
                  {renderFooter && (
                    <div className="flex shrink-0 justify-end gap-(--hn-inline-gap) px-(--hn-panel-p)">
                      {renderFooter({ close })}
                    </div>
                  )}
                </>
              )}
            </Card>
          </DialogContent>
        </DialogPortal>
      )}
    </DialogRoot>
  )
}
