// packages/react/src/components/heading/Heading.tsx
import type { HTMLAttributes, Ref } from 'react'
import { cn } from '../../lib/cn'
import { heading, type HeadingVariants } from './heading.variants'

const sizeByLevel = {
  1: '2xl',
  2: 'xl',
  3: 'lg',
  4: 'md',
  5: 'base',
  6: 'sm',
} as const

export interface HeadingProps extends HTMLAttributes<HTMLHeadingElement> {
  level?: 1 | 2 | 3 | 4 | 5 | 6
  size?: HeadingVariants['size']
  weight?: HeadingVariants['weight']
  truncate?: boolean
  ref?: Ref<HTMLHeadingElement>
}

export function Heading({ level = 2, size, weight, truncate, className, ...props }: HeadingProps) {
  const Tag = `h${level}` as const
  return (
    <Tag
      {...props}
      className={cn(heading({ size: size ?? sizeByLevel[level], weight, truncate }), className)}
    />
  )
}

// packages/vue/src/components/heading/Heading.vue
<script setup lang="ts">
  import { computed } from 'vue'
  import { Primitive } from 'reka-ui'
  import { cn } from '../../lib/cn'
  import { heading, type HeadingVariants } from './heading.variants'

  defineOptions({ name: 'HnHeading' })

  const props = withDefaults(
    defineProps<{
      level?: 1 | 2 | 3 | 4 | 5 | 6
      size?: HeadingVariants['size']
      weight?: HeadingVariants['weight']
      truncate?: boolean
      class?: string
    }>(),
    { level: 2 },
  )

  const sizeByLevel = {
    1: '2xl',
    2: 'xl',
    3: 'lg',
    4: 'md',
    5: 'base',
    6: 'sm',
  } as const

  const tag = computed(() => `h${props.level}`)
  const size = computed(() => props.size ?? sizeByLevel[props.level])
</script>

<template>
  <Primitive
    :as="tag"
    :class="
      cn(
        heading({
          size: size,
          weight: props.weight,
          truncate: props.truncate,
        }),
        props.class,
      )
    "
  >
    <slot />
  </Primitive>
</template>
