// docs/vue/app/demos/zh-CN/checkbox/indeterminate.vue
<script setup lang="ts">
  import { computed, ref } from 'vue'
  import { Checkbox, Stack } from '@hina-ui/vue'

  const types = ['Galgame', '轻小说', '漫画']
  const picked = ref(['Galgame'])

  const all = computed<boolean | 'indeterminate'>({
    get: () =>
      picked.value.length === 0
        ? false
        : picked.value.length === types.length
          ? true
          : 'indeterminate',
    set: value => {
      picked.value = value === true ? [...types] : []
    },
  })

  function toggle(type: string, on: boolean | 'indeterminate') {
    picked.value = on === true ? [...picked.value, type] : picked.value.filter(t => t !== type)
  }
</script>

<template>
  <Stack gap="sm">
    <Checkbox v-model="all">全部类型</Checkbox>
    <Stack gap="sm" class="ps-6">
      <Checkbox
        v-for="type in types"
        :key="type"
        :model-value="picked.includes(type)"
        @update:model-value="toggle(type, $event)"
      >
        {{ type }}
      </Checkbox>
    </Stack>
  </Stack>
</template>

// docs-react/demos/zh-CN/checkbox/indeterminate.tsx
'use client'

import { useState } from 'react'
import { Checkbox, Stack } from '@hina-ui/react'

const types = ['Galgame', '轻小说', '漫画']

export default function Demo() {
  const [picked, setPicked] = useState(['Galgame'])

  const all: boolean | 'indeterminate' =
    picked.length === 0 ? false : picked.length === types.length ? true : 'indeterminate'

  function setAll(value: boolean | 'indeterminate') {
    setPicked(value === true ? [...types] : [])
  }

  function toggle(type: string, on: boolean | 'indeterminate') {
    setPicked(on === true ? [...picked, type] : picked.filter(t => t !== type))
  }

  return (
    <Stack gap="sm">
      <Checkbox checked={all} onCheckedChange={setAll}>
        全部类型
      </Checkbox>
      <Stack gap="sm" className="ps-6">
        {types.map(type => (
          <Checkbox
            key={type}
            checked={picked.includes(type)}
            onCheckedChange={value => toggle(type, value)}
          >
            {type}
          </Checkbox>
        ))}
      </Stack>
    </Stack>
  )
}
