// docs/app/demos/en/close-button/in-dialog.vue
<script setup lang="ts">
  import { Button, Dialog, Text } from '@hikarinagi/ui'
</script>

<template>
  <Dialog title="Export data" description="Choose a format to export the current selection.">
    <Button variant="outline" tone="neutral">Open dialog</Button>
    <template #content>
      <Text tone="muted">
        The close button in the corner comes with Dialog; there is no need to add another.
      </Text>
    </template>
  </Dialog>
</template>

// docs/react/demos/en/close-button/in-dialog.tsx
'use client'

import { Button, Dialog, Text } from '@hina-ui/react'

export default function Demo() {
  return (
    <Dialog
      title="Export data"
      description="Choose a format to export the current selection."
      renderContent={() => (
        <Text tone="muted">
          The close button in the corner comes with Dialog; there is no need to add another.
        </Text>
      )}
    >
      <Button variant="outline" tone="neutral">
        Open dialog
      </Button>
    </Dialog>
  )
}
