// packages/react/src/components/loading-overlay/LoadingOverlay.tsx
'use client'

import type { ReactNode } from 'react'
import { cn } from '../../lib/cn'
import { hasContent } from '../../lib/content'
import { Transition } from '../../lib/transition/Transition'
import { Spinner } from '../spinner/Spinner'
import type { SpinnerVariants } from '../spinner/spinner.variants'
import { Text } from '../text/Text'
import { useDelayedVisible } from './hooks/useDelayedVisible'
import { loadingBlocker, loadingOverlay } from './loading-overlay.variants'

export interface LoadingOverlayProps {
  visible?: boolean
  text?: string
  fixed?: boolean
  size?: SpinnerVariants['size']
  delay?: number
  minVisible?: number
  className?: string
  children?: ReactNode
}

export function LoadingOverlay({
  visible = false,
  text,
  fixed = false,
  size = 'md',
  delay = 300,
  minVisible = 300,
  className,
  children,
}: LoadingOverlayProps) {
  const shown = useDelayedVisible(visible, delay, minVisible)
  return (
    <>
      {visible && !shown && (
        <div data-hn-loading-blocker="" aria-hidden="true" className={loadingBlocker({ fixed })} />
      )}
      <Transition
        show={shown}
        enterActiveClass="hn-transition-base"
        enterFromClass="opacity-0"
        leaveActiveClass="hn-transition"
        leaveToClass="opacity-0"
      >
        <div data-hn-loading-overlay="" className={cn(loadingOverlay({ fixed }), className)}>
          {hasContent(children) ? (
            children
          ) : (
            <>
              <Spinner size={size} label={text} />
              {text && (
                <Text size="sm" tone="muted" aria-hidden="true">
                  {text}
                </Text>
              )}
            </>
          )}
        </div>
      </Transition>
    </>
  )
}

// packages/vue/src/components/loading-overlay/LoadingOverlay.vue
<script setup lang="ts">
  import { cn } from '../../lib/cn'
  import Spinner from '../spinner/Spinner.vue'
  import type { SpinnerVariants } from '../spinner/spinner.variants'
  import Text from '../text/Text.vue'
  import { useDelayedVisible } from './composables/useDelayedVisible'
  import { loadingBlocker, loadingOverlay } from './loading-overlay.variants'

  defineOptions({ name: 'HnLoadingOverlay' })

  const props = withDefaults(
    defineProps<{
      visible?: boolean
      text?: string
      fixed?: boolean
      size?: SpinnerVariants['size']
      delay?: number
      minVisible?: number
      class?: string
    }>(),
    { visible: false, fixed: false, size: 'md', delay: 300, minVisible: 300 },
  )

  const shown = useDelayedVisible(
    () => props.visible,
    () => ({ delay: props.delay, minVisible: props.minVisible }),
  )
</script>

<template>
  <div
    v-if="props.visible && !shown"
    data-hn-loading-blocker
    aria-hidden="true"
    :class="loadingBlocker({ fixed: props.fixed })"
  />
  <Transition
    enter-active-class="hn-transition-base"
    enter-from-class="opacity-0"
    leave-active-class="hn-transition"
    leave-to-class="opacity-0"
  >
    <div
      v-if="shown"
      data-hn-loading-overlay
      :class="cn(loadingOverlay({ fixed: props.fixed }), props.class)"
    >
      <slot>
        <Spinner :size="props.size" :label="props.text" />
        <Text v-if="props.text" size="sm" tone="muted" aria-hidden="true">{{ props.text }}</Text>
      </slot>
    </div>
  </Transition>
</template>
