// packages/react/src/components/progress/Progress.tsx
'use client'

import type { CSSProperties, HTMLAttributes, Ref } from 'react'
import { cn } from '../../lib/cn'
import { useProgressValue, type ProgressFormat } from './hooks/useProgressValue'
import {
  progress,
  progressBar,
  progressHeader,
  progressTrack,
  progressValue,
  type ProgressVariants,
} from './progress.variants'
import { ProgressIndicator, ProgressRoot } from '../../primitives/progress'

export type { ProgressFormat }

export interface ProgressProps extends HTMLAttributes<HTMLDivElement> {
  value?: number | null
  max?: number
  label?: string
  showValue?: boolean
  format?: ProgressFormat
  tone?: ProgressVariants['tone']
  size?: ProgressVariants['size']
  ref?: Ref<HTMLDivElement>
  [attribute: `data-${string}`]: string | undefined
}

export function Progress({
  value = null,
  max = 100,
  label,
  showValue = false,
  format,
  tone,
  size,
  className,
  ...attrs
}: ProgressProps) {
  const { current, ratio, text, name } = useProgressValue({ value, max, label, format })

  return (
    <div
      data-hn-progress=""
      className={cn(progress(), className)}
      style={{ '--hn-progress-p': String(ratio) } as CSSProperties}
    >
      {label || (showValue && text) ? (
        <div className={progressHeader()}>
          {label ? <span>{label}</span> : null}
          {showValue && text ? <span className={progressValue()}>{text}</span> : null}
        </div>
      ) : null}
      <ProgressRoot
        aria-label={name}
        aria-valuetext={format ? text : undefined}
        {...attrs}
        value={current}
        max={max}
        className={progressTrack({ size })}
      >
        <ProgressIndicator className={progressBar({ tone })} />
      </ProgressRoot>
    </div>
  )
}

// packages/vue/src/components/progress/Progress.vue
<script setup lang="ts">
  import { ProgressIndicator, ProgressRoot } from '../../primitives/progress'
  import { cn } from '../../lib/cn'
  import { useProgressValue, type ProgressFormat } from './composables/useProgressValue'
  import {
    progress,
    progressBar,
    progressHeader,
    progressTrack,
    progressValue,
    type ProgressVariants,
  } from './progress.variants'

  defineOptions({ name: 'HnProgress', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      value?: number | null
      max?: number
      label?: string
      showValue?: boolean
      format?: ProgressFormat
      tone?: ProgressVariants['tone']
      size?: ProgressVariants['size']
      class?: string
    }>(),
    { value: null, max: 100, showValue: false },
  )

  const { current, ratio, text, name } = useProgressValue({
    value: () => props.value,
    max: () => props.max,
    label: () => props.label,
    format: () => props.format,
  })
</script>

<template>
  <div
    data-hn-progress
    :class="cn(progress(), props.class)"
    :style="{ '--hn-progress-p': String(ratio) }"
  >
    <div v-if="props.label || (props.showValue && text)" :class="progressHeader()">
      <span v-if="props.label">{{ props.label }}</span>
      <span v-if="props.showValue && text" :class="progressValue()">{{ text }}</span>
    </div>
    <ProgressRoot
      v-bind="$attrs"
      :model-value="current"
      :max="props.max"
      :get-value-label="() => name"
      :get-value-text="props.format ? () => text : undefined"
      :class="progressTrack({ size: props.size })"
    >
      <ProgressIndicator :class="progressBar({ tone: props.tone })" />
    </ProgressRoot>
  </div>
</template>
