// packages/vue/src/components/pin-input/PinInput.vue
<script setup lang="ts">
  import { PinInputInput, PinInputRoot } from '../../primitives/pin-input'
  import { computed } from 'vue'
  import { cn } from '../../lib/cn'
  import { useFieldControl } from '../form-field/context'
  import { useUiLocale } from '../../locale'
  import { pinInput, pinInputCell, type PinInputVariants } from './pin-input.variants'

  defineOptions({ name: 'HnPinInput' })

  const props = withDefaults(
    defineProps<{
      length?: number
      type?: 'text' | 'number'
      mask?: boolean
      otp?: boolean
      placeholder?: string
      name?: string
      variant?: PinInputVariants['variant']
      size?: PinInputVariants['size']
      disabled?: boolean
      invalid?: boolean
      class?: string
    }>(),
    { length: 6, type: 'text', placeholder: '' },
  )

  const emit = defineEmits<{ complete: [value: string] }>()

  const model = defineModel<string>({ default: '' })

  const t = useUiLocale()

  const { labelledBy, invalid, disabled, describedBy } = useFieldControl({
    invalid: () => props.invalid,
    disabled: () => props.disabled,
  })

  const cells = computed(() => Array.from({ length: props.length }, (_, i) => model.value[i] ?? ''))

  function update(value: (string | number)[] | undefined) {
    const next = (value ?? []).map(cell => (cell === undefined ? '' : String(cell))).join('')
    if (next !== model.value) model.value = next
  }
</script>

<template>
  <PinInputRoot
    role="group"
    :aria-labelledby="labelledBy"
    :aria-describedby="describedBy"
    :model-value="cells"
    :type="props.type"
    :mask="props.mask"
    :otp="props.otp"
    :placeholder="props.placeholder"
    :name="props.name"
    :disabled="disabled"
    data-hn-pin-input
    :data-invalid="invalid ? '' : undefined"
    :class="cn(pinInput(), props.class)"
    @update:model-value="update"
    @complete="value => emit('complete', value.map(String).join(''))"
  >
    <PinInputInput
      v-for="index in props.length"
      :key="index"
      :index="index - 1"
      :aria-label="t.pinInput.cellLabel(index, props.length)"
      :aria-invalid="invalid || undefined"
      :data-invalid="invalid ? '' : undefined"
      :class="pinInputCell({ variant: props.variant, size: props.size })"
    />
  </PinInputRoot>
</template>

// packages/react/src/components/pin-input/PinInput.tsx
'use client'

import { useMemo, type HTMLAttributes, type Ref } from 'react'
import { useControllableState } from 'radix-ui/internal'
import { cn } from '../../lib/cn'
import { useUiLocale } from '../../locale'
import { PinInputInput, PinInputRoot, type PinInputValue } from '../../primitives/pin-input'
import { useFieldControl } from '../form-field/context'
import { pinInput, pinInputCell, type PinInputVariants } from './pin-input.variants'

export interface PinInputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'defaultValue' | 'onChange' | 'children' | 'placeholder' | 'dir'
> {
  length?: number
  type?: 'text' | 'number'
  mask?: boolean
  otp?: boolean
  placeholder?: string
  name?: string
  variant?: PinInputVariants['variant']
  size?: PinInputVariants['size']
  disabled?: boolean
  invalid?: boolean
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
  onComplete?: (value: string) => void
  dir?: 'ltr' | 'rtl'
  id?: string
  required?: boolean
  ref?: Ref<HTMLElement>
  [attribute: `data-${string}`]: string | undefined
}

export function PinInput({
  length = 6,
  type = 'text',
  mask,
  otp,
  placeholder = '',
  name,
  variant,
  size,
  disabled: disabledProp,
  invalid: invalidProp,
  value,
  defaultValue,
  onValueChange,
  onComplete,
  className,
  ...attrs
}: PinInputProps) {
  const [model = '', setModel] = useControllableState<string>({
    prop: value,
    defaultProp: defaultValue ?? '',
    onChange: onValueChange,
    caller: 'PinInput',
  })
  const t = useUiLocale()
  const { labelledBy, invalid, disabled, describedBy } = useFieldControl(
    { invalid: invalidProp, disabled: disabledProp },
    attrs,
  )

  const cells = useMemo(() => Array.from({ length }, (_, i) => model[i] ?? ''), [model, length])

  function update(next: PinInputValue | undefined) {
    const text = (next ?? []).map(cell => (cell === undefined ? '' : String(cell))).join('')
    if (text !== model) setModel(text)
  }

  return (
    <PinInputRoot
      role="group"
      aria-labelledby={labelledBy}
      aria-describedby={describedBy}
      value={cells}
      type={type}
      mask={mask}
      otp={otp}
      placeholder={placeholder}
      name={name}
      disabled={disabled}
      data-hn-pin-input=""
      data-invalid={invalid ? '' : undefined}
      onValueChange={update}
      onComplete={next => onComplete?.(next.map(String).join(''))}
      {...attrs}
      className={cn(pinInput(), className)}
    >
      {Array.from({ length }, (_, i) => (
        <PinInputInput
          key={i + 1}
          index={i}
          aria-label={t.pinInput.cellLabel(i + 1, length)}
          aria-invalid={invalid || undefined}
          data-invalid={invalid ? '' : undefined}
          className={pinInputCell({ variant, size })}
        />
      ))}
    </PinInputRoot>
  )
}
