// docs/react/demos/en/dropdown-menu/submenu.tsx
import { Download, Share2 } from 'lucide-react'
import {
  Button,
  DropdownMenu,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuSub,
} from '@hina-ui/react'

export default function Demo() {
  return (
    <DropdownMenu
      label="File actions"
      align="start"
      content={
        <>
          <DropdownMenuItem>Rename</DropdownMenuItem>
          <DropdownMenuSub label="Share with" icon={<Share2 />}>
            <DropdownMenuItem>Copy link</DropdownMenuItem>
            <DropdownMenuItem>Send by email</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Invite a collaborator</DropdownMenuItem>
          </DropdownMenuSub>
          <DropdownMenuSub label="Export as" icon={<Download />}>
            <DropdownMenuItem>PDF</DropdownMenuItem>
            <DropdownMenuItem>EPUB</DropdownMenuItem>
            <DropdownMenuItem>Plain text</DropdownMenuItem>
          </DropdownMenuSub>
        </>
      }
    >
      <Button variant="outline" tone="neutral">
        File
      </Button>
    </DropdownMenu>
  )
}

// docs/app/demos/en/dropdown-menu/submenu.vue
<script setup lang="ts">
  import { Download, Share2 } from '@lucide/vue'
  import {
    Button,
    DropdownMenu,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuSub,
  } from '@hikarinagi/ui'
</script>

<template>
  <DropdownMenu label="File actions" align="start">
    <Button variant="outline" tone="neutral">File</Button>
    <template #content>
      <DropdownMenuItem>Rename</DropdownMenuItem>
      <DropdownMenuSub label="Share with">
        <template #icon>
          <Share2 />
        </template>
        <DropdownMenuItem>Copy link</DropdownMenuItem>
        <DropdownMenuItem>Send by email</DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem>Invite a collaborator</DropdownMenuItem>
      </DropdownMenuSub>
      <DropdownMenuSub label="Export as">
        <template #icon>
          <Download />
        </template>
        <DropdownMenuItem>PDF</DropdownMenuItem>
        <DropdownMenuItem>EPUB</DropdownMenuItem>
        <DropdownMenuItem>Plain text</DropdownMenuItem>
      </DropdownMenuSub>
    </template>
  </DropdownMenu>
</template>
