// packages/vue/src/components/date-range-picker/DateRangePicker.vue
<script setup lang="ts">
  import { computed, shallowRef, useSlots } from 'vue'
  import {
    PopoverAnchor,
    PopoverContent,
    PopoverPortal,
    PopoverRoot,
    PopoverTrigger,
  } from 'reka-ui'
  import { CalendarRange } from '@lucide/vue'
  import { cn } from '../../lib/cn'
  import type { DateRangeValue } from '../../lib/date'
  import { useUiLocale } from '../../locale'
  import type { CalendarVariants } from '../calendar/calendar.variants'
  import Card from '../card/Card.vue'
  import DateRangeField from '../date-range-field/DateRangeField.vue'
  import { datePickerContent } from '../date-picker/date-picker.variants'
  import { useFieldControl } from '../form-field/context'
  import { injectInputGroup } from '../input-group/context'
  import InputGroupScope from '../input-group/InputGroupScope.vue'
  import InputAction from '../input/InputAction.vue'
  import { inputEmbedded, inputHost, type InputVariants } from '../input/input.variants'
  import RangeCalendar from '../range-calendar/RangeCalendar.vue'

  defineOptions({ name: 'HnDateRangePicker', inheritAttrs: false })

  const props = withDefaults(
    defineProps<{
      placeholder?: string
      min?: string
      max?: string
      maximumDays?: number
      unavailable?: (date: string) => boolean
      weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6
      weekdayFormat?: 'narrow' | 'short'
      fixedWeeks?: boolean
      clearable?: boolean
      readonly?: boolean
      name?: string
      variant?: InputVariants['variant']
      size?: InputVariants['size']
      disabled?: boolean
      invalid?: boolean
      class?: string
    }>(),
    { clearable: false, fixedWeeks: true },
  )
  const emit = defineEmits<{ clear: [] }>()

  const model = defineModel<DateRangeValue | null>({ default: null })
  const open = defineModel<boolean>('open', { default: false })

  const slots = useSlots()
  const t = useUiLocale()
  const outer = injectInputGroup()
  const host = shallowRef<HTMLElement | null>(null)

  const size = computed(() => (outer ? outer.size.value : props.size))
  const { invalid, disabled } = useFieldControl({
    invalid: () => props.invalid || !!outer?.invalid.value,
    disabled: () => props.disabled || !!outer?.disabled.value,
  })
  const calendarSize = computed<CalendarVariants['size']>(() => size.value ?? 'md')

  function pick(next: DateRangeValue | null) {
    model.value = next
    if (next?.start && next.end) open.value = false
  }
</script>

<template>
  <PopoverRoot v-model:open="open" modal>
    <PopoverAnchor as-child>
      <div
        ref="host"
        data-hn-date-range-picker
        :data-invalid="invalid ? '' : undefined"
        :class="
          cn(
            outer ? inputEmbedded() : inputHost({ variant: props.variant, size: props.size }),
            props.class,
          )
        "
      >
        <InputGroupScope :size="size" :disabled="disabled" :invalid="invalid">
          <DateRangeField
            v-bind="$attrs"
            :model-value="model"
            :placeholder="props.placeholder"
            :min="props.min"
            :max="props.max"
            :clearable="props.clearable"
            :readonly="props.readonly"
            :name="props.name"
            @update:model-value="model = $event"
            @clear="emit('clear')"
          >
            <template v-if="slots.leading" #leading>
              <slot name="leading" />
            </template>
          </DateRangeField>
        </InputGroupScope>
        <PopoverTrigger as-child>
          <InputAction :label="t.datePicker.open" :disabled="disabled">
            <CalendarRange />
          </InputAction>
        </PopoverTrigger>
      </div>
    </PopoverAnchor>
    <PopoverPortal>
      <PopoverContent
        as-child
        side="bottom"
        align="start"
        :side-offset="8"
        @open-auto-focus.prevent
      >
        <Card :padded="false" :class="datePickerContent()">
          <RangeCalendar
            :model-value="model"
            :placeholder="props.placeholder"
            :min="props.min"
            :max="props.max"
            :maximum-days="props.maximumDays"
            :unavailable="props.unavailable"
            :week-starts-on="props.weekStartsOn"
            :weekday-format="props.weekdayFormat"
            :fixed-weeks="props.fixedWeeks"
            :size="calendarSize"
            :readonly="props.readonly"
            autofocus
            @update:model-value="pick"
          />
        </Card>
      </PopoverContent>
    </PopoverPortal>
  </PopoverRoot>
</template>

// packages/react/src/components/date-range-picker/DateRangePicker.tsx
'use client'

import type { HTMLAttributes, ReactNode } from 'react'
import { CalendarRange } from 'lucide-react'
import { useControllableState } from 'radix-ui/internal'
import { cn } from '../../lib/cn'
import type { DateRangeValue } from '../../../../shared/src/lib/date'
import { lucide } from '../../lib/icon'
import { useUiLocale } from '../../locale'
import {
  PopoverAnchor,
  PopoverContent,
  PopoverPortal,
  PopoverRoot,
  PopoverTrigger,
} from '../../primitives/popover'
import type { CalendarVariants } from '../calendar/calendar.variants'
import { Card } from '../card/Card'
import { DateRangeField } from '../date-range-field/DateRangeField'
import { datePickerContent } from '../date-picker/date-picker.variants'
import { useFieldControl } from '../form-field/context'
import { useInputGroup } from '../input-group/context'
import { InputGroupScope } from '../input-group/InputGroupScope'
import { InputAction } from '../input/InputAction'
import { inputEmbedded, inputHost, type InputVariants } from '../input/input.variants'
import { RangeCalendar } from '../range-calendar/RangeCalendar'

const CalendarRangeIcon = lucide(CalendarRange)

export interface DateRangePickerProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'placeholder' | 'defaultValue' | 'children'
> {
  value?: DateRangeValue | null
  defaultValue?: DateRangeValue | null
  onValueChange?: (value: DateRangeValue | null) => void
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  placeholder?: string
  min?: string
  max?: string
  maximumDays?: number
  unavailable?: (date: string) => boolean
  weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6
  weekdayFormat?: 'narrow' | 'short'
  fixedWeeks?: boolean
  clearable?: boolean
  readonly?: boolean
  name?: string
  variant?: InputVariants['variant']
  size?: InputVariants['size']
  disabled?: boolean
  invalid?: boolean
  onClear?: () => void
  leading?: ReactNode
  [attribute: `data-${string}`]: string | undefined
}

export function DateRangePicker({
  value,
  defaultValue,
  onValueChange,
  open: openProp,
  defaultOpen,
  onOpenChange,
  placeholder,
  min,
  max,
  maximumDays,
  unavailable,
  weekStartsOn,
  weekdayFormat,
  fixedWeeks = true,
  clearable = false,
  readonly,
  name,
  variant,
  size: sizeProp,
  disabled: disabledProp,
  invalid: invalidProp,
  onClear,
  leading,
  className,
  ...attrs
}: DateRangePickerProps) {
  const t = useUiLocale()
  const outer = useInputGroup()
  const [model = null, setModel] = useControllableState<DateRangeValue | null>({
    prop: value,
    defaultProp: defaultValue ?? null,
    onChange: onValueChange as ((value: DateRangeValue | null) => void) | undefined,
    caller: 'DateRangePicker',
  })
  const [open = false, setOpen] = useControllableState<boolean>({
    prop: openProp,
    defaultProp: defaultOpen ?? false,
    onChange: onOpenChange,
    caller: 'DateRangePicker',
  })

  const size = outer ? outer.size : sizeProp
  const { invalid, disabled } = useFieldControl(
    {
      invalid: invalidProp || !!outer?.invalid,
      disabled: disabledProp || !!outer?.disabled,
    },
    attrs,
  )
  const calendarSize: CalendarVariants['size'] = size ?? 'md'

  function pick(next: DateRangeValue | null) {
    setModel(next)
    if (next?.start && next.end) setOpen(false)
  }

  return (
    <PopoverRoot open={open} onOpenChange={setOpen} modal>
      <PopoverAnchor asChild>
        <div
          data-hn-date-range-picker=""
          data-invalid={invalid ? '' : undefined}
          data-disabled={disabled ? '' : undefined}
          className={cn(
            outer ? inputEmbedded() : inputHost({ variant, size: sizeProp }),
            className,
          )}
        >
          <InputGroupScope size={size} disabled={disabled} invalid={invalid}>
            <DateRangeField
              {...attrs}
              value={model}
              placeholder={placeholder}
              min={min}
              max={max}
              clearable={clearable}
              readonly={readonly}
              name={name}
              onValueChange={setModel}
              onClear={onClear}
              leading={leading}
            />
          </InputGroupScope>
          <PopoverTrigger asChild>
            <InputAction label={t.datePicker.open} disabled={disabled}>
              <CalendarRangeIcon />
            </InputAction>
          </PopoverTrigger>
        </div>
      </PopoverAnchor>
      <PopoverPortal>
        <PopoverContent
          asChild
          side="bottom"
          align="start"
          sideOffset={8}
          onOpenAutoFocus={event => event.preventDefault()}
        >
          <Card padded={false} className={datePickerContent()}>
            <RangeCalendar
              value={model}
              placeholder={placeholder}
              min={min}
              max={max}
              maximumDays={maximumDays}
              unavailable={unavailable}
              weekStartsOn={weekStartsOn}
              weekdayFormat={weekdayFormat}
              fixedWeeks={fixedWeeks}
              size={calendarSize}
              readonly={readonly}
              autofocus
              onValueChange={pick}
            />
          </Card>
        </PopoverContent>
      </PopoverPortal>
    </PopoverRoot>
  )
}
