// packages/react/src/components/table/TableHead.tsx
import type { Ref, ThHTMLAttributes } from 'react'
import { cn } from '../../lib/cn'
import { tableCell, type TableCellVariants } from './table.variants'

export interface TableHeadProps extends Omit<ThHTMLAttributes<HTMLTableCellElement>, 'align'> {
  scope?: 'col' | 'row' | 'colgroup' | 'rowgroup'
  align?: TableCellVariants['align']
  sticky?: boolean
  ref?: Ref<HTMLTableCellElement>
}

export function TableHead({
  scope = 'col',
  align,
  sticky = false,
  className,
  ...props
}: TableHeadProps) {
  return (
    <th
      {...props}
      scope={scope}
      className={cn(tableCell({ align, sticky, head: true }), className)}
    />
  )
}

// packages/vue/src/components/table/TableHead.vue
<script setup lang="ts">
  import { cn } from '../../lib/cn'
  import { tableCell, type TableCellVariants } from './table.variants'

  defineOptions({ name: 'HnTableHead' })

  const props = withDefaults(
    defineProps<{
      scope?: 'col' | 'row' | 'colgroup' | 'rowgroup'
      align?: TableCellVariants['align']
      sticky?: boolean
      class?: string
    }>(),
    { scope: 'col', sticky: false },
  )
</script>

<template>
  <th
    :scope="props.scope"
    :class="cn(tableCell({ align: props.align, sticky: props.sticky, head: true }), props.class)"
  >
    <slot />
  </th>
</template>
