// packages/react/src/components/chip/Chip.tsx
'use client'

import { useEffect } from 'react'
import type {
  AnchorHTMLAttributes,
  HTMLAttributes,
  KeyboardEvent,
  MouseEvent,
  ReactNode,
  Ref,
} from 'react'
import { cn } from '../../lib/cn'
import { devWarn } from '../../lib/dev'
import { hasContent } from '../../lib/content'
import { Primitive, type PrimitiveProps } from '../../lib/primitive'
import { useUiLocale } from '../../locale'
import { Ripple } from '../ripple/Ripple'
import { CloseButton } from '../close-button/CloseButton'
import { IconSlot } from './IconSlot'
import { chip, chipRemove, type ChipVariants } from './chip.variants'
import { useControllableState } from '../../primitives/utils/controllable-state'

export interface ChipProps
  extends
    PrimitiveProps,
    HTMLAttributes<HTMLElement>,
    Pick<AnchorHTMLAttributes<HTMLElement>, 'href' | 'target' | 'rel' | 'download'> {
  variant?: ChipVariants['variant']
  tone?: ChipVariants['tone']
  size?: ChipVariants['size']
  selectable?: boolean
  removable?: boolean
  disabled?: boolean
  ripple?: boolean
  selected?: boolean
  defaultSelected?: boolean
  onSelectedChange?: (selected: boolean) => void
  onRemove?: () => void
  icon?: ReactNode
  ref?: Ref<HTMLElement>
  [attribute: `data-${string}`]: string | undefined
}

export function Chip({
  as,
  asChild,
  variant,
  tone,
  size,
  selectable,
  removable: removableProp,
  disabled,
  ripple = true,
  selected: selectedProp,
  defaultSelected = false,
  onSelectedChange,
  onRemove,
  icon,
  className,
  children,
  onClick,
  onClickCapture,
  ...attrs
}: ChipProps) {
  const t = useUiLocale()
  const [selected, setSelected] = useControllableState({
    prop: selectedProp,
    defaultProp: defaultSelected,
    onChange: onSelectedChange,
    caller: 'Chip',
  })

  const conflict = !!selectable && !!removableProp
  useEffect(() => {
    if (conflict) devWarn('Chip', 'selectable 与 removable 不能同时使用，removable 已忽略')
  }, [conflict])

  const tag = as ?? (selectable ? 'button' : 'span')
  const nativeButton = tag === 'button' && !asChild
  const interactive = !!selectable || tag === 'button' || tag === 'a' || !!asChild
  const rootAttrs = nativeButton
    ? { type: 'button' as const, disabled }
    : interactive && disabled
      ? { 'data-disabled': '', 'aria-disabled': 'true' as const, tabIndex: -1 }
      : disabled
        ? { 'data-disabled': '' }
        : undefined
  const removable = !!removableProp && !selectable
  const showCheck = !!selectable && selected
  const hasIcon = hasContent(icon)

  function guard(event: MouseEvent<HTMLElement>) {
    if (disabled) {
      event.preventDefault()
      event.stopPropagation()
      event.nativeEvent.stopImmediatePropagation()
      return
    }
    onClickCapture?.(event)
  }

  function toggle(event: MouseEvent<HTMLElement>) {
    if (selectable) setSelected(!selected)
    onClick?.(event)
  }

  function onRemoveKeydown(event: KeyboardEvent<HTMLElement>) {
    if (event.key !== 'Backspace' && event.key !== 'Delete') return
    event.preventDefault()
    onRemove?.()
  }

  return (
    <Primitive
      as={tag}
      data-hn-chip=""
      asChild={asChild}
      {...rootAttrs}
      aria-pressed={selectable ? selected : undefined}
      data-state={showCheck ? 'selected' : undefined}
      {...attrs}
      className={cn(
        chip({
          variant,
          tone,
          size,
          interactive,
          selected: showCheck,
          disabled,
        }),
        className,
      )}
      onClickCapture={guard}
      onClick={toggle}
    >
      {asChild ? (
        children
      ) : (
        <>
          {interactive && ripple && <Ripple disabled={disabled} />}
          {(selectable || hasIcon) && (
            <IconSlot size={size} checked={showCheck} icon={hasIcon}>
              {icon}
            </IconSlot>
          )}
          {children}
          {removable && (
            <CloseButton
              size="xs"
              label={t.chip.remove}
              disabled={disabled}
              className={chipRemove({ size })}
              onClick={event => {
                event.stopPropagation()
                onRemove?.()
              }}
              onKeyDown={onRemoveKeydown}
            />
          )}
        </>
      )}
    </Primitive>
  )
}

// packages/vue/src/components/chip/Chip.vue
<script setup lang="ts">
  import { computed, useSlots } from 'vue'
  import { cn } from '../../lib/cn'
  import { devWarn } from '../../lib/dev'
  import { useUiLocale } from '../../locale'
  import Ripple from '../ripple/Ripple.vue'
  import CloseButton from '../close-button/CloseButton.vue'
  import IconSlot from './IconSlot.vue'
  import { useChipRoot } from './composables/useChipRoot'
  import { chip, chipRemove, type ChipVariants } from './chip.variants'
  import type { PrimitiveProps } from '../../primitives/primitive'
  import { Primitive } from '../../primitives/primitive'

  defineOptions({ name: 'HnChip' })

  const props = withDefaults(
    defineProps<
      PrimitiveProps & {
        variant?: ChipVariants['variant']
        tone?: ChipVariants['tone']
        size?: ChipVariants['size']
        selectable?: boolean
        removable?: boolean
        disabled?: boolean
        ripple?: boolean
        class?: string
      }
    >(),
    { ripple: true },
  )

  const selected = defineModel<boolean>('selected', { default: false })

  const emit = defineEmits<{ remove: [] }>()

  const slots = useSlots()
  const t = useUiLocale()

  if (props.selectable && props.removable) {
    devWarn('Chip', 'selectable 与 removable 不能同时使用，removable 已忽略')
  }

  const { tag, interactive, attrs } = useChipRoot(props)
  const removable = computed(() => props.removable && !props.selectable)
  const showCheck = computed(() => props.selectable && selected.value)

  function guard(event: MouseEvent) {
    if (!props.disabled) return
    event.preventDefault()
    event.stopImmediatePropagation()
  }

  function toggle() {
    if (props.selectable) selected.value = !selected.value
  }

  function onRemoveKeydown(event: KeyboardEvent) {
    if (event.key !== 'Backspace' && event.key !== 'Delete') return
    event.preventDefault()
    emit('remove')
  }
</script>

<template>
  <Primitive
    :as="tag"
    data-hn-chip
    :as-child="props.asChild"
    v-bind="attrs"
    :aria-pressed="props.selectable ? selected : undefined"
    :data-state="showCheck ? 'selected' : undefined"
    :class="
      cn(
        chip({
          variant: props.variant,
          tone: props.tone,
          size: props.size,
          interactive,
          selected: showCheck,
          disabled: props.disabled,
        }),
        props.class,
      )
    "
    @click.capture="guard"
    @click="toggle"
  >
    <Ripple v-if="interactive && props.ripple" :disabled="props.disabled" />
    <IconSlot
      v-if="props.selectable || slots.icon"
      :size="props.size"
      :checked="showCheck"
      :icon="!!slots.icon"
    >
      <slot name="icon" />
    </IconSlot>
    <slot />
    <CloseButton
      v-if="removable"
      size="xs"
      :label="t.chip.remove"
      :disabled="props.disabled"
      :class="chipRemove({ size: props.size })"
      @click.stop="emit('remove')"
      @keydown="onRemoveKeydown"
    />
  </Primitive>
</template>
