// docs/react/demos/en/search-input/form.tsx
'use client'

import { useState } from 'react'
import * as v from 'valibot'
import { Button, Form, FormField, SearchInput, Text } from '@hina-ui/react'

const schema = v.object({
  keyword: v.pipe(
    v.string('Enter a keyword'),
    v.trim(),
    v.nonEmpty('Enter a keyword'),
    v.minLength(2, 'At least 2 characters'),
  ),
})

export default function Demo() {
  const [values, setValues] = useState({ keyword: '' })
  const [result, setResult] = useState('')

  async function search(data: unknown) {
    await new Promise(resolve => setTimeout(resolve, 600))
    setResult((data as { keyword: string }).keyword)
  }

  return (
    <Form values={values} rules={schema} className="w-80" onSubmit={search}>
      {({ submitting }) => (
        <>
          <FormField name="keyword" label="Search works">
            <SearchInput
              value={values.keyword}
              onValueChange={keyword => setValues({ ...values, keyword })}
              placeholder="Title or alias"
            />
          </FormField>
          <Button type="submit" loading={submitting} className="self-start">
            Search
          </Button>
          {result && (
            <Text tone="muted" size="sm">
              Searching for &quot;{result}&quot;.
            </Text>
          )}
        </>
      )}
    </Form>
  )
}

// docs/vue/app/demos/en/editable/form.vue
<script setup lang="ts">
  import { reactive, ref } from 'vue'
  import * as v from 'valibot'
  import { Button, Editable, Form, FormField, Text } from '@hina-ui/vue'

  const values = reactive({ displayName: '' })
  const editing = ref(false)
  const saved = ref('')
  const schema = v.object({
    displayName: v.pipe(v.string(), v.trim(), v.minLength(2, 'Use at least 2 characters')),
  })

  async function save(data: unknown) {
    await new Promise(resolve => setTimeout(resolve, 600))
    saved.value = (data as { displayName: string }).displayName
  }
</script>

<template>
  <Form
    v-slot="{ submitting }"
    :values="values"
    :rules="schema"
    class="w-full max-w-sm"
    @submit="save"
  >
    <FormField
      name="displayName"
      label="Display name"
      description="Confirm the field edit before saving the profile."
      required
    >
      <Editable
        v-model="values.displayName"
        v-model:editing="editing"
        name="displayName"
        placeholder="Enter a display name"
      />
    </FormField>
    <Button type="submit" :loading="submitting" :disabled="editing" class="self-start">
      Save profile
    </Button>
    <Text v-if="saved" role="status" size="sm" tone="muted">Saved: {{ saved }}</Text>
  </Form>
</template>
