// packages/vue/src/components/section/Section.vue
<script setup lang="ts">
  import { computed, useAttrs, useId } from 'vue'
  import { cn } from '../../lib/cn'
  import Heading from '../heading/Heading.vue'

  defineOptions({ name: 'HnSection' })

  const props = defineProps<{
    title?: string
    id?: string
    class?: string
  }>()

  const attrs = useAttrs()
  const headingId = useId()
  const labelledBy = computed(() =>
    props.title && !attrs['aria-label'] && !attrs['aria-labelledby'] ? headingId : undefined,
  )
</script>

<template>
  <section
    :id="props.id"
    :aria-labelledby="labelledBy"
    :class="cn('flex scroll-mt-6 flex-col gap-4', props.class)"
  >
    <Heading v-if="props.title" :id="headingId" :level="2">{{ props.title }}</Heading>
    <slot />
  </section>
</template>

// packages/react/src/components/section/Section.tsx
import { useId, type HTMLAttributes, type Ref } from 'react'
import { cn } from '../../lib/cn'
import { Heading } from '../heading/Heading'

export interface SectionProps extends Omit<HTMLAttributes<HTMLElement>, 'title'> {
  title?: string
  ref?: Ref<HTMLElement>
}

export function Section({ title, className, children, ...props }: SectionProps) {
  const headingId = useId()
  const labelledBy =
    props['aria-labelledby'] ?? (title && !props['aria-label'] ? headingId : undefined)
  return (
    <section
      {...props}
      aria-labelledby={labelledBy}
      className={cn('flex scroll-mt-6 flex-col gap-4', className)}
    >
      {title ? (
        <Heading id={headingId} level={2}>
          {title}
        </Heading>
      ) : null}
      {children}
    </section>
  )
}
