// docs/react/demos/zh-CN/pagination/loading.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { Card, Pagination, Stack, Text, type PaginationChange } from '@hina-ui/react'

export default function Demo() {
  const [page, setPage] = useState(1)
  const [displayedPage, setDisplayedPage] = useState(1)
  const [pending, setPending] = useState(false)
  const timer = useRef<ReturnType<typeof setTimeout>>(undefined)

  function change(value: PaginationChange) {
    setPending(true)
    clearTimeout(timer.current)
    timer.current = setTimeout(() => {
      setDisplayedPage(value.page)
      setPending(false)
    }, 1000)
  }

  useEffect(() => () => clearTimeout(timer.current), [])

  return (
    <Pagination
      value={page}
      onValueChange={setPage}
      total={96}
      pageSize={5}
      pending={pending}
      showInfo
      onChange={change}
      renderList={() => (
        <Stack gap="xs">
          {[1, 2, 3, 4, 5].map(index => (
            <Card key={index}>
              <Text size="sm">{(displayedPage - 1) * 5 + index}</Text>
            </Card>
          ))}
        </Stack>
      )}
    />
  )
}

// docs/vue/app/demos/en/pagination/loading.vue
<script setup lang="ts">
  import { onBeforeUnmount, ref } from 'vue'
  import { Card, Pagination, Stack, Text, type PaginationChange } from '@hina-ui/vue'

  const page = ref(1)
  const displayedPage = ref(1)
  const pending = ref(false)
  let timer: ReturnType<typeof setTimeout> | undefined

  function change(value: PaginationChange) {
    pending.value = true
    clearTimeout(timer)
    timer = setTimeout(() => {
      displayedPage.value = value.page
      pending.value = false
    }, 1000)
  }

  onBeforeUnmount(() => clearTimeout(timer))
</script>

<template>
  <Pagination
    v-model="page"
    :total="96"
    :page-size="5"
    :pending="pending"
    show-info
    @change="change"
  >
    <template #list>
      <Stack gap="xs">
        <Card v-for="index in 5" :key="index">
          <Text size="sm">{{ (displayedPage - 1) * 5 + index }}</Text>
        </Card>
      </Stack>
    </template>
  </Pagination>
</template>
