// packages/react/src/components/indicator/Indicator.tsx
import { cn } from '../../lib/cn'
import { Primitive, type PrimitiveElementProps } from '../../lib/primitive'
import { VisuallyHidden } from '../visually-hidden/VisuallyHidden'
import { indicator, type IndicatorVariants } from './indicator.variants'

export interface IndicatorProps extends Omit<PrimitiveElementProps, 'children'> {
  tone?: IndicatorVariants['tone']
  size?: IndicatorVariants['size']
  pulse?: boolean
  label?: string
}

export function Indicator({
  as = 'span',
  asChild,
  tone,
  size,
  pulse = false,
  label,
  className,
  ...attrs
}: IndicatorProps) {
  return (
    <Primitive
      as={as}
      asChild={asChild}
      aria-hidden={label ? undefined : 'true'}
      {...attrs}
      className={cn(indicator({ tone, size }), className)}
    >
      {pulse ? (
        <span aria-hidden="true" className="hn-ping absolute inset-0 rounded-full bg-inherit" />
      ) : null}
      {label ? <VisuallyHidden>{label}</VisuallyHidden> : null}
    </Primitive>
  )
}

// packages/vue/src/components/indicator/Indicator.vue
<script setup lang="ts">
  import VisuallyHidden from '../visually-hidden/VisuallyHidden.vue'
  import { cn } from '../../lib/cn'
  import { indicator, type IndicatorVariants } from './indicator.variants'
  import type { PrimitiveProps } from '../../primitives/primitive'
  import { Primitive } from '../../primitives/primitive'

  defineOptions({ name: 'HnIndicator' })

  const props = withDefaults(
    defineProps<
      PrimitiveProps & {
        tone?: IndicatorVariants['tone']
        size?: IndicatorVariants['size']
        pulse?: boolean
        label?: string
        class?: string
      }
    >(),
    { as: 'span' },
  )
</script>

<template>
  <Primitive
    :as="props.as"
    :as-child="props.asChild"
    :aria-hidden="props.label ? undefined : 'true'"
    :class="cn(indicator({ tone: props.tone, size: props.size }), props.class)"
  >
    <span
      v-if="props.pulse"
      aria-hidden="true"
      class="hn-ping absolute inset-0 rounded-full bg-inherit"
    />
    <VisuallyHidden v-if="props.label">{{ props.label }}</VisuallyHidden>
  </Primitive>
</template>
