// docs/react/demos/zh-CN/dropdown-menu/shortcut.tsx
import { Copy, Scissors, Trash2 } from 'lucide-react'
import { Button, DropdownMenu, DropdownMenuItem, Kbd } from '@hina-ui/react'

export default function Demo() {
  return (
    <DropdownMenu
      label="编辑"
      content={
        <>
          <DropdownMenuItem icon={<Copy />} trailing={<Kbd>Ctrl C</Kbd>}>
            复制
          </DropdownMenuItem>
          <DropdownMenuItem icon={<Scissors />} trailing={<Kbd>Ctrl X</Kbd>}>
            剪切
          </DropdownMenuItem>
          <DropdownMenuItem tone="danger" icon={<Trash2 />} trailing={<Kbd>Del</Kbd>}>
            删除
          </DropdownMenuItem>
        </>
      }
    >
      <Button variant="outline" tone="neutral">
        编辑
      </Button>
    </DropdownMenu>
  )
}

// docs/app/demos/zh-CN/dropdown-menu/shortcut.vue
<script setup lang="ts">
  import { Copy, Scissors, Trash2 } from '@lucide/vue'
  import { Button, DropdownMenu, DropdownMenuItem, Kbd } from '@hina-ui/vue'
</script>

<template>
  <DropdownMenu label="编辑">
    <Button variant="outline" tone="neutral">编辑</Button>
    <template #content>
      <DropdownMenuItem>
        <template #icon>
          <Copy />
        </template>
        复制
        <template #trailing>
          <Kbd>Ctrl C</Kbd>
        </template>
      </DropdownMenuItem>
      <DropdownMenuItem>
        <template #icon>
          <Scissors />
        </template>
        剪切
        <template #trailing>
          <Kbd>Ctrl X</Kbd>
        </template>
      </DropdownMenuItem>
      <DropdownMenuItem tone="danger">
        <template #icon>
          <Trash2 />
        </template>
        删除
        <template #trailing>
          <Kbd>Del</Kbd>
        </template>
      </DropdownMenuItem>
    </template>
  </DropdownMenu>
</template>
