// packages/react/src/components/data-table/DataTableSelection.tsx
'use client'

import { useLayoutEffect, useRef } from 'react'
import clsx from 'clsx'
import { Checkbox } from '../checkbox/Checkbox'
import { checkboxBox } from '../checkbox/checkbox.variants'
import { radioDot } from '../radio-group/radio-group.variants'
import { Transition } from '../../lib/transition/Transition'

export interface DataTableSelectionProps {
  single?: boolean
  checked: boolean | 'indeterminate'
  disabled?: boolean
  label: string
  name: string
  onChange?: (value: boolean) => void
}

export function DataTableSelection({
  single,
  checked,
  disabled,
  label,
  name,
  onChange,
}: DataTableSelectionProps) {
  const input = useRef<HTMLInputElement>(null)
  useLayoutEffect(() => {
    input.current?.toggleAttribute('checked', checked === true)
  }, [checked])
  if (!single)
    return (
      <Checkbox
        className="mx-auto"
        checked={checked}
        disabled={disabled}
        aria-label={label}
        onCheckedChange={value => onChange?.(value === true)}
      />
    )
  return (
    <label className={clsx('relative inline-grid', disabled && 'opacity-50')}>
      <input
        ref={input}
        type="radio"
        name={name}
        checked={checked === true}
        disabled={disabled}
        aria-label={label}
        className="peer absolute inset-0 z-10 size-full cursor-pointer opacity-0"
        onChange={() => onChange?.(true)}
      />
      <span
        aria-hidden="true"
        className={clsx(
          checkboxBox({ shape: 'round' }),
          'peer-focus-visible:outline-(--hn-focus-ring) peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2',
        )}
        data-state={checked === true ? 'checked' : 'unchecked'}
      >
        <Transition
          show={checked === true}
          enterActiveClass="hn-transition-press"
          enterFromClass="scale-50 opacity-0"
          leaveActiveClass="hn-transition"
          leaveToClass="scale-50 opacity-0"
        >
          <span className={radioDot()} />
        </Transition>
      </span>
    </label>
  )
}

// packages/vue/src/components/data-table/DataTableSelection.vue
<script setup lang="ts">
  import Checkbox from '../checkbox/Checkbox.vue'
  import { checkboxBox } from '../checkbox/checkbox.variants'
  import { radioDot } from '../radio-group/radio-group.variants'
  defineProps<{
    single?: boolean
    checked: boolean | 'indeterminate'
    disabled?: boolean
    label: string
    name: string
  }>()
  defineEmits<{ change: [value: boolean] }>()
</script>
<template>
  <label v-if="single" class="relative inline-grid" :class="disabled && 'opacity-50'">
    <input
      type="radio"
      :name="name"
      :checked="checked === true"
      :disabled="disabled"
      :aria-label="label"
      class="peer absolute inset-0 z-10 size-full cursor-pointer opacity-0"
      @change="$emit('change', true)"
    />
    <span
      aria-hidden="true"
      :class="[
        checkboxBox({ shape: 'round' }),
        'peer-focus-visible:outline-(--hn-focus-ring) peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2',
      ]"
      :data-state="checked === true ? 'checked' : 'unchecked'"
    >
      <Transition
        enter-active-class="hn-transition-press"
        enter-from-class="scale-50 opacity-0"
        leave-active-class="hn-transition"
        leave-to-class="scale-50 opacity-0"
      >
        <span v-if="checked === true" :class="radioDot()" />
      </Transition>
    </span>
  </label>
  <Checkbox
    v-else
    class="mx-auto"
    :model-value="checked"
    :disabled="disabled"
    :aria-label="label"
    @update:model-value="$emit('change', $event === true)"
  />
</template>
