// docs/react/demos/en/sheet/locked.tsx
'use client'

import { useState } from 'react'
import { Button, Sheet, Text } from '@hina-ui/react'

export default function Demo() {
  const [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false)

  async function save() {
    setSaving(true)
    await new Promise(resolve => setTimeout(resolve, 1500))
    setSaving(false)
    setOpen(false)
  }

  return (
    <Sheet
      open={open}
      onOpenChange={setOpen}
      title="Save changes"
      description="The sheet stays put while saving."
      locked={saving}
      renderContent={() => (
        <Text>
          For a second and a half after pressing Save, dragging, Esc and the scrim do nothing.
        </Text>
      )}
      renderFooter={({ close }) => (
        <>
          <Button variant="soft" tone="neutral" disabled={saving} onClick={close}>
            Cancel
          </Button>
          <Button loading={saving} onClick={save}>
            Save
          </Button>
        </>
      )}
    >
      <Button variant="outline" tone="neutral">
        Open
      </Button>
    </Sheet>
  )
}

// docs/vue/app/demos/en/sheet/locked.vue
<script setup lang="ts">
  import { ref } from 'vue'
  import { Button, Sheet, Text } from '@hina-ui/vue'

  const open = ref(false)
  const saving = ref(false)

  async function save() {
    saving.value = true
    await new Promise(resolve => setTimeout(resolve, 1500))
    saving.value = false
    open.value = false
  }
</script>

<template>
  <Sheet
    v-model:open="open"
    title="Save changes"
    description="The sheet stays put while saving."
    :locked="saving"
  >
    <Button variant="outline" tone="neutral">Open</Button>
    <template #content>
      <Text>
        For a second and a half after pressing Save, dragging, Esc and the scrim do nothing.
      </Text>
    </template>
    <template #footer="{ close }">
      <Button variant="soft" tone="neutral" :disabled="saving" @click="close">Cancel</Button>
      <Button :loading="saving" @click="save">Save</Button>
    </template>
  </Sheet>
</template>
