// docs-react/demos/en/date-range-field/form.tsx
'use client'

import { useState } from 'react'
import * as v from 'valibot'
import { Button, DateRangeField, Form, FormField, Text, type DateRangeValue } from '@hina-ui/react'

const schema = v.object({
  period: v.pipe(
    v.nullable(v.object({ start: v.nullable(v.string()), end: v.nullable(v.string()) })),
    v.check(value => !!value?.start && !!value?.end, 'Fill in the whole event period'),
  ),
})

export default function Demo() {
  const [values, setValues] = useState<{ period: DateRangeValue | null }>({ period: null })
  const [saved, setSaved] = useState('')

  async function save(data: unknown) {
    await new Promise(resolve => setTimeout(resolve, 600))
    setSaved(JSON.stringify(data))
  }

  return (
    <Form values={values} rules={schema} className="w-80" onSubmit={save}>
      {({ submitting }) => (
        <>
          <FormField name="period" label="Event period" required>
            <DateRangeField value={values.period} onValueChange={period => setValues({ period })} />
          </FormField>
          <Button type="submit" loading={submitting} className="self-start">
            Save
          </Button>
          {saved && (
            <Text tone="muted" size="sm">
              Saved: {saved}
            </Text>
          )}
        </>
      )}
    </Form>
  )
}

// docs/vue/app/demos/en/switch/form.vue
<script setup lang="ts">
  import { reactive, ref } from 'vue'
  import * as v from 'valibot'
  import { Button, Form, FormField, Input, Switch, Text } from '@hina-ui/vue'

  const schema = v.pipe(
    v.object({
      isPublic: v.boolean(),
      summary: v.string(),
    }),
    v.forward(
      v.check(
        input => !input.isPublic || input.summary.trim().length > 0,
        'A public work needs a summary',
      ),
      ['summary'],
    ),
  )

  const values = reactive({ isPublic: true, summary: '' })
  const saved = ref('')

  async function save(data: unknown) {
    await new Promise(resolve => setTimeout(resolve, 600))
    saved.value = JSON.stringify(data)
  }
</script>

<template>
  <Form v-slot="{ submitting }" :values="values" :rules="schema" class="w-80" @submit="save">
    <FormField name="isPublic">
      <Switch v-model="values.isPublic">Public</Switch>
    </FormField>
    <FormField name="summary" label="Summary">
      <Input v-model="values.summary" />
    </FormField>
    <Button type="submit" :loading="submitting" class="self-start">Save</Button>
    <Text v-if="saved" tone="muted" size="sm">Saved: {{ saved }}</Text>
  </Form>
</template>
