// docs/vue/app/demos/en/data-list/pagination.vue
<script setup lang="ts">
  import { ref } from 'vue'
  import { DataList, Select, Text } from '@hina-ui/vue'
  import { dataListDemo } from '../../data-list'
  const items = dataListDemo('en')
  const page = ref(1)
  const pageSize = ref(10)
  const sizes = [10, 20, 50].map(value => ({ value, label: `${value} per page` }))
</script>
<template>
  <DataList
    v-model:page="page"
    v-model:page-size="pageSize"
    :items="items"
    item-key="id"
    item-title="title"
    item-description="subtitle"
    pagination
    class="max-w-2xl"
  >
    <template #header="{ pageSize: size, setPageSize }">
      <Text size="sm" tone="muted">{{ items.length }} items</Text>
      <Select
        :model-value="size"
        :options="sizes"
        size="sm"
        class="w-36 max-w-full"
        aria-label="Items per page"
        @update:model-value="value => setPageSize(Number(value))"
      />
    </template>
    <template #meta="{ item }">
      <Text size="xs" tone="muted">{{ item.released }}</Text>
    </template>
  </DataList>
</template>

// docs/react/demos/en/data-list/pagination.tsx
'use client'

import { useState } from 'react'
import { DataList, Select, Text } from '@hina-ui/react'
import { dataListDemo } from '../../data-list'

const items = dataListDemo('en')
const sizes = [10, 20, 50].map(value => ({ value, label: `${value} per page` }))

export default function Demo() {
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)

  return (
    <DataList
      page={page}
      onPageChange={setPage}
      pageSize={pageSize}
      onPageSizeChange={setPageSize}
      items={items}
      itemKey="id"
      itemTitle="title"
      itemDescription="subtitle"
      pagination
      className="max-w-2xl"
      renderHeader={({ pageSize: size, setPageSize: resize }) => (
        <>
          <Text size="sm" tone="muted">
            {items.length} items
          </Text>
          <Select
            value={size}
            options={sizes}
            size="sm"
            className="w-36 max-w-full"
            aria-label="Items per page"
            onValueChange={value => resize(Number(value))}
          />
        </>
      )}
      renderMeta={({ item }) => (
        <Text size="xs" tone="muted">
          {item.released}
        </Text>
      )}
    />
  )
}
