// docs/app/demos/en/stack/gap.vue
<script setup lang="ts">
  import { Card, Inline, Stack, Text } from '@hikarinagi/ui'

  const gaps = ['none', 'xs', 'sm', 'md', 'lg', 'xl'] as const
</script>

<template>
  <Inline align="start" class="gap-8">
    <Stack v-for="gap in gaps" :key="gap" gap="xs">
      <Text tone="muted" size="sm">{{ gap }}</Text>
      <Stack :gap="gap">
        <Card class="bg-inset size-10" :padded="false" />
        <Card class="bg-inset size-10" :padded="false" />
        <Card class="bg-inset size-10" :padded="false" />
      </Stack>
    </Stack>
  </Inline>
</template>

// docs/react/demos/zh-CN/stack/gap.tsx
import { Card, Inline, Stack, Text } from '@hina-ui/react'

const gaps = ['none', 'xs', 'sm', 'md', 'lg', 'xl'] as const

export default function Demo() {
  return (
    <Inline align="start" className="gap-8">
      {gaps.map(gap => (
        <Stack key={gap} gap="xs">
          <Text tone="muted" size="sm">
            {gap}
          </Text>
          <Stack gap={gap}>
            <Card className="bg-inset size-10" padded={false} />
            <Card className="bg-inset size-10" padded={false} />
            <Card className="bg-inset size-10" padded={false} />
          </Stack>
        </Stack>
      ))}
    </Inline>
  )
}
